// frontend/src/svelte/components/activity/ActivityFeed.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { Bell, X, Inbox, Loader2 } from 'lucide-svelte'
  import { formatDistanceToNow } from 'date-fns'
  import { activityStore, activityList, unreadActivityCount } from '../../stores/activity'
  import type { Activity, ActivityType } from '../../stores/activity'

  const filters: { label: string; value: ActivityType | null }[] = [
    { label: 'All', value: null },
    { label: 'Mentions', value: 'mention' },
    { label: 'Threads', value: 'thread_reply' },
  ]

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && $activityStore.isOpen) {
      activityStore.closeFeed()
    }
  }

  onMount(() => {
    document.addEventListener('keydown', handleKeydown)
  })

  onDestroy(() => {
    document.removeEventListener('keydown', handleKeydown)
  })

  function actionText(type: ActivityType): string {
    switch (type) {
      case 'mention':
        return 'mentioned you'
      case 'reply':
        return 'replied to your message'
      case 'reaction':
        return 'reacted to your message'
      case 'dm':
        return 'sent you a message'
      case 'thread_reply':
        return 'replied in a thread you follow'
      default:
        return 'interacted with you'
    }
  }

  function handleActivityClick(activity: Activity) {
    if (!activity.read) {
      void activityStore.markRead(activity.id)
    }
    activityStore.closeFeed()
  }
</script>

{#if $activityStore.isOpen}
  <div
    data-testid="activity-feed"
    class="flex w-80 shrink-0 flex-col border-l border-border-1 bg-bg-surface-1 animate-slide-in-right"
    role="dialog"
    aria-label="Activity feed"
    aria-modal="true"
  >
    <!-- Header -->
    <div class="flex h-[var(--header-height)] items-center justify-between border-b border-border-1 px-4">
      <div class="flex items-center gap-2">
        <Bell class="h-5 w-5 text-text-1" />
        <h2 class="text-sm font-semibold text-text-1">
          Activity
          {#if $unreadActivityCount > 0}
            <span class="ml-2 text-xs font-normal text-danger">({$unreadActivityCount} unread)</span>
          {/if}
        </h2>
      </div>
      <div class="flex items-center gap-2">
        {#if $unreadActivityCount > 0}
          <button
            class="text-xs text-brand hover:text-brand-hover"
            on:click={() => activityStore.markAllRead()}
          >
            Mark all read
          </button>
        {/if}
        <button
          class="flex h-8 w-8 items-center justify-center rounded-r-1 text-text-3 transition-standard hover:bg-bg-surface-2 hover:text-text-1 focus-ring"
          aria-label="Close activity feed"
          on:click={() => activityStore.closeFeed()}
        >
          <X class="h-4 w-4" />
        </button>
      </div>
    </div>

    <!-- Filters -->
    <div class="flex gap-1.5 overflow-x-auto border-b border-border-1 p-3">
      {#each filters as filter (filter.label)}
        <button
          class="whitespace-nowrap rounded-full px-3 py-1 text-xs font-medium transition-standard"
          class:bg-text-1={$activityStore.filter === filter.value}
          class:text-bg-surface-1={$activityStore.filter === filter.value}
          class:bg-bg-surface-2={$activityStore.filter !== filter.value}
          class:text-text-2={$activityStore.filter !== filter.value}
          class:hover:bg-bg-surface-3={$activityStore.filter !== filter.value}
          on:click={() => activityStore.setFilter(filter.value)}
        >
          {filter.label}
        </button>
      {/each}
    </div>

    <!-- List -->
    <div class="flex-1 overflow-y-auto custom-scrollbar-thin">
      {#if $activityStore.isLoading && $activityList.length === 0}
        <div class="flex items-center justify-center py-12 text-text-3">
          <Loader2 class="mr-2 h-6 w-6 animate-spin" />
          Loading...
        </div>
      {:else if $activityList.length === 0}
        <div class="px-4 py-12 text-center text-text-3">
          <Inbox class="mx-auto mb-3 h-12 w-12 opacity-40" />
          <p class="font-medium">No activity yet</p>
          <p class="mt-1 text-sm">Mentions, replies, and reactions will appear here</p>
        </div>
      {:else}
        <div class="divide-y divide-border-1">
          {#each $activityList as activity (activity.id)}
            <button
              class="flex w-full items-start gap-3 p-4 text-left transition-standard {!activity.read ? 'bg-brand/5' : ''} {activity.read ? 'hover:bg-bg-surface-2' : ''}"
              on:click={() => handleActivityClick(activity)}
            >
              <div class="w-1.5 self-stretch pt-1.5">
                {#if !activity.read}
                  <div class="h-1.5 w-1.5 rounded-full bg-brand"></div>
                {/if}
              </div>
              <div
                class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-bg-surface-2"
              >
                <span class="text-sm">
                  {#if activity.type === 'mention'}@
                  {:else if activity.type === 'reply'}💬
                  {:else if activity.type === 'reaction'}❤️
                  {:else if activity.type === 'dm'}✉️
                  {:else}🧵
                  {/if}
                </span>
              </div>
              <div class="min-w-0 flex-1">
                <div class="flex items-start justify-between gap-2">
                  <p class="text-sm leading-snug text-text-1">
                    <span class="font-semibold">{activity.actorUsername}</span>
                    {actionText(activity.type)}
                  </p>
                  <span class="mt-0.5 shrink-0 whitespace-nowrap text-xs text-text-3">
                    {formatDistanceToNow(new Date(activity.createdAt), { addSuffix: true })}
                  </span>
                </div>
                {#if activity.message}
                  <p class="mt-1 line-clamp-2 text-sm text-text-2">{activity.message}</p>
                {/if}
                {#if activity.type === 'reaction' && activity.reaction}
                  <p class="mt-1 text-base">{activity.reaction}</p>
                {/if}
                <p class="mt-1 text-xs text-text-3">
                  #{activity.channelName} · {activity.teamName}
                </p>
              </div>
            </button>
          {/each}

          {#if $activityStore.hasMore}
            <div class="p-4 text-center">
              <button
                class="text-sm text-brand hover:text-brand-hover disabled:opacity-50"
                disabled={$activityStore.isLoading}
                on:click={() => activityStore.loadMore()}
              >
                {$activityStore.isLoading ? 'Loading...' : 'Load more'}
              </button>
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </div>
{/if}

// frontend/src/components/activity/ActivityFeed.vue
<template>
  <Transition name="slide">
    <div
      v-if="isOpen"
      class="fixed inset-y-0 right-0 w-[400px] bg-white border-l border-gray-200 shadow-xl z-50 flex flex-col"
      role="dialog"
      aria-label="Activity feed"
      aria-modal="true"
    >
      <!-- Header -->
      <div class="flex items-center justify-between p-4 border-b border-gray-200">
        <div class="flex items-center gap-2">
          <Bell class="w-5 h-5" />
          <h2 class="text-lg font-semibold">
            Activity
            <span v-if="unreadCount > 0" class="ml-2 text-sm text-red-500 font-normal">
              ({{ unreadCount }} unread)
            </span>
          </h2>
        </div>
        <div class="flex items-center gap-2">
          <button
            v-if="unreadCount > 0"
            class="text-sm text-blue-500 hover:text-blue-600 px-2 py-1 rounded"
            @click="handleMarkAllRead"
          >
            Mark all read
          </button>
          <button
            class="p-1 hover:bg-gray-100 rounded"
            aria-label="Close activity feed"
            @click="close"
          >
            <X class="w-5 h-5" />
          </button>
        </div>
      </div>

      <!-- Filters -->
      <ActivityFilters
        :model-value="filter"
        @update:model-value="handleFilterChange"
      />

      <!-- Activity List -->
      <div class="flex-1 overflow-y-auto">
        <div v-if="isLoading && activities.length === 0" class="flex items-center justify-center py-12 text-gray-500">
          <Loader2 class="w-6 h-6 animate-spin mr-2" />
          Loading...
        </div>

        <div v-else-if="activities.length === 0" class="text-center py-12 text-gray-500 px-4">
          <Inbox class="w-12 h-12 mx-auto mb-3 opacity-40" />
          <p class="font-medium">No activity yet</p>
          <p class="text-sm mt-1">Mentions, replies, and reactions will appear here</p>
        </div>

        <div v-else class="divide-y divide-gray-100">
          <ActivityItem
            v-for="activity in activities"
            :key="activity.id"
            :activity="activity"
            @click="handleActivityClick(activity)"
            @mark-read="handleMarkRead(activity.id)"
          />

          <div v-if="hasMore" class="p-4 text-center">
            <button
              class="text-blue-500 hover:text-blue-600 text-sm disabled:opacity-50"
              :disabled="isLoading"
              @click="loadMore"
            >
              {{ isLoading ? 'Loading...' : 'Load more' }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </Transition>

  <!-- Backdrop -->
  <Transition name="fade">
    <div
      v-if="isOpen"
      class="fixed inset-0 bg-black/20 z-40"
      @click="close"
    />
  </Transition>
</template>

<script setup lang="ts">
import { log } from '@/utils/log';
import { computed, onMounted, onUnmounted } from 'vue'
import { Bell, X, Inbox, Loader2 } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { useActivityStore } from '../../features/activity/stores/activityStore'
import { activityService } from '../../features/activity/services/activityService'
import type { Activity } from '../../features/activity/types'
import { ActivityType } from '../../features/activity/types'
import ActivityItem from './ActivityItem.vue'
import ActivityFilters from './ActivityFilters.vue'

const store = useActivityStore()
const router = useRouter()

const isOpen = computed(() => store.isOpen)
const activities = computed(() => store.getActivities)
const unreadCount = computed(() => store.unreadCount)
const hasMore = computed(() => store.hasMore)
const isLoading = computed(() => store.isLoading)
const filter = computed(() => store.filter)

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && isOpen.value) {
    close()
  }
}

onMounted(() => document.addEventListener('keydown', handleKeydown))
onUnmounted(() => document.removeEventListener('keydown', handleKeydown))

function close() {
  activityService.closeFeed()
}

function loadMore() {
  activityService.loadMore()
}

function handleFilterChange(type: ActivityType | null) {
  activityService.setFilter(type)
}

async function handleMarkRead(activityId: string) {
  try {
    await activityService.markRead(activityId)
  } catch (error) {
    log.error('Failed to mark activity as read:', error)
  }
}

async function handleMarkAllRead() {
  try {
    await activityService.markAllRead()
  } catch (error) {
    log.error('Failed to mark all as read:', error)
  }
}

function handleActivityClick(activity: Activity) {
  if (!activity.read) {
    handleMarkRead(activity.id)
  }
  if (activity.rootId) {
    router.push(`/channels/${activity.channelId}?thread=${activity.rootId}`)
  } else {
    router.push(`/channels/${activity.channelId}?post=${activity.postId}`)
  }
  activityService.closeFeed()
}
</script>

<style scoped>
.slide-enter-active,
.slide-leave-active {
  transition: transform 0.2s ease-out;
}
.slide-enter-from,
.slide-leave-to {
  transform: translateX(100%);
}
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease-out;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
