// frontend/src/svelte/components/chat/MessageList.svelte
<script lang="ts">
  import { onMount, afterUpdate } from 'svelte'
  import { isSameDay, format } from 'date-fns'
  import { chatStore } from '../../stores/chat'
  import type { ChatMessage } from './types'
  import MessageItem from './MessageItem.svelte'

  export let messages: ChatMessage[] = []
  export let channelId: string | null = null
  export let currentUserId: string | undefined = undefined

  let container: HTMLElement
  let isNearBottom = true
  let showNewMessagesButton = false
  let highlightedMessageId: string | null = null
  let highlightTimeout: ReturnType<typeof setTimeout>
  let isLoadingMore = false

  $: activeChannelId = channelId ?? $chatStore.currentChannelId
  $: renderedMessages = activeChannelId ? ($chatStore.messagesByChannel[activeChannelId] ?? []) : messages
  $: pagination = activeChannelId
    ? ($chatStore.pagination?.[activeChannelId] ?? { hasMore: true, oldestMessageId: null, isLoading: false })
    : { hasMore: false, oldestMessageId: null, isLoading: false }

  type TimelineItem =
    | { type: 'date'; date: Date }
    | { type: 'message'; message: ChatMessage }

  function getTimeline(msgs: ChatMessage[]): TimelineItem[] {
    const result: TimelineItem[] = []
    let lastDate: Date | null = null
    for (const message of msgs) {
      const date = new Date(message.createdAt ?? message.created_at ?? 0)
      if (!lastDate || !isSameDay(date, lastDate)) {
        result.push({ type: 'date', date })
        lastDate = date
      }
      result.push({ type: 'message', message })
    }
    return result
  }

  $: timeline = getTimeline(renderedMessages)

  function scrollToBottom(behavior: ScrollBehavior = 'auto') {
    if (container) {
      container.scrollTo({ top: container.scrollHeight, behavior })
    }
  }

  export function scrollToMessage(messageId: string) {
    if (!container) return
    const el = container.querySelector(`[data-message-id="${messageId}"]`)
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' })
      highlightedMessageId = messageId
      clearTimeout(highlightTimeout)
      highlightTimeout = setTimeout(() => {
        highlightedMessageId = null
      }, 2000)
    }
  }

  async function handleScroll() {
    if (!container) return
    const threshold = 50
    isNearBottom = container.scrollHeight - container.scrollTop - container.clientHeight < threshold
    if (isNearBottom) showNewMessagesButton = false

    if (!activeChannelId) return

    // Infinite scroll: load older messages when near top
    if (container.scrollTop < 100 && pagination.hasMore && !pagination.isLoading && !isLoadingMore) {
      isLoadingMore = true
      const oldScrollHeight = container.scrollHeight
      await chatStore.fetchMessages(activeChannelId, {
        before: pagination.oldestMessageId ?? undefined,
        limit: 50,
      })
      requestAnimationFrame(() => {
        if (container) {
          const newScrollHeight = container.scrollHeight
          container.scrollTop = newScrollHeight - oldScrollHeight
        }
        isLoadingMore = false
      })
    }
  }

  $: if (renderedMessages.length > 0 && !isNearBottom) {
    showNewMessagesButton = true
  }

  onMount(() => {
    scrollToBottom()
  })

  afterUpdate(() => {
    if (isNearBottom) {
      scrollToBottom('smooth')
    }
  })
</script>

<section
  bind:this={container}
  on:scroll={handleScroll}
  class="flex-1 overflow-y-auto bg-bg-app p-4 custom-scrollbar"
  aria-label="Message list"
>
  <div class="max-w-[var(--msg-max-width)] mx-auto">
    {#if pagination.isLoading && renderedMessages.length === 0}
      <div class="flex justify-center py-4">
        <div class="w-6 h-6 border-2 border-brand border-t-transparent rounded-full animate-spin" />
      </div>
    {:else if renderedMessages.length === 0}
      <div class="rounded-r-2 border border-dashed border-border-2 bg-bg-surface-1 p-6 text-center text-sm text-text-3">
        No messages yet. Start the conversation below.
      </div>
    {:else}
      <div class="space-y-1">
        {#if pagination.isLoading || isLoadingMore}
          <div class="flex justify-center py-2">
            <div class="w-5 h-5 border-2 border-brand border-t-transparent rounded-full animate-spin" />
          </div>
        {/if}
        {#each timeline as item (item.type === 'date' ? `date-${item.date.toISOString()}` : item.message.id)}
          {#if item.type === 'date'}
            <div class="sticky top-2 z-[5] flex justify-center my-3">
              <span class="px-3 py-1 text-xs font-medium text-text-3 bg-bg-surface-1 border border-border-1 rounded-full shadow-1">
                {format(item.date, 'MMMM d, yyyy')}
              </span>
            </div>
          {:else}
            <MessageItem
              message={item.message}
              {currentUserId}
              isHighlighted={highlightedMessageId === item.message.id}
              on:reply
              on:edit
              on:delete
              on:openProfile
              on:thread
            />
          {/if}
        {/each}
      </div>
    {/if}
  </div>
</section>

{#if showNewMessagesButton}
  <button
    class="fixed bottom-20 left-1/2 -translate-x-1/2 px-4 py-2 bg-brand text-brand-foreground text-sm font-medium rounded-full shadow-2 hover:bg-brand-hover transition-standard z-20"
    on:click={() => { scrollToBottom('smooth'); showNewMessagesButton = false }}
  >
    New messages ↓
  </button>
{/if}

// frontend/src/components/channel/MessageList.vue
<script setup lang="ts">
import { ref, watch, computed, nextTick } from 'vue'
import { ArrowDown } from 'lucide-vue-next'
import { useMessageStore } from '../../stores/messages'
import MessageItem from './MessageItem.vue'

const props = defineProps<{
  channelId: string
}>()

const emit = defineEmits<{
  (e: 'reply', messageId: string): void
  (e: 'delete', messageId: string): void
  (e: 'edit', messageId: string): void
}>()

const messageStore = useMessageStore()
const containerRef = ref<HTMLElement | null>(null)
const shouldAutoScroll = ref(true)
const showNewMessagesBtn = ref(false)

const messages = computed(() => messageStore.messagesByChannel[props.channelId] || [])

// Handle scroll events to detect if user is at bottom or top (infinite scroll)
async function handleScroll() {
  if (!containerRef.value || messageStore.loading) return
  
  const { scrollTop, scrollHeight, clientHeight } = containerRef.value
  const distanceToBottom = scrollHeight - scrollTop - clientHeight
  
  // 1. Auto-scroll logic
  const atBottom = distanceToBottom < 50
  shouldAutoScroll.value = atBottom
  
  if (atBottom) {
    showNewMessagesBtn.value = false
  }

  // 2. Reverse infinite scroll (load older)
  if (scrollTop < 100 && messageStore.hasMoreOlder(props.channelId)) {
    const oldScrollHeight = scrollHeight
    await messageStore.fetchOlderMessages(props.channelId)
    
    // Preserve scroll position after prepending messages
    nextTick(() => {
      if (containerRef.value) {
        const newScrollHeight = containerRef.value.scrollHeight
        containerRef.value.scrollTop = newScrollHeight - oldScrollHeight
      }
    })
  }
}

// Scroll to bottom
function scrollToBottom(behavior: ScrollBehavior = 'auto') {
  if (!containerRef.value) return
  containerRef.value.scrollTo({
    top: containerRef.value.scrollHeight,
    behavior
  })
}

// Watch for NEW messages (not full fetch)
watch(() => messages.value.length, (newLen, oldLen) => {
  if (newLen > oldLen) {
    if (shouldAutoScroll.value) {
      nextTick(() => scrollToBottom('smooth'))
    } else {
      showNewMessagesBtn.value = true
    }
  }
})

// Watch for channel change to refetch and reset scroll
watch(() => props.channelId, async (newId) => {
    if (newId) {
        showNewMessagesBtn.value = false
        shouldAutoScroll.value = true
        await messageStore.fetchMessages(newId)
        nextTick(() => scrollToBottom())
    }
}, { immediate: true })

const highlightedMessageId = ref<string | null>(null)

function scrollToMessage(messageId: string) {
  const element = containerRef.value?.querySelector(`[data-message-id="${messageId}"]`)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth', block: 'center' })
    highlightedMessageId.value = messageId
    setTimeout(() => {
      highlightedMessageId.value = null
    }, 2000)
    shouldAutoScroll.value = false
  }
}

defineExpose({ scrollToMessage })

function handleReply(id: string) {
  emit('reply', id)
}

function handleDelete(id: string) {
  emit('delete', id)
}

function handleEdit(id: string) {
  emit('edit', id)
}
</script>

<template>
  <div 
    class="flex-1 overflow-y-auto px-4 py-4 space-y-6 custom-scrollbar relative" 
    ref="containerRef"
    @scroll="handleScroll"
  >
    <!-- New Messages Floating Button -->
    <transition
      enter-active-class="transition ease-out duration-200"
      enter-from-class="transform translate-y-4 opacity-0"
      enter-to-class="transform translate-y-0 opacity-100"
      leave-active-class="transition ease-in duration-150"
      leave-from-class="transform translate-y-0 opacity-100"
      leave-to-class="transform translate-y-4 opacity-0"
    >
      <div 
        v-if="showNewMessagesBtn"
        @click="scrollToBottom('smooth')"
        class="absolute bottom-6 left-1/2 -translate-x-1/2 z-10 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-full shadow-lg cursor-pointer flex items-center space-x-2 text-sm font-medium animate-bounce"
      >
        <ArrowDown class="w-4 h-4" />
        <span>New messages</span>
      </div>
    </transition>

    <!-- Loading State -->
    <div v-if="messageStore.loading" class="text-center text-gray-500 py-10">
        <div class="animate-spin w-8 h-8 border-2 border-primary border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading messages...</p>
    </div>

    <!-- Empty State -->
    <div v-else-if="messages.length === 0" class="text-center text-gray-500 py-10">
        <p>This is the start of the channel.</p>
        <p class="text-sm mt-2">Send a message to start the conversation.</p>
    </div>

    <!-- Message List -->
    <div v-else class="space-y-[1px]">
        <MessageItem 
            v-for="msg in messages" 
            :key="msg.id" 
            :message="msg"
            :data-message-id="msg.id"
            :class="{ 'bg-yellow-100/50 dark:bg-yellow-500/10 ring-1 ring-yellow-400/50': highlightedMessageId === msg.id }"
            class="transition-all duration-500 rounded-sm"
            @reply="handleReply"
            @delete="handleDelete"
            @edit="handleEdit"
        />
    </div>
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 6px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #CBD5E1;
  border-radius: 6px;
}
.dark .custom-scrollbar::-webkit-scrollbar-thumb {
  background: #374151;
}
</style>
