// frontend/src/svelte/components/chat/PinnedMessagesPanel.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { Pin, X, ExternalLink } from 'lucide-svelte'
  import { format } from 'date-fns'
  import { svelteApi } from '../../stores/http'

  interface PanelMessage {
    id: string
    channelId: string
    username: string
    timestamp: string
    content: string
    files?: { length: number }[] | null
  }

  let { channelId, open }: { channelId: string; open: boolean } = $props()

  const dispatch = createEventDispatcher<{ close: void; jump: string }>()

  let pinnedMessages = $state<PanelMessage[]>([])
  let loading = $state(false)

  async function loadPinnedMessages() {
    loading = true
    try {
      const { data } = await svelteApi.get<{ messages: unknown[] }>(`/channels/${channelId}/posts?is_pinned=true`)
      pinnedMessages = data.messages.map((m) => {
        const msg = m as Record<string, unknown>
        return {
          id: String(msg.id ?? ''),
          channelId: String(msg.channel_id ?? msg.channelId ?? ''),
          username: String(msg.username ?? ''),
          timestamp: String(msg.created_at ?? msg.timestamp ?? new Date().toISOString()),
          content: String(msg.message ?? msg.content ?? ''),
          files: Array.isArray(msg.files) ? (msg.files as { length: number }[]) : null,
        }
      })
    } catch (e) {
      console.error('Failed to fetch pinned messages', e)
    } finally {
      loading = false
    }
  }

  $effect(() => {
    if (open && channelId) {
      void loadPinnedMessages()
    }
  })

  async function handleUnpin(message: PanelMessage) {
    try {
      await svelteApi.delete(`/posts/${message.id}/pin`)
      pinnedMessages = pinnedMessages.filter((m) => m.id !== message.id)
    } catch (e) {
      console.error('Failed to unpin message', e)
    }
  }

  function jumpToMessage(message: PanelMessage) {
    dispatch('jump', message.id)
  }
</script>

{#if open}
  <aside class="h-full bg-white flex flex-col" data-testid="pinned-messages-panel">
    <!-- Header -->
    <div class="h-12 border-b border-gray-200 flex items-center justify-between px-4">
      <div class="flex items-center space-x-2">
        <Pin class="w-5 h-5 text-gray-500 fill-current" />
        <span class="font-semibold text-gray-900">Pinned Items</span>
      </div>
      <button
        class="p-1 hover:bg-gray-100 rounded transition-colors"
        aria-label="Close pinned messages"
        onclick={() => dispatch('close')}
      >
        <X class="w-5 h-5 text-gray-400" />
      </button>
    </div>

    <!-- Pinned List -->
    <div class="flex-1 overflow-y-auto p-0">
      {#if loading}
        <div class="text-center py-8 text-gray-500">
          <div class="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full mx-auto mb-2"></div>
          Loading pinned items...
        </div>
      {:else if pinnedMessages.length === 0}
        <div class="text-center py-8 text-gray-500 px-4">
          <div class="mb-2 text-gray-400">
            <Pin class="w-12 h-12 mx-auto mb-3 opacity-20" />
            No pinned items yet
          </div>
          <div class="text-xs">Pin important messages to find them easily here</div>
        </div>
      {:else}
        <div class="divide-y divide-gray-100">
          {#each pinnedMessages as message (message.id)}
            <div class="px-4 py-4 hover:bg-gray-50 transition-colors group relative">
              <div class="flex items-start justify-between mb-1">
                <div class="flex items-center space-x-2">
                  <span class="font-bold text-sm text-gray-900">{message.username}</span>
                  <span class="text-[10px] text-gray-400">{format(new Date(message.timestamp), 'MMM d, h:mm a')}</span>
                </div>
                <!-- Actions -->
                <div class="flex items-center space-x-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button
                    class="p-1 hover:bg-gray-200 rounded text-gray-400 hover:text-red-500 transition-colors"
                    title="Unpin"
                    onclick={() => handleUnpin(message)}
                  >
                    <Pin class="w-3.5 h-3.5 rotate-45" />
                  </button>
                  <button
                    class="p-1 hover:bg-gray-200 rounded text-gray-400 hover:text-blue-500 transition-colors"
                    title="Jump to message"
                    onclick={() => jumpToMessage(message)}
                  >
                    <ExternalLink class="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
              <div class="text-sm text-gray-700 line-clamp-4 mt-1">
                {message.content}
              </div>
              {#if message.files && message.files.length > 0}
                <div class="mt-2 text-[10px] text-blue-500 flex items-center">
                  <span class="mr-1">{message.files.length} attachment{message.files.length > 1 ? 's' : ''}</span>
                </div>
              {/if}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </aside>
{/if}

// frontend/src/components/channel/PinnedMessagesPanel.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { X, Pin, ExternalLink } from 'lucide-vue-next'
import { format } from 'date-fns'
import type { Message } from '@/features/messages/stores/messageStore'
import { useMessageStore } from '@/features/messages/stores/messageStore'
import { useChannelStore } from '@/features/channels/stores/channelStore'

const props = defineProps<{
    show: boolean
}>()

const emit = defineEmits<{
    (e: 'close'): void
    (e: 'jump', messageId: string): void
}>()

const messageStore = useMessageStore()
const channelStore = useChannelStore()

const pinnedMessages = ref<Message[]>([])
const loading = ref(false)

async function loadPinnedMessages() {
    if (!channelStore.currentChannelId) return
    loading.value = true
    try {
        pinnedMessages.value = await messageStore.fetchPinnedMessages(channelStore.currentChannelId)
    } catch (e) {
        console.error('Failed to fetch pinned messages', e)
    } finally {
        loading.value = false
    }
}

watch(() => props.show, (isOpen) => {
    if (isOpen) {
        loadPinnedMessages()
    }
})

// Also reload if channel changes while open
watch(() => channelStore.currentChannelId, (newId) => {
    if (props.show && newId) {
        loadPinnedMessages()
    }
})

async function handleUnpin(message: Message) {
    try {
        await messageStore.unpinMessage(message.id, message.channelId)
        pinnedMessages.value = pinnedMessages.value.filter(m => m.id !== message.id)
    } catch (e) {
        console.error('Failed to unpin message', e)
    }
}

function jumpToMessage(message: Message) {
    emit('jump', message.id)
}
</script>

<template>
  <aside 
    v-if="show"
    class="h-full bg-white flex flex-col"
  >
    <!-- Header -->
    <div class="h-12 border-b border-gray-200 flex items-center justify-between px-4">
      <div class="flex items-center space-x-2">
        <Pin class="w-5 h-5 text-gray-500 fill-current" />
        <span class="font-semibold text-gray-900">Pinned Items</span>
      </div>
      <button 
        @click="$emit('close')"
        class="p-1 hover:bg-gray-100 rounded transition-colors"
      >
        <X class="w-5 h-5 text-gray-400" />
      </button>
    </div>

    <!-- Pinned List -->
    <div class="flex-1 overflow-y-auto p-0">
      <div v-if="loading" class="text-center py-8 text-gray-500">
        <div class="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full mx-auto mb-2"></div>
        Loading pinned items...
      </div>
      
      <div v-else-if="pinnedMessages.length === 0" class="text-center py-8 text-gray-500 px-4">
        <div class="mb-2 text-gray-400">
            <Pin class="w-12 h-12 mx-auto mb-3 opacity-20" />
            No pinned items yet
        </div>
        <div class="text-xs">Pin important messages to find them easily here</div>
      </div>

      <div v-else class="divide-y divide-gray-100">
        <div 
            v-for="message in pinnedMessages" 
            :key="message.id"
            class="px-4 py-4 hover:bg-gray-50 transition-colors group relative"
        >
            <div class="flex items-start justify-between mb-1">
                <div class="flex items-center space-x-2">
                    <span class="font-bold text-sm text-gray-900">{{ message.username }}</span>
                    <span class="text-[10px] text-gray-400">{{ format(new Date(message.timestamp), 'MMM d, h:mm a') }}</span>
                </div>
                <!-- Actions -->
                <div class="flex items-center space-x-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button 
                        @click="handleUnpin(message)"
                        class="p-1 hover:bg-gray-200 rounded text-gray-400 hover:text-red-500 transition-colors"
                        title="Unpin"
                    >
                        <Pin class="w-3.5 h-3.5 rotate-45" />
                    </button>
                    <button 
                        @click="jumpToMessage(message)"
                        class="p-1 hover:bg-gray-200 rounded text-gray-400 hover:text-blue-500 transition-colors"
                        title="Jump to message"
                    >
                        <ExternalLink class="w-3.5 h-3.5" />
                    </button>
                </div>
            </div>
            <div class="text-sm text-gray-700 line-clamp-4 mt-1">
                {{ message.content }}
            </div>
            <div v-if="message.files && message.files.length > 0" class="mt-2 text-[10px] text-blue-500 flex items-center">
                <span class="mr-1">{{ message.files.length }} attachment{{ message.files.length > 1 ? 's' : '' }}</span>
            </div>
        </div>
      </div>
    </div>
  </aside>
</template>
