// frontend/src/components/channel/ThreadPanel.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { Send, MessageSquare } from 'lucide-vue-next'
import { format } from 'date-fns'
import { useMessageStore } from '@/features/messages/stores/messageStore'
import { useUIStore } from '../../features/ui/stores/uiStore'
import { useAuthStore } from '../../features/auth/stores/authStore'
import { useTeamStore } from '@/features/teams/stores/teamStore'
import { useWebSocket } from '../../composables/useWebSocket'
import RcAvatar from '../ui/RcAvatar.vue'
import FilePreview from '../atomic/FilePreview.vue'
import ImageGallery from '../atomic/ImageGallery.vue'
import type { FileUploadResponse } from '../../api/files'
import { threadsApi } from '../../api/threads'
import { useMarkdownRenderer } from '../../composables/useMarkdownRenderer'

const messageStore = useMessageStore()
const uiStore = useUIStore()
const authStore = useAuthStore()
const teamStore = useTeamStore()

const { sendMessage } = useWebSocket()
const { renderMarkdown } = useMarkdownRenderer()

const replyContent = ref('')
const loading = ref(false)

// Gallery state
const showGallery = ref(false)
const galleryInitialIndex = ref(0)
const galleryCurrentImages = ref<FileUploadResponse[]>([])

function openGallery(file: FileUploadResponse, allFiles: FileUploadResponse[]) {
  const images = allFiles.filter(f => f.mime_type.startsWith('image/'))
  const index = images.findIndex(f => f.id === file.id)
  if (index !== -1) {
    galleryCurrentImages.value = images
    galleryInitialIndex.value = index
    showGallery.value = true
  }
}

const parentMessage = computed(() => {
    if (!uiStore.rhsContextId) return null
    for (const channelId in messageStore.messagesByChannel) {
        const messages = messageStore.messagesByChannel[channelId]
        if (!messages) continue;
        const msg = messages.find(m => m.id === uiStore.rhsContextId)
        if (msg) return msg
    }
    return null
})

const replies = computed(() => {
    if (!uiStore.rhsContextId) return []
    return messageStore.repliesByThread[uiStore.rhsContextId] || []
})

watch(() => uiStore.rhsContextId, async (newId) => {
    if (newId && uiStore.rhsView === 'thread') {
        loading.value = true
        try {
            await messageStore.fetchThread(newId)
            // Mark thread as read when opened
            if (teamStore.currentTeamId) {
                try {
                    await threadsApi.markAsRead(newId, teamStore.currentTeamId)
                } catch (e) {
                    console.error('Failed to mark thread as read:', e)
                }
            }
        } catch (e) {
            console.error('Failed to fetch thread:', e)
        } finally {
            loading.value = false
        }
    }
}, { immediate: true })

async function sendReply() {
    if (!replyContent.value.trim() || !parentMessage.value) return
    
    const rootId = parentMessage.value.id
    const content = replyContent.value
    replyContent.value = ''

    try {
        await sendMessage(parentMessage.value.channelId, content, rootId)
    } catch (e) {
        console.error('Failed to send reply:', e)
        replyContent.value = content
    }
}

function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        sendReply()
    }
}
</script>

<template>
  <div 
    v-if="parentMessage"
    class="flex-1 flex flex-col min-h-0 bg-surface"
  >
    <!-- Thread Header (Simplified since RightSidebar provides the main header) -->
    <!-- Parent Message -->
    <div class="p-5 border-b border-border-dim bg-surface-dim/30">
      <div class="flex items-start space-x-3">
        <RcAvatar 
          :userId="parentMessage.userId" 
          :username="parentMessage.username" 
          :src="parentMessage.avatarUrl" 
          size="md"
          class="w-10 h-10 rounded-lg shrink-0 mt-0.5"
        />
        <div class="flex-1 min-w-0">
          <div class="flex items-baseline space-x-2 mb-1">
            <span class="font-bold text-[15px] text-gray-900 leading-tight">{{ parentMessage.username }}</span>
            <span class="text-[11px] text-gray-500 font-medium">{{ format(new Date(parentMessage.timestamp), 'MMM d, h:mm a') }}</span>
          </div>
          <div 
            class="text-[15px] text-gray-800 leading-relaxed markdown-content"
            v-html="renderMarkdown(parentMessage.content, authStore.user?.username || undefined)"
          ></div>

          <!-- Parent Files -->
          <div v-if="parentMessage.files && parentMessage.files.length > 0" class="mt-4 flex flex-wrap gap-2">
            <template v-for="file in parentMessage.files" :key="file.id">
              <FilePreview :file="file" @preview="(f) => openGallery(f, parentMessage!.files || [])" />
            </template>
          </div>
        </div>
      </div>
    </div>

    <!-- Replies Count -->
    <div v-if="replies.length > 0" class="px-5 py-3 border-b border-border-dim text-[11px] font-bold text-gray-500 uppercase tracking-widest bg-surface/50">
      {{ replies.length }} {{ replies.length === 1 ? 'reply' : 'replies' }}
    </div>

    <!-- Replies List -->
    <div class="flex-1 overflow-y-auto p-5 space-y-6 custom-scrollbar">
      <div v-if="loading" class="text-center py-10 text-gray-500">
        <div class="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full mx-auto mb-3"></div>
        <p class="text-xs font-medium uppercase tracking-wider">Loading replies...</p>
      </div>
      
      <div v-else-if="replies.length === 0" class="text-center py-12">
          <div class="w-16 h-16 bg-surface-dim rounded-full flex items-center justify-center mx-auto mb-4 border border-border-dim">
             <MessageSquare class="w-8 h-8 text-gray-400" />
          </div>
          <p class="text-[15px] font-semibold text-gray-700">No replies yet.</p>
          <p class="text-xs text-gray-500 mt-1">Be the first to share your thoughts!</p>
      </div>

      <div 
        v-else
        v-for="reply in replies"
        :key="reply.id"
        class="flex items-start space-x-3 group relative transition-all"
      >
        <RcAvatar 
          :userId="reply.userId" 
          :username="reply.username" 
          :src="reply.avatarUrl" 
          size="sm"
          class="w-8 h-8 rounded-md shrink-0 mt-0.5"
        />
        <div class="flex-1 min-w-0">
          <div class="flex items-baseline space-x-2 mb-0.5">
            <span class="font-bold text-sm text-gray-900 leading-tight">{{ reply.username }}</span>
            <span class="text-[10px] text-gray-500 font-medium">{{ format(new Date(reply.timestamp), 'h:mm a') }}</span>
          </div>
          <div 
            class="text-[14px] text-gray-700 leading-normal markdown-content"
            v-html="renderMarkdown(reply.content, authStore.user?.username || undefined)"
          ></div>

          <!-- Reply Files -->
          <div v-if="reply.files && reply.files.length > 0" class="mt-3 flex flex-wrap gap-2">
            <template v-for="file in reply.files" :key="file.id">
              <FilePreview :file="file" @preview="(f) => openGallery(f, reply.files || [])" />
            </template>
          </div>
        </div>
      </div>
    </div>

    <!-- Reply Composer -->
    <div class="p-4 border-t border-border-dim bg-surface-dim/30">
      <div class="flex items-end space-x-2 bg-surface border border-border-dim rounded-xl focus-within:ring-2 focus-within:ring-primary/40 focus-within:border-primary/50 transition-all p-1.5 shadow-sm">
        <textarea
          v-model="replyContent"
          @keydown="handleKeydown"
          rows="2"
          class="flex-1 px-3 py-2 bg-transparent text-gray-900 resize-none border-none focus:ring-0 text-[14px] scrollbar-none"
          placeholder="Reply to thread..."
        ></textarea>
        <button
          @click="sendReply"
          :disabled="!replyContent.trim()"
          class="mb-1 mr-1 rounded-lg bg-primary p-2.5 text-brand-foreground shadow-lg shadow-primary/20 transition-all hover:bg-brand-hover active:scale-95 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <Send class="w-4 h-4" />
        </button>
      </div>
    </div>

    <!-- Image Gallery Lightbox -->
    <Teleport to="body">
      <ImageGallery 
        v-if="showGallery" 
        :images="galleryCurrentImages" 
        :initialIndex="galleryInitialIndex" 
        @close="showGallery = false" 
      />
    </Teleport>
  </div>

</template>

// frontend/src/svelte/components/thread/ThreadPanel.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte'
  import { createEventDispatcher } from 'svelte'
  import { format } from 'date-fns'
  import { X, MessageSquare, Send, Loader2 } from 'lucide-svelte'
  import { chatStore } from '../../stores/chat'
  import ThreadMessageItem from './ThreadMessageItem.svelte'

  export let threadId: string | null = null
  export let channelId: string | null = null
  export let open = false

  const dispatch = createEventDispatcher<{ close: void }>()

  let composerRef: HTMLTextAreaElement | null = null
  let draft = ''
  let isSending = false
  let listRef: HTMLDivElement | null = null
  let isScrolledToBottom = true

  $: state = $chatStore
  $: parentMessage =
    channelId && threadId
      ? (state.messagesByChannel[channelId]?.find((m) => m.id === threadId) ?? null)
      : null
  $: replies = threadId ? (state.threadsByParent[threadId] ?? []) : []
  $: replyCount = replies.length

  // Fetch replies when threadId changes and panel is open
  $: if (open && threadId) {
    chatStore.fetchThreadReplies(threadId).catch((err: unknown) => {
      console.error('Failed to load thread:', err)
    })
  }

  // Focus composer when thread opens
  $: if (open && composerRef) {
    setTimeout(() => composerRef?.focus(), 100)
  }

  // Scroll to bottom when replies change (if already at bottom)
  $: if (replies.length > 0 && isScrolledToBottom && listRef) {
    tick().then(() => {
      if (listRef) {
        listRef.scrollTo({ top: listRef.scrollHeight, behavior: 'smooth' })
      }
    })
  }

  function handleClose() {
    draft = ''
    dispatch('close')
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
      e.preventDefault()
      handleClose()
      return
    }
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendReply()
    }
  }

  async function sendReply() {
    const trimmed = draft.trim()
    if (!trimmed || !threadId || !channelId || isSending) return
    isSending = true
    try {
      await chatStore.sendThreadReply(threadId, channelId, trimmed)
      draft = ''
      tick().then(() => {
        if (listRef) {
          listRef.scrollTo({ top: listRef.scrollHeight, behavior: 'smooth' })
        }
      })
    } catch (error) {
      console.error('Failed to send reply:', error)
    } finally {
      isSending = false
    }
  }

  function handleScroll() {
    if (!listRef) return
    const { scrollTop, scrollHeight, clientHeight } = listRef
    isScrolledToBottom = scrollHeight - scrollTop - clientHeight < 50
  }

  function handleGlobalKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      const activeElement = document.activeElement
      const isInComposer = activeElement === composerRef
      const isInOtherInput =
        activeElement instanceof HTMLInputElement ||
        (activeElement instanceof HTMLTextAreaElement && !isInComposer)

      if (!isInOtherInput || isInComposer) {
        handleClose()
      }
    }
  }

  onMount(() => {
    document.addEventListener('keydown', handleGlobalKeydown)
    return () => {
      document.removeEventListener('keydown', handleGlobalKeydown)
    }
  })

  function getInitials(name: string) {
    return name
      .split(' ')
      .map((n) => n[0])
      .filter(Boolean)
      .join('')
      .toUpperCase()
      .slice(0, 2)
  }

  function formatTime(value: string | undefined) {
    if (!value) return ''
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return ''
    return format(date, 'MMM d, h:mm a')
  }
</script>

{#if open}
  <!-- Overlay for mobile -->
  <div
    class="thread-panel-overlay fixed inset-0 bg-black/40 backdrop-blur-sm z-30 lg:hidden"
    role="button"
    tabindex="-1"
    aria-label="Close thread"
    on:click={(e) => {
      if ((e.target as HTMLElement).classList.contains('thread-panel-overlay')) {
        handleClose()
      }
    }}
    on:keydown={(e) => {
      if (e.key === 'Escape') {
        e.preventDefault()
        handleClose()
      }
    }}
  ></div>

  <div
    data-testid="thread-panel"
    class="fixed lg:relative top-0 right-0 h-full w-full sm:w-[400px] lg:w-[var(--rhs-width)] bg-bg-surface-1 border-l border-border-1 z-40 flex flex-col shadow-2xl"
    role="dialog"
    aria-modal="true"
    aria-label="Thread panel"
    tabindex="-1"
    on:keydown={handleKeydown}
  >
    <!-- Header -->
    <div class="border-b border-border-1 bg-bg-surface-2">
      <div class="h-12 flex items-center justify-between px-4 border-b border-border-1">
        <div class="flex items-center gap-2">
          <MessageSquare class="w-5 h-5 text-text-2" />
          <h3 class="font-bold text-[15px] text-text-1 uppercase tracking-wider">Thread</h3>
          {#if replyCount > 0}
            <span data-testid="thread-reply-count" class="text-sm text-text-3">
              ({replyCount}
              {replyCount === 1 ? 'reply' : 'replies'})
            </span>
          {/if}
        </div>
        <button
          on:click={handleClose}
          class="p-1.5 hover:bg-bg-surface-1 rounded-lg text-text-3 hover:text-text-1 transition-standard focus-ring"
          aria-label="Close thread"
          title="Close thread"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Parent Message -->
      {#if parentMessage}
        <div class="p-5">
          <div class="flex items-start space-x-3">
            <div class="shrink-0 mt-0.5">
              {#if parentMessage.avatar_url}
                <img
                  src={parentMessage.avatar_url}
                  alt={parentMessage.username ?? 'Unknown'}
                  class="w-10 h-10 rounded-lg object-cover"
                />
              {:else}
                <div
                  class="w-10 h-10 rounded-lg bg-brand/10 text-brand flex items-center justify-center text-xs font-bold"
                >
                  {getInitials(parentMessage.username ?? 'Unknown')}
                </div>
              {/if}
            </div>
            <div class="flex-1 min-w-0">
              <div class="flex items-baseline space-x-2 mb-1">
                <span class="font-bold text-[15px] text-text-1 leading-tight">
                  {parentMessage.username ?? 'Unknown User'}
                </span>
                <span class="text-[11px] text-text-3 font-medium">
                  {formatTime(parentMessage.created_at)}
                </span>
              </div>
              <div class="text-[15px] text-text-1 leading-relaxed break-words whitespace-pre-wrap">
                {parentMessage.message ?? ''}
              </div>
            </div>
          </div>
        </div>
      {:else}
        <div class="p-5">
          <div class="flex items-center gap-3 text-text-3">
            <div class="w-10 h-10 rounded-lg bg-bg-surface-1 flex items-center justify-center">
              <MessageSquare class="w-5 h-5" />
            </div>
            <div>
              <p class="text-sm font-medium text-text-2">Message not found</p>
              <p class="text-xs">This message is no longer available</p>
            </div>
          </div>
        </div>
      {/if}
    </div>

    <!-- Replies List -->
    <div
      bind:this={listRef}
      class="flex-1 overflow-y-auto p-5 space-y-5 custom-scrollbar"
      on:scroll={handleScroll}
    >
      {#if replies.length === 0}
        <div class="flex flex-col items-center justify-center py-12 text-center">
          <div class="w-16 h-16 bg-bg-surface-2 rounded-full flex items-center justify-center mb-4">
            <MessageSquare class="w-8 h-8 text-text-3" />
          </div>
          <p class="text-[15px] font-semibold text-text-1 mb-1">No replies yet</p>
          <p class="text-sm text-text-3">Be the first to share your thoughts!</p>
        </div>
      {:else}
        {#each replies as reply (reply.id)}
          <ThreadMessageItem message={reply} />
        {/each}
      {/if}
    </div>

    <!-- Reply Composer -->
    <div class="p-4 border-t border-border-1 bg-bg-surface-2">
      <div
        class="flex items-end space-x-2 bg-bg-surface-1 border border-border-1 rounded-xl focus-within:ring-2 focus-within:ring-brand/40 focus-within:border-brand/50 transition-all p-1.5 shadow-sm"
      >
        <textarea
          bind:this={composerRef}
          bind:value={draft}
          on:keydown={handleKeydown}
          rows={2}
          data-testid="thread-composer"
          class="flex-1 px-3 py-2 bg-transparent text-text-1 resize-none border-none focus:ring-0 text-[14px] scrollbar-none"
          placeholder="Reply to thread..."
          disabled={isSending}
        ></textarea>

        <button
          on:click={sendReply}
          disabled={!draft.trim() || isSending}
          class="mb-1 mr-1 flex items-center justify-center rounded-lg bg-brand p-2.5 text-brand-foreground shadow-lg shadow-brand/20 transition-all hover:bg-brand-hover active:scale-95 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {#if isSending}
            <Loader2 class="w-4 h-4 animate-spin" />
          {:else}
            <Send class="w-4 h-4" />
          {/if}
        </button>
      </div>

      <div class="mt-2 text-[11px] text-text-3 text-right">
        <span>Press </span>
        <kbd class="px-1.5 py-0.5 bg-bg-surface-1 border border-border-1 rounded text-[10px] font-mono">Enter</kbd>
        <span> to send, </span>
        <kbd class="px-1.5 py-0.5 bg-bg-surface-1 border border-border-1 rounded text-[10px] font-mono">Shift+Enter</kbd>
        <span> for new line</span>
      </div>
    </div>
  </div>
{/if}
