// frontend/src/svelte/components/settings/tabs/SidebarTab.svelte
<script lang="ts">
  let groupUnread = 'never'
  let limitDMs = 'all'

  // Silence unused-variable warnings; bind:group reads are not always detected
  $: groupUnread, limitDMs
</script>

<div class="space-y-5">
  <div class="overflow-hidden rounded-r-3 border border-border-1 bg-bg-surface-1 shadow-1">
    <!-- Group Unread Channels -->
    <div class="border-b border-border-1 px-5 py-4">
      <label class="mb-1 block text-sm font-medium text-text-1">Group unread channels separately</label>
      <p class="mb-2 text-xs text-text-3">Group unread channels above read channels in the channel sidebar</p>
      <div class="space-y-2">
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={groupUnread} value="never" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>Off</span>
        </label>
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={groupUnread} value="only_for_favorites" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>For favorites only</span>
        </label>
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={groupUnread} value="always" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>On</span>
        </label>
      </div>
    </div>

    <!-- Limit Visible DMs -->
    <div class="px-5 py-4">
      <label class="mb-1 block text-sm font-medium text-text-1">Number of direct messages to show</label>
      <p class="mb-2 text-xs text-text-3">Limit the number of direct messages shown in the sidebar</p>
      <div class="space-y-2">
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={limitDMs} value="all" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>All direct messages</span>
        </label>
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={limitDMs} value="40" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>40 direct messages</span>
        </label>
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={limitDMs} value="20" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>20 direct messages</span>
        </label>
        <label class="flex items-center gap-3 rounded-r-2 border border-border-1 bg-bg-surface-1 p-3 text-sm text-text-2 transition-standard hover:border-border-2 hover:bg-bg-surface-2 cursor-pointer">
          <input type="radio" bind:group={limitDMs} value="10" class="mt-0.5 h-4 w-4 accent-brand" />
          <span>10 direct messages</span>
        </label>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/settings/sidebar/SidebarTab.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import SettingItemMin from '../SettingItemMin.vue'
import SettingItemMax from '../SettingItemMax.vue'
import { usePreferencesStore } from '../../../features/preferences/stores/preferencesStore'

const preferencesStore = usePreferencesStore()
const expandedRow = ref<string | null>(null)
const saving = ref(false)

// Local preference states for editing
const localGroupUnread = ref<'never' | 'only_for_favorites' | 'always'>('never')
const localLimitDMs = ref<'all' | '10' | '20' | '40'>('all')

// Display labels
const groupUnreadLabel = computed(() => {
  const labels: Record<string, string> = {
    never: 'Off',
    only_for_favorites: 'For favorites only',
    always: 'On'
  }
  return labels[preferencesStore.preferences?.group_unread_channels || 'never'] || 'Off'
})

const limitDMsLabel = computed(() => {
  const limit = preferencesStore.preferences?.limit_visible_dms_gms
  if (limit === 'all' || !limit) return 'All direct messages'
  return `${limit} direct messages`
})

// Initialize local states from preferences on mount
onMounted(() => {
  preferencesStore.fetchPreferences().then(() => {
    syncLocalState()
  })
})

function syncLocalState() {
  const prefs = preferencesStore.preferences
  if (!prefs) return

  localGroupUnread.value = prefs.group_unread_channels || 'never'
  localLimitDMs.value = prefs.limit_visible_dms_gms || 'all'
}

function expandRow(rowId: string) {
  if (expandedRow.value === rowId) {
    return
  }
  syncLocalState()
  expandedRow.value = rowId
}

async function savePreference(updates: Record<string, unknown>) {
  saving.value = true
  try {
    await preferencesStore.updatePreferences(updates)
    expandedRow.value = null
  } finally {
    saving.value = false
  }
}

function cancelEdit() {
  syncLocalState()
  expandedRow.value = null
}
</script>

<template>
  <div class="space-y-1">
    <!-- 1. Group unread channels separately -->
    <div v-if="expandedRow !== 'group_unread'">
      <SettingItemMin
        label="Group unread channels separately"
        :value="groupUnreadLabel"
        description="Group unread channels above read channels in the channel sidebar"
        @click="expandRow('group_unread')"
      />
    </div>
    
    <SettingItemMax
      v-else
      label="Group unread channels separately"
      description="Control how unread channels are grouped in the sidebar"
      :loading="saving"
      @save="savePreference({ group_unread_channels: localGroupUnread })"
      @cancel="cancelEdit"
    >
      <div class="space-y-3">
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localGroupUnread"
            value="never"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">Off</div>
            <div class="text-xs text-text-3">Show channels in their normal order</div>
          </div>
        </label>
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localGroupUnread"
            value="only_for_favorites"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">For favorites only</div>
            <div class="text-xs text-text-3">Only group unread channels in Favorites</div>
          </div>
        </label>
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localGroupUnread"
            value="always"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">On</div>
            <div class="text-xs text-text-3">Group all unread channels at the top</div>
          </div>
        </label>
      </div>
    </SettingItemMax>

    <!-- 2. Number of direct messages to show -->
    <div v-if="expandedRow !== 'limit_dms'">
      <SettingItemMin
        label="Number of direct messages to show"
        :value="limitDMsLabel"
        description="Limit the number of direct messages shown in the sidebar"
        @click="expandRow('limit_dms')"
      />
    </div>
    
    <SettingItemMax
      v-else
      label="Number of direct messages to show"
      description="Control how many direct message conversations appear in the sidebar"
      :loading="saving"
      @save="savePreference({ limit_visible_dms_gms: localLimitDMs })"
      @cancel="cancelEdit"
    >
      <div class="space-y-3">
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localLimitDMs"
            value="all"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">All direct messages</div>
            <div class="text-xs text-text-3">Show all your direct messages</div>
          </div>
        </label>
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localLimitDMs"
            value="40"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">40 direct messages</div>
            <div class="text-xs text-text-3">Show the 40 most recent conversations</div>
          </div>
        </label>
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localLimitDMs"
            value="20"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">20 direct messages</div>
            <div class="text-xs text-text-3">Show the 20 most recent conversations</div>
          </div>
        </label>
        <label class="flex items-center gap-3 p-3 border border-border-1 rounded-lg cursor-pointer hover:bg-bg-surface-2">
          <input
            type="radio"
            v-model="localLimitDMs"
            value="10"
            class="w-4 h-4 text-primary"
          />
          <div class="flex-1">
            <div class="text-sm font-medium text-text-1">10 direct messages</div>
            <div class="text-xs text-text-3">Show the 10 most recent conversations</div>
          </div>
        </label>
      </div>
    </SettingItemMax>
  </div>
</template>
