// frontend/src/components/modals/AddChannelMembersModal.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { X, Search, User, UserPlus } from 'lucide-vue-next';
import { useTeamStore } from '@/features/teams/stores/teamStore';
import { useAuthStore } from '../../features/auth/stores/authStore';
import BaseButton from '../atomic/BaseButton.vue';
import { channelRepository } from '../../features/channels/repositories/channelRepository';
import { getApiErrorMessage } from '@/core/errors/errorUtils';

const props = defineProps<{
    show: boolean
    channelId?: string
    channelName?: string
}>()

const emit = defineEmits<{
    (e: 'close'): void
    (e: 'members-added', count: number): void
}>()

const teamStore = useTeamStore()
const authStore = useAuthStore()

const search = ref('')
const addingMembers = ref<Set<string>>(new Set())
const error = ref('')
const success = ref('')

// Get current channel members to exclude
const currentMembers = ref<Set<string>>(new Set())

watch(() => props.show, async (isShown) => {
    if (isShown) {
        search.value = ''
        error.value = ''
        success.value = ''
        if (teamStore.currentTeamId) {
            await teamStore.fetchMembers(teamStore.currentTeamId)
        }
        // Fetch current channel members
        if (props.channelId) {
            try {
                const members = await channelRepository.getMembers(props.channelId)
                currentMembers.value = new Set(members.map(m => m.userId))
            } catch (e) {
                console.error('Failed to fetch channel members:', e)
            }
        }
    }
})

const filteredMembers = computed(() => {
    if (!teamStore.members) return []
    
    return teamStore.members.filter((m: any) => {
        // Don't show current user or existing members
        if (m.user_id === authStore.user?.id) return false
        if (currentMembers.value.has(m.user_id)) return false
        
        const searchLower = search.value.toLowerCase()
        return (
            m.username.toLowerCase().includes(searchLower) ||
            (m.display_name && m.display_name.toLowerCase().includes(searchLower))
        )
    })
})

async function addMember(member: any) {
    if (!props.channelId || addingMembers.value.has(member.user_id)) return

    addingMembers.value.add(member.user_id)
    error.value = ''
    success.value = ''

    try {
        await channelRepository.addMember(props.channelId, member.user_id)
        currentMembers.value.add(member.user_id)
        success.value = `Added ${member.display_name || member.username}`
        
        // Clear success message after 2 seconds
        setTimeout(() => {
            success.value = ''
        }, 2000)
    } catch (e: unknown) {
        error.value = getApiErrorMessage(e) || `Failed to add ${member.username}`
    } finally {
        addingMembers.value.delete(member.user_id)
    }
}

function handleClose() {
    const addedCount = success.value ? 1 : 0
    search.value = ''
    error.value = ''
    success.value = ''
    emit('close')
    if (addedCount > 0) {
        emit('members-added', addedCount)
    }
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center">
      <!-- Backdrop -->
      <div class="absolute inset-0 bg-black/50 backdrop-blur-sm" @click="handleClose"></div>
      
      <!-- Modal -->
      <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 overflow-hidden flex flex-col max-h-[80vh]">
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div>
            <h2 class="text-xl font-bold text-gray-900">Add Members</h2>
            <p v-if="channelName" class="text-sm text-gray-500 mt-0.5">To #{{ channelName }}</p>
          </div>
          <button @click="handleClose" class="p-1 hover:bg-gray-100 rounded-lg transition-colors">
            <X class="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <!-- Search -->
        <div class="px-6 py-4 border-b border-gray-100">
          <div class="relative">
            <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input 
              v-model="search"
              type="text"
              placeholder="Search for team members..."
              class="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-900 focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all"
              autofocus
            />
          </div>
        </div>

        <!-- Content -->
        <div class="flex-1 overflow-y-auto p-2 custom-scrollbar min-h-[200px]">
          <!-- Error -->
          <div v-if="error" class="m-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
            {{ error }}
          </div>

          <!-- Success -->
          <div v-if="success" class="m-4 p-3 bg-green-50 border border-green-200 rounded-lg text-green-600 text-sm">
            {{ success }}
          </div>

          <!-- Loading -->
          <div v-if="teamStore.loading && teamStore.members.length === 0" class="flex flex-col items-center justify-center py-12 text-gray-500">
            <div class="w-8 h-8 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin mb-4"></div>
            <p class="text-sm">Loading members...</p>
          </div>

          <!-- Members List -->
          <div v-else-if="filteredMembers.length > 0" class="space-y-1">
            <button
              v-for="member in filteredMembers"
              :key="member.user_id"
              @click="addMember(member)"
              :disabled="addingMembers.has(member.user_id)"
              class="w-full flex items-center justify-between px-4 py-3 rounded-lg hover:bg-indigo-50 transition-colors group text-left"
            >
              <div class="flex items-center">
                <!-- Avatar -->
                <div class="relative mr-4">
                  <img 
                    v-if="member.avatar_url"
                    :src="member.avatar_url"
                    class="w-10 h-10 rounded-full object-cover ring-2 ring-white shadow-sm"
                  />
                  <div v-else class="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center ring-2 ring-white shadow-sm">
                    <User class="w-6 h-6 text-indigo-500" />
                  </div>
                </div>

                <!-- Name -->
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-semibold text-gray-900 truncate">
                    {{ member.display_name || member.username }}
                  </p>
                  <p class="text-xs text-gray-500 truncate">
                    @{{ member.username }}
                  </p>
                </div>
              </div>

              <!-- Add button -->
              <div v-if="addingMembers.has(member.user_id)" class="w-8 h-8 flex items-center justify-center">
                <div class="w-5 h-5 border-2 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin"></div>
              </div>
              <div v-else class="w-8 h-8 flex items-center justify-center rounded-full bg-indigo-100 text-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity">
                <UserPlus class="w-4 h-4" />
              </div>
            </button>
          </div>

          <!-- Empty State -->
          <div v-else class="flex flex-col items-center justify-center py-12 text-gray-500 px-6 text-center">
            <div class="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center mb-4">
              <UserPlus class="w-6 h-6 text-gray-400" />
            </div>
            <p class="text-sm font-medium">No members to add</p>
            <p class="text-xs mt-1">All team members are already in this channel</p>
          </div>
        </div>

        <!-- Footer -->
        <div class="px-6 py-4 border-t border-gray-200 bg-gray-50 flex justify-end">
          <BaseButton variant="secondary" @click="handleClose">
            Done
          </BaseButton>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 4px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 4px;
}
.dark .custom-scrollbar::-webkit-scrollbar-thumb {
  background: #475569;
}
</style>

// frontend/src/svelte/components/modals/AddChannelMembersModal.svelte
<script lang="ts">
  import { X, Search, User, UserPlus } from 'lucide-svelte'
  import { svelteApi, SvelteHttpError } from '../../stores/http'
  import { authStore } from '../../stores/auth'
  import { chatStore } from '../../stores/chat'
  import type { SvelteChatMember } from '../../stores/chat'

  interface Props {
    open?: boolean
    channelId?: string
    channelName?: string
    onclose?: () => void
    onmembersAdded?: (count: number) => void
  }

  let {
    open = false,
    channelId,
    channelName,
    onclose,
    onmembersAdded,
  }: Props = $props()

  let search = $state('')
  let addingMembers = $state<Set<string>>(new Set())
  let error = $state('')
  let success = $state('')
  let addedCount = $state(0)
  let currentMembers = $state<Set<string>>(new Set())
  let channelMembersLoading = $state(false)

  let channelTeamId = $derived((() => {
    if (!channelId) return null
    const channel = $chatStore.channels.find((c) => c.id === channelId)
    return channel?.team_id ?? null
  })())

  let currentTeamId = $derived(
    channelTeamId ??
      (() => {
        const channel = $chatStore.channels.find((c) => c.id === $chatStore.currentChannelId)
        return channel?.team_id ?? $chatStore.teams[0]?.id ?? null
      })()
  )

  $effect(() => {
    if (open) {
      search = ''
      error = ''
      success = ''
      addedCount = 0
      currentMembers = new Set()
      if (currentTeamId) {
        if (!$chatStore.membersByTeam[currentTeamId]?.length) {
          chatStore.fetchMembers(currentTeamId)
        }
      }
      if (channelId) {
        fetchChannelMembers()
      }
    }
  })

  async function fetchChannelMembers() {
    if (!channelId) return
    channelMembersLoading = true
    try {
      const { data } = await svelteApi.get<Array<{ user_id: string }>>(`/channels/${channelId}/members`)
      currentMembers = new Set(data.map((m) => m.user_id))
    } catch (e) {
      console.error('Failed to fetch channel members:', e)
    } finally {
      channelMembersLoading = false
    }
  }

  let members = $derived(currentTeamId ? ($chatStore.membersByTeam[currentTeamId] ?? []) : [])

  let filteredMembers = $derived(((): SvelteChatMember[] => {
    if (!members.length) return []
    const searchLower = search.toLowerCase()
    return members.filter((m) => {
      if (m.user_id === $authStore.user?.id) return false
      if (currentMembers.has(m.user_id)) return false
      return (
        m.username.toLowerCase().includes(searchLower) ||
        (m.display_name && m.display_name.toLowerCase().includes(searchLower))
      )
    })
  })())

  async function addMember(member: SvelteChatMember) {
    if (!channelId || addingMembers.has(member.user_id)) return

    addingMembers.add(member.user_id)
    error = ''
    success = ''

    try {
      await svelteApi.post(`/channels/${channelId}/members`, { user_id: member.user_id })
      currentMembers.add(member.user_id)
      success = `Added ${member.display_name || member.username}`
      addedCount += 1

      setTimeout(() => {
        success = ''
      }, 2000)
    } catch (err: unknown) {
      const message =
        err instanceof SvelteHttpError
          ? ((err.data as { message?: string })?.message ?? `Failed to add ${member.username}`)
          : `Failed to add ${member.username}`
      error = message
    } finally {
      addingMembers.delete(member.user_id)
    }
  }

  function handleClose() {
    const count = addedCount
    search = ''
    error = ''
    success = ''
    addedCount = 0
    onclose?.()
    if (count > 0) {
      onmembersAdded?.(count)
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      handleClose()
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center"
    data-testid="add-channel-members-modal"
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/50 backdrop-blur-sm"
      onclick={handleClose}
      role="button"
      tabindex="-1"
      aria-label="Close modal"
    ></div>

    <!-- Modal -->
    <div
      class="relative mx-4 flex max-h-[80vh] w-full max-w-md flex-col overflow-hidden rounded-xl bg-white shadow-2xl"
    >
      <!-- Header -->
      <div class="flex items-center justify-between border-b border-gray-200 px-6 py-4">
        <div>
          <h2 class="text-xl font-bold text-gray-900">Add Members</h2>
          {#if channelName}
            <p class="mt-0.5 text-sm text-gray-500">To #{channelName}</p>
          {/if}
        </div>
        <button
          onclick={handleClose}
          class="rounded-lg p-1 transition-colors hover:bg-gray-100"
          aria-label="Close"
        >
          <X class="h-5 w-5 text-gray-500" />
        </button>
      </div>

      <!-- Search -->
      <div class="border-b border-gray-100 px-6 py-4">
        <div class="relative">
          <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
          <input
            bind:value={search}
            type="text"
            placeholder="Search for team members..."
            class="w-full rounded-lg border border-gray-200 bg-gray-50 py-2 pl-10 pr-4 text-sm text-gray-900 outline-none transition-all focus:border-transparent focus:ring-2 focus:ring-indigo-500"
            autofocus
          />
        </div>
      </div>

      <!-- Content -->
      <div class="custom-scrollbar min-h-[200px] flex-1 overflow-y-auto p-2">
        {#if error}
          <div class="m-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">
            {error}
          </div>
        {/if}

        {#if success}
          <div class="m-4 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-600">
            {success}
          </div>
        {/if}

        {#if ($chatStore.loading || channelMembersLoading) && members.length === 0}
          <div class="flex flex-col items-center justify-center py-12 text-gray-500">
            <div
              class="mb-4 h-8 w-8 animate-spin rounded-full border-4 border-indigo-500/20 border-t-indigo-500"
            ></div>
            <p class="text-sm">Loading members...</p>
          </div>
        {:else if filteredMembers.length > 0}
          <div class="space-y-1">
            {#each filteredMembers as member (member.user_id)}
              <button
                onclick={() => addMember(member)}
                disabled={addingMembers.has(member.user_id)}
                class="group flex w-full items-center justify-between rounded-lg px-4 py-3 text-left transition-colors hover:bg-indigo-50"
              >
                <div class="flex items-center">
                  <div class="relative mr-4">
                    {#if member.avatar_url}
                      <img
                        src={member.avatar_url}
                        alt=""
                        class="h-10 w-10 rounded-full object-cover shadow-sm ring-2 ring-white"
                      />
                    {:else}
                      <div
                        class="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-100 shadow-sm ring-2 ring-white"
                      >
                        <User class="h-6 w-6 text-indigo-500" />
                      </div>
                    {/if}
                  </div>

                  <div class="min-w-0 flex-1">
                    <p class="truncate text-sm font-semibold text-gray-900">
                      {member.display_name || member.username}
                    </p>
                    <p class="truncate text-xs text-gray-500">
                      @{member.username}
                    </p>
                  </div>
                </div>

                {#if addingMembers.has(member.user_id)}
                  <div class="flex h-8 w-8 items-center justify-center">
                    <div
                      class="h-5 w-5 animate-spin rounded-full border-2 border-indigo-500/20 border-t-indigo-500"
                    ></div>
                  </div>
                {:else}
                  <div
                    class="flex h-8 w-8 items-center justify-center rounded-full bg-indigo-100 text-indigo-600 opacity-0 transition-opacity group-hover:opacity-100"
                  >
                    <UserPlus class="h-4 w-4" />
                  </div>
                {/if}
              </button>
            {/each}
          </div>
        {:else}
          <div class="flex flex-col items-center justify-center px-6 py-12 text-center text-gray-500">
            <div class="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-gray-100">
              <UserPlus class="h-6 w-6 text-gray-400" />
            </div>
            <p class="text-sm font-medium">No members to add</p>
            <p class="mt-1 text-xs">All team members are already in this channel</p>
          </div>
        {/if}
      </div>

      <!-- Footer -->
      <div class="flex justify-end border-t border-gray-200 bg-gray-50 px-6 py-4">
        <button
          type="button"
          onclick={handleClose}
          class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50"
        >
          Done
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .custom-scrollbar::-webkit-scrollbar {
    width: 4px;
  }
  .custom-scrollbar::-webkit-scrollbar-track {
    background: transparent;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb {
    background: #cbd5e1;
    border-radius: 4px;
  }
  .dark .custom-scrollbar::-webkit-scrollbar-thumb {
    background: #475569;
  }
</style>
