// frontend/src/svelte/views/auth/RegisterView.svelte
<script lang="ts">
  import TurnstileWidget from '../../components/auth/TurnstileWidget.svelte'

  let username = ''
  let email = ''
  let website = ''
  let loading = false
  let error = ''
  let success = false
  let registeredEmail = ''
  let turnstileEnabled = false
  let turnstileSiteKey = ''
  let turnstileToken = ''
  let turnstileWidget: { reset: () => void } | undefined

  $: turnstileReady = !turnstileEnabled || turnstileToken.length > 0

  function apiUrl(path: string) {
    const baseUrl = import.meta.env.VITE_API_URL || '/api/v1'
    return `${baseUrl}${path}`
  }

  function navigate(path: string) {
    window.history.pushState({}, '', path)
    window.dispatchEvent(new PopStateEvent('popstate'))
  }

  async function readError(response: Response, fallback: string) {
    try {
      const data = await response.json()
      return data?.message ?? data?.error ?? fallback
    } catch {
      return fallback
    }
  }

  async function loadAuthConfig() {
    try {
      const response = await fetch(apiUrl('/auth/config'))
      if (!response.ok) return
      const data = await response.json()
      turnstileEnabled = Boolean(data.turnstile?.enabled)
      turnstileSiteKey = data.turnstile?.site_key ?? ''
    } catch {
      turnstileEnabled = false
      turnstileSiteKey = ''
    }
  }

  async function handleRegister() {
    if (website) {
      error = 'Invalid request'
      return
    }

    if (!turnstileReady) {
      error = 'Please complete the verification'
      return
    }

    loading = true
    error = ''

    try {
      const response = await fetch(apiUrl('/auth/register'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username,
          email,
          display_name: username,
          'cf-turnstile-response': turnstileToken || undefined,
          website: website || undefined,
        }),
      })

      if (!response.ok) {
        throw new Error(await readError(response, 'Failed to register'))
      }

      const data = await response.json()
      registeredEmail = data.email ?? email
      success = true

      if (data.token) {
        localStorage.setItem('auth_token', data.token)
        window.location.href = '/'
      }
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to register'
      turnstileToken = ''
      turnstileWidget?.reset()
    } finally {
      loading = false
    }
  }

  loadAuthConfig()
</script>

<svelte:head>
  <title>Create account - RustChat</title>
</svelte:head>

<main class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <section class="sm:mx-auto sm:w-full sm:max-w-md" aria-labelledby="register-title">
    <h1 id="register-title" class="text-center text-3xl font-bold tracking-tight text-gray-900">
      Create your RustChat account
    </h1>
    <p class="mt-2 text-center text-sm text-gray-600">
      Already have an account?
      <a href="/login" class="font-medium text-primary hover:text-blue-500" on:click|preventDefault={() => navigate('/login')}>Sign in</a>
    </p>
  </section>

  <section class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white px-4 py-8 shadow sm:rounded-lg sm:px-10">
      {#if success}
        <div class="text-center py-8">
          <div class="mx-auto flex items-center justify-center h-16 w-16 rounded-full bg-green-100 mb-6">
            <svg class="h-8 w-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
          </div>
          <h2 class="text-xl font-semibold text-gray-900 mb-2">Check your email</h2>
          <p class="text-gray-600 mb-6">
            We've sent a password setup link to <strong>{registeredEmail}</strong>. Please check your inbox and click the link to complete your registration.
          </p>
          <button type="button" class="flex w-full justify-center rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50" on:click={() => navigate('/login')}>
            Go to Login
          </button>
        </div>
      {:else}
        <form class="space-y-6" on:submit|preventDefault={handleRegister}>
          {#if error}
            <div class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-md text-sm" role="alert">
              {error}
            </div>
          {/if}

          <div class="honeypot-field" aria-hidden="true">
            <label for="website">Website</label>
            <input id="website" type="text" name="website" bind:value={website} tabindex="-1" autocomplete="off" />
          </div>

          <div>
            <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
            <input id="username" name="username" required placeholder="jdoe" bind:value={username} class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" />
          </div>

          <div>
            <label for="email" class="block text-sm font-medium text-gray-700">Email address</label>
            <input id="email" name="email" type="email" autocomplete="email" required placeholder="you@example.com" bind:value={email} class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" />
          </div>

          <div class="bg-blue-50 border border-blue-200 rounded-md p-4">
            <p class="text-sm text-blue-700">You'll receive an email with a link to set your password after registration.</p>
          </div>

          {#if turnstileEnabled && turnstileSiteKey}
            <TurnstileWidget
              bind:this={turnstileWidget}
              siteKey={turnstileSiteKey}
              onVerify={(token) => {
                turnstileToken = token
              }}
              onError={() => {
                turnstileToken = ''
                error = 'Verification failed. Please try again.'
              }}
              onExpired={() => {
                turnstileToken = ''
              }}
            />
          {/if}

          <button
            type="submit"
            disabled={loading || !turnstileReady}
            class="flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {loading ? 'Creating account...' : 'Create Account'}
          </button>
        </form>
      {/if}
    </div>
  </section>
</main>

<style>
  .honeypot-field {
    position: absolute;
    left: -9999px;
    top: -9999px;
    opacity: 0;
    height: 0;
    width: 0;
    overflow: hidden;
  }
</style>

// frontend/src/views/auth/RegisterView.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import client from '../../api/client'
import AuthLayout from '../../layouts/AuthLayout.vue'
import BaseInput from '../../components/atomic/BaseInput.vue'
import BaseButton from '../../components/atomic/BaseButton.vue'
import TurnstileWidget from '../../components/auth/TurnstileWidget.vue'
import { useConfigStore } from '../../features/config/stores/configStore'
import { getApiErrorMessage } from '@/core/errors/errorUtils'

const router = useRouter()
const configStore = useConfigStore()

const username = ref('')
const email = ref('')
const website = ref('') // Honeypot field - should remain empty
const turnstileToken = ref('')
const loading = ref(false)
const error = ref('')
const success = ref(false)
const registeredEmail = ref('')

// Turnstile configuration
const turnstileEnabled = ref(false)
const turnstileSiteKey = ref('')
const turnstileVerified = ref(false)

onMounted(async () => {
  configStore.loadConfig()
  
  // Fetch Turnstile configuration
  try {
    const response = await client.get('/auth/config')
    if (response.data.turnstile?.enabled) {
      turnstileEnabled.value = true
      turnstileSiteKey.value = response.data.turnstile.site_key
    }
  } catch {
    // Ignore errors - Turnstile will be disabled
  }
})

function onTurnstileVerify(token: string) {
  turnstileToken.value = token
  turnstileVerified.value = true
}

function onTurnstileError() {
  turnstileVerified.value = false
  error.value = 'Verification failed. Please try again.'
}

async function handleRegister() {
  // Check honeypot
  if (website.value) {
    // Silently fail if honeypot is filled
    error.value = 'Invalid request'
    return
  }

  // Check Turnstile verification if enabled
  if (turnstileEnabled.value && !turnstileVerified.value) {
    error.value = 'Please complete the verification'
    return
  }

  loading.value = true
  error.value = ''
  try {
    const response = await client.post('/auth/register', {
      username: username.value,
      email: email.value,
      display_name: username.value,
      'cf-turnstile-response': turnstileToken.value || undefined,
      website: website.value || undefined
    })
    
    registeredEmail.value = response.data.email || email.value
    success.value = true
    
    // If password setup is required, show success message
    // User will receive email with password setup link
    if (response.data.requires_password_setup) {
      // Stay on page and show success message
    } else {
      // Auto-login was provided, redirect to home
      if (response.data.token) {
        localStorage.setItem('auth_token', response.data.token)
        window.location.href = '/'
      }
    }
  } catch (e: unknown) {
    error.value = getApiErrorMessage(e) || 'Failed to register'
    // Reset Turnstile on error
    turnstileVerified.value = false
    turnstileToken.value = ''
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <AuthLayout>
    <template #title>Create your {{ configStore.siteConfig.site_name }} account</template>
    <template #subtitle>
      Already have an account? <router-link to="/login" class="font-medium text-primary hover:text-blue-500">Sign in</router-link>
    </template>

    <!-- Success State -->
    <div v-if="success" class="text-center py-8">
      <div class="mx-auto flex items-center justify-center h-16 w-16 rounded-full bg-green-100 mb-6">
        <svg class="h-8 w-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
        </svg>
      </div>
      <h3 class="text-xl font-semibold text-gray-900 mb-2">
        Check your email
      </h3>
      <p class="text-gray-600 mb-6">
        We've sent a password setup link to <strong>{{ registeredEmail }}</strong>.
        Please check your inbox and click the link to set your password and complete your registration.
      </p>
      <div class="space-y-4">
        <p class="text-sm text-gray-500">
          Didn't receive the email? Check your spam folder or 
          <router-link to="/login" class="text-indigo-600 hover:text-indigo-500">try logging in</router-link>
          to resend.
        </p>
        <BaseButton @click="router.push('/login')" variant="secondary" block>
          Go to Login
        </BaseButton>
      </div>
    </div>

    <!-- Registration Form -->
    <form v-else class="space-y-6" @submit.prevent="handleRegister">
      <div v-if="error" class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-md text-sm">
        {{ error }}
      </div>

      <!-- Honeypot field - hidden from humans -->
      <div class="honeypot-field" aria-hidden="true">
        <input
          type="text"
          name="website"
          v-model="website"
          tabindex="-1"
          autocomplete="off"
        />
      </div>

      <BaseInput
        id="username"
        label="Username"
        v-model="username"
        required
        placeholder="jdoe"
      />

      <BaseInput
        id="email"
        type="email"
        label="Email address"
        v-model="email"
        required
        placeholder="you@example.com"
      />

      <div class="bg-blue-50 border border-blue-200 rounded-md p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <p class="text-sm text-blue-700">
              You'll receive an email with a link to set your password after registration.
            </p>
          </div>
        </div>
      </div>

      <!-- Turnstile Widget -->
      <TurnstileWidget
        v-if="turnstileEnabled && turnstileSiteKey"
        :site-key="turnstileSiteKey"
        @verify="onTurnstileVerify"
        @error="onTurnstileError"
      />

      <div>
        <BaseButton 
          type="submit" 
          block 
          :loading="loading"
          :disabled="turnstileEnabled && !turnstileVerified"
        >
          Create Account
        </BaseButton>
      </div>
    </form>
  </AuthLayout>
</template>

<style scoped>
/* Hide honeypot field from humans */
.honeypot-field {
  position: absolute;
  left: -9999px;
  top: -9999px;
  opacity: 0;
  height: 0;
  width: 0;
  overflow: hidden;
}
</style>
