// frontend/src/svelte/views/playbooks/PlaybookRun.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { ArrowLeft, CheckCircle2, Circle, Loader2, Send } from 'lucide-svelte'
  import { playbooksStore } from '../../stores/playbooks'

  let runId = $state<string | null>(null)
  let loading = $state(false)
  let error = $state<string | null>(null)
  let updateMessage = $state('')

  const run = $derived($playbooksStore.currentRun?.run ?? null)
  const tasks = $derived($playbooksStore.currentRun?.tasks ?? [])
  const progress = $derived($playbooksStore.currentRun?.progress ?? { total: 0, completed: 0, in_progress: 0, pending: 0 })
  const completion = $derived(progress.total > 0 ? Math.round((progress.completed / progress.total) * 100) : 0)

  function navigate(path: string) {
    window.history.pushState({}, '', path)
    window.dispatchEvent(new PopStateEvent('popstate'))
  }

  async function load() {
    const match = window.location.pathname.match(/^\/runs\/([^/]+)$/)
    runId = match?.[1] ?? null
    if (!runId) {
      error = 'Run not found.'
      return
    }

    loading = true
    error = null
    try {
      await Promise.all([
        playbooksStore.fetchRun(runId),
        playbooksStore.fetchStatusUpdates(runId),
      ])
    } catch (loadError) {
      error = loadError instanceof Error ? loadError.message : 'Failed to load run.'
    } finally {
      loading = false
    }
  }

  async function toggleTask(taskId: string, done: boolean) {
    if (!runId) return
    await playbooksStore.updateRunTask(runId, taskId, { status: done ? 'pending' : 'done' })
  }

  async function finishRun() {
    if (!runId) return
    await playbooksStore.finishRun(runId)
  }

  async function postUpdate() {
    if (!runId || !updateMessage.trim()) return
    await playbooksStore.createStatusUpdate(runId, updateMessage.trim())
    updateMessage = ''
  }

  function formatDate(value: string | null) {
    if (!value) return 'Not finished'
    return new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
  }

  onMount(() => {
    void load()
  })
</script>

<main class="min-h-screen bg-bg-app text-text-1">
  <header class="border-b border-border-1 bg-bg-surface-1 px-6 py-4">
    <div class="mx-auto flex max-w-5xl items-center justify-between gap-4">
      <div class="flex items-center gap-3">
        <button
          type="button"
          class="flex h-9 w-9 items-center justify-center rounded-r-2 text-text-3 transition-standard hover:bg-bg-surface-2 hover:text-text-1"
          aria-label="Back to playbooks"
          on:click={() => navigate('/playbooks')}
        >
          <ArrowLeft class="h-5 w-5" />
        </button>
        <div>
          <h1 class="text-xl font-bold">{run?.name ?? 'Playbook Run'}</h1>
          <p class="text-sm text-text-3">{run ? `${run.status.replace('_', ' ')} - started ${formatDate(run.started_at)}` : 'Loading run details'}</p>
        </div>
      </div>
      {#if run && run.status === 'in_progress'}
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-r-2 bg-success px-4 py-2.5 text-sm font-semibold text-white transition-standard hover:opacity-90"
          on:click={finishRun}
        >
          <CheckCircle2 class="h-4 w-4" />
          Finish Run
        </button>
      {/if}
    </div>
  </header>

  <section class="mx-auto grid max-w-5xl gap-6 px-6 py-6 lg:grid-cols-[1fr_20rem]">
    {#if error}
      <div class="rounded-r-2 border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger lg:col-span-2" role="alert">
        {error}
      </div>
    {/if}

    {#if loading}
      <div class="flex items-center justify-center rounded-r-3 border border-border-1 bg-bg-surface-1 py-16 text-text-3 lg:col-span-2">
        <Loader2 class="mr-2 h-5 w-5 animate-spin" />
        Loading run...
      </div>
    {:else}
      <section class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
        <div class="mb-5">
          <div class="mb-2 flex items-center justify-between text-sm">
            <span class="font-semibold">Progress</span>
            <span class="text-text-3">{progress.completed} of {progress.total} complete</span>
          </div>
          <div class="h-2 overflow-hidden rounded-full bg-bg-surface-2">
            <div class="h-full rounded-full bg-success transition-all" style={`width: ${completion}%`}></div>
          </div>
        </div>

        <div class="space-y-3">
          {#each tasks as task (task.id)}
            <button
              type="button"
              class="flex w-full items-start gap-3 rounded-r-2 border border-border-1 p-3 text-left transition-standard hover:bg-bg-surface-2"
              on:click={() => toggleTask(task.id, task.status === 'done')}
            >
              {#if task.status === 'done'}
                <CheckCircle2 class="mt-0.5 h-5 w-5 shrink-0 text-success" />
              {:else}
                <Circle class="mt-0.5 h-5 w-5 shrink-0 text-text-4" />
              {/if}
              <span>
                <span class="block text-sm font-semibold">Task {task.task_id}</span>
                <span class="block text-xs text-text-3">{task.status.replace('_', ' ')}{task.notes ? ` - ${task.notes}` : ''}</span>
              </span>
            </button>
          {:else}
            <div class="rounded-r-2 border border-dashed border-border-1 py-10 text-center text-sm text-text-3">
              No tasks are attached to this run.
            </div>
          {/each}
        </div>
      </section>

      <aside class="space-y-4">
        <section class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
          <h2 class="mb-3 text-sm font-bold uppercase tracking-[0.16em] text-text-3">Run Details</h2>
          <dl class="space-y-3 text-sm">
            <div>
              <dt class="text-text-3">Status</dt>
              <dd class="font-semibold capitalize">{run?.status.replace('_', ' ') ?? 'Unknown'}</dd>
            </div>
            <div>
              <dt class="text-text-3">Started</dt>
              <dd>{formatDate(run?.started_at ?? null)}</dd>
            </div>
            <div>
              <dt class="text-text-3">Finished</dt>
              <dd>{formatDate(run?.finished_at ?? null)}</dd>
            </div>
          </dl>
        </section>

        <section class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
          <h2 class="mb-3 text-sm font-bold uppercase tracking-[0.16em] text-text-3">Updates</h2>
          <div class="mb-3 space-y-2">
            {#each $playbooksStore.statusUpdates as update (update.id)}
              <article class="rounded-r-2 bg-bg-surface-2 p-3 text-sm">
                <p>{update.message}</p>
                <p class="mt-1 text-xs text-text-3">{formatDate(update.created_at)}</p>
              </article>
            {:else}
              <p class="text-sm text-text-3">No status updates yet.</p>
            {/each}
          </div>
          <div class="flex gap-2">
            <input
              class="min-w-0 flex-1 rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm"
              bind:value={updateMessage}
              placeholder="Post an update"
              on:keydown={(event) => { if (event.key === 'Enter') void postUpdate() }}
            />
            <button type="button" class="rounded-r-2 bg-brand p-2 text-brand-foreground" aria-label="Post update" on:click={postUpdate}>
              <Send class="h-4 w-4" />
            </button>
          </div>
        </section>
      </aside>
    {/if}
  </section>
</main>

// frontend/src/components/playbooks/PlaybookRun.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, CheckCircle2, Circle, Send } from 'lucide-vue-next'
import { useToast } from '../../composables/useToast'
import { playbooksApi, type RunWithTasks, type RunStatusUpdate, type RunTask } from '../../api/playbooks'

const route = useRoute()
const router = useRouter()
const toast = useToast()

const run = ref<RunWithTasks | null>(null)
const updates = ref<RunStatusUpdate[]>([])
const newUpdate = ref('')
const loading = ref(true)
const sendingUpdate = ref(false)

const progressPercent = computed(() => {
    if (!run.value) return 0
    return Math.round((run.value.progress.completed / run.value.progress.total) * 100) || 0
})

const taskMap = ref<Record<string, { title: string, description: string | null }>>({})

onMounted(async () => {
    const runId = route.params.id as string
    if (runId) {
        try {
            const response = await playbooksApi.getRun(runId)
            run.value = response.data
            
            // Fetch playbook to get task details
            if (run.value) {
                const playbookRes = await playbooksApi.get(run.value.run.playbook_id)
                // Flatten tasks
                playbookRes.data.checklists.forEach(c => {
                    c.tasks.forEach(t => {
                        taskMap.value[t.id] = { title: t.title, description: t.description }
                    })
                })
            }

            await fetchUpdates()
        } catch (e) {
            toast.error('Error', 'Failed to load run')
            router.push('/playbooks')
        } finally {
            loading.value = false
        }
    }
})

async function fetchUpdates() {
    if (!run.value) return
    try {
        const response = await playbooksApi.listStatusUpdates(run.value.run.id)
        updates.value = response.data
    } catch(e) {
        console.error('Failed to fetch updates', e)
    }
}

async function postUpdate() {
    if (!run.value || !newUpdate.value.trim()) return
    sendingUpdate.value = true
    try {
        const response = await playbooksApi.createStatusUpdate(run.value.run.id, {
            message: newUpdate.value,
            is_broadcast: false
        })
        updates.value.unshift(response.data)
        newUpdate.value = ''
    } catch (e) {
        toast.error('Error', 'Failed to post update')
    } finally {
        sendingUpdate.value = false
    }
}

async function toggleTask(task: RunTask) {
    if (!run.value) return
    const newStatus = task.status === 'done' ? 'pending' : 'done'
    
    // Optimistic update
    const oldStatus = task.status
    task.status = newStatus
    
    // Update progress locally
    if (newStatus === 'done') {
        run.value.progress.completed++
        run.value.progress.pending--
    } else {
        run.value.progress.completed--
        run.value.progress.pending++
    }

    try {
        await playbooksApi.updateRunTask(run.value.run.id, task.task_id, {
            status: newStatus
        })
    } catch (e) {
        // Revert task status and progress counters
        task.status = oldStatus
        if (newStatus === 'done') {
            run.value.progress.completed--
            run.value.progress.pending++
        } else {
            run.value.progress.completed++
            run.value.progress.pending--
        }
        toast.error('Error', 'Failed to update task')
    }
}

function formatDate(date: string) {
    return new Date(date).toLocaleString()
}
</script>

<template>
    <div class="h-full flex flex-col bg-gray-50">
        <div v-if="loading" class="flex-1 flex items-center justify-center">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>

        <template v-else-if="run">
            <!-- Header -->
            <header class="bg-white border-b border-gray-200 px-6 py-4">
                <div class="flex items-center space-x-4 mb-4">
                    <button @click="router.push('/playbooks')" class="p-2 hover:bg-gray-100 rounded-lg">
                        <ArrowLeft class="w-5 h-5 text-gray-500" />
                    </button>
                    <div>
                        <div class="flex items-center space-x-2">
                            <h1 class="text-xl font-bold text-gray-900">{{ run.run.name }}</h1>
                            <span class="px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 capitalize">
                                {{ run.run.status.replace('_', ' ') }}
                            </span>
                        </div>
                        <p class="text-sm text-gray-500">Started {{ formatDate(run.run.started_at) }}</p>
                    </div>
                </div>

                <!-- Progress Bar -->
                <div class="w-full bg-gray-200 rounded-full h-2.5 mb-1">
                    <div class="bg-primary h-2.5 rounded-full transition-all duration-500" :style="{ width: `${progressPercent}%` }"></div>
                </div>
                <div class="flex justify-between text-xs text-gray-500">
                    <span>{{ progressPercent }}% Complete</span>
                    <span>{{ run.progress.completed }}/{{ run.progress.total }} tasks</span>
                </div>
            </header>

            <div class="flex-1 flex overflow-hidden">
                <!-- Tasks List -->
                <div class="flex-1 overflow-y-auto p-6 border-r border-gray-200">
                    <h2 class="text-lg font-semibold mb-4 text-gray-900">Tasks</h2>
                    <div class="space-y-4">
                        <div 
                            v-for="task in run.tasks" 
                            :key="task.id"
                            class="bg-white p-4 rounded-lg border border-gray-200 flex items-start space-x-3 hover:shadow-sm transition-shadow"
                            :class="{ 'opacity-75': task.status === 'done' }"
                        >
                            <button 
                                @click="toggleTask(task)"
                                class="mt-1 flex-shrink-0 text-gray-400 hover:text-primary transition-colors"
                                :class="{ 'text-green-500': task.status === 'done' }"
                            >
                                <CheckCircle2 v-if="task.status === 'done'" class="w-5 h-5" />
                                <Circle v-else class="w-5 h-5" />
                            </button>
                            
                            <div class="flex-1">
                                <p class="text-gray-900 font-medium" :class="{ 'line-through text-gray-500': task.status === 'done' }">
                                    {{ taskMap[task.task_id]?.title || 'Unknown Task' }}
                                </p>
                                <p v-if="taskMap[task.task_id]?.description" class="text-sm text-gray-500 mt-0.5">{{ taskMap[task.task_id]?.description }}</p>
                                <p v-if="task.notes" class="text-sm text-gray-500 mt-1 italic">{{ task.notes }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Sidebar: Status Updates -->
                <div class="w-80 bg-white flex flex-col border-l border-gray-200">
                    <div class="p-4 border-b border-gray-200">
                        <h2 class="text-lg font-semibold text-gray-900">Timeline</h2>
                    </div>

                    <div class="flex-1 overflow-y-auto p-4 space-y-4">
                        <div v-for="update in updates" :key="update.id" class="flex space-x-3">
                            <div class="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center flex-shrink-0">
                                <span class="text-xs font-medium text-gray-600">U</span>
                            </div>
                            <div>
                                <div class="bg-gray-100 rounded-lg p-3 text-sm text-gray-800">
                                    {{ update.message }}
                                </div>
                                <p class="text-xs text-gray-500 mt-1">{{ formatDate(update.created_at) }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="p-4 border-t border-gray-200 bg-gray-50">
                        <form @submit.prevent="postUpdate" class="flex space-x-2">
                            <input 
                                v-model="newUpdate"
                                placeholder="Post an update..." 
                                class="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                            />
                            <button 
                                type="submit" 
                                :disabled="!newUpdate || sendingUpdate"
                                class="p-2 bg-primary text-brand-foreground rounded-lg hover:bg-primary/90 disabled:opacity-50"
                            >
                                <Send class="w-4 h-4" />
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </template>
    </div>
</template>
