// frontend/src/components/settings/profile/ProfileTab.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Camera } from 'lucide-vue-next'
import BaseButton from '../../atomic/BaseButton.vue'
import BaseInput from '../../atomic/BaseInput.vue'
import { v4Api } from '../../../api/client'
import { useAuthStore } from '../../../features/auth/stores/authStore'
import { usersApi } from '../../../api/users'
import { MAX_PROFILE_IMAGE_SIZE } from '../../../constants'
import { getApiErrorMessage } from '@/core/errors/errorUtils'

const auth = useAuthStore()
const loading = ref(false)
const error = ref('')
const success = ref('')
const fileInput = ref<HTMLInputElement | null>(null)

// Profile form fields
const username = ref('')
const displayName = ref('')
const avatarUrl = ref('')
const firstName = ref('')
const lastName = ref('')
const nickname = ref('')
const position = ref('')

// Status fields
const statusText = ref('')
const statusEmoji = ref('')

const errorClass = 'rounded-r-2 border border-danger/20 bg-danger/10 p-3 text-sm text-danger'
const successClass = 'rounded-r-2 border border-success/20 bg-success/10 p-3 text-sm text-success'
const sectionClass = 'rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1'
const sectionHeaderClass = 'border-b border-border-1 pb-3'
const sectionTitleClass = 'text-sm font-semibold tracking-[0.01em] text-text-1'
const sectionBodyClass = 'mt-4 space-y-4'
const helperTextClass = 'text-xs text-text-3'
const readOnlyCardClass =
  'rounded-r-2 border border-border-1 bg-bg-surface-2 px-3 py-2 text-sm text-text-3 break-all'

// Initialize from auth user
watch(
  () => auth.user,
  user => {
    if (user) {
      username.value = user.username || ''
      displayName.value = user.display_name || ''
      avatarUrl.value = user.avatar_url || ''
      firstName.value = user.first_name || ''
      lastName.value = user.last_name || ''
      nickname.value = user.nickname || ''
      position.value = user.position || ''
      statusText.value = user.status_text || ''
      statusEmoji.value = user.status_emoji || ''
    }
  },
  { immediate: true }
)

async function handleFileUpload(event: Event) {
  const input = event.target as HTMLInputElement
  if (input.files && input.files[0]) {
    const file = input.files[0]

    if (!file.type.startsWith('image/')) {
      error.value = 'Please select a valid image file'
      return
    }

    if (file.size > MAX_PROFILE_IMAGE_SIZE) {
      error.value = 'Image size must be less than 5MB'
      return
    }

    loading.value = true
    error.value = ''

    try {
      const formData = new FormData()
      formData.append('image', file)

      await v4Api.post(`/users/${auth.user?.id}/image`, formData)
      await auth.fetchMe()
      avatarUrl.value = auth.user?.avatar_url || ''
      success.value = 'Avatar uploaded successfully!'
    } catch (e: unknown) {
      error.value = getApiErrorMessage(e) || 'Failed to upload avatar'
    } finally {
      loading.value = false
      input.value = ''
    }
  }
}

async function handleSaveProfile() {
  if (!auth.user) return

  loading.value = true
  error.value = ''
  success.value = ''

  try {
    await v4Api.put('/users/me/patch', {
      first_name: firstName.value || undefined,
      last_name: lastName.value || undefined,
      nickname: nickname.value || undefined,
      position: position.value || undefined,
    })

    await usersApi.update(auth.user.id, {
      username: username.value,
      display_name: displayName.value,
      avatar_url: avatarUrl.value,
    })

    await auth.fetchMe()
    success.value = 'Profile updated successfully!'
    setTimeout(() => (success.value = ''), 3000)
  } catch (e: unknown) {
    error.value = getApiErrorMessage(e) || 'Failed to update profile'
  } finally {
    loading.value = false
  }
}

async function handleSaveStatus() {
  loading.value = true
  error.value = ''
  success.value = ''

  try {
    await auth.updateStatus({
      text: statusText.value,
      emoji: statusEmoji.value,
    })
    success.value = 'Status updated successfully!'
    setTimeout(() => (success.value = ''), 3000)
  } catch (e: unknown) {
    error.value = 'Failed to update status'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Messages -->
    <div v-if="error" :class="errorClass">
      {{ error }}
    </div>
    <div v-if="success" :class="successClass">
      {{ success }}
    </div>

    <!-- Profile Section -->
    <div :class="sectionClass">
      <div :class="sectionHeaderClass">
        <h4 :class="sectionTitleClass">Profile Information</h4>
        <p class="mt-1 text-xs text-text-3">
          Keep your identity details current so teammates can recognize and trust who is speaking.
        </p>
      </div>

      <div :class="sectionBodyClass">
        <!-- Avatar -->
        <div class="flex items-center space-x-4">
          <div class="relative group">
            <div
              class="flex h-16 w-16 items-center justify-center overflow-hidden rounded-full bg-brand text-xl font-bold text-brand-foreground ring-2 ring-transparent transition-all group-hover:ring-brand/35 sm:h-20 sm:w-20 sm:text-2xl"
            >
              <img
                v-if="avatarUrl"
                :src="avatarUrl"
                alt="Avatar"
                class="h-full w-full object-cover"
              />
              <span v-else>{{ auth.user?.username?.charAt(0).toUpperCase() || 'U' }}</span>
            </div>
            <button
              type="button"
              class="absolute bottom-0 right-0 flex h-7 w-7 items-center justify-center rounded-full border-2 border-bg-surface-1 bg-brand text-brand-foreground shadow-1 transition-standard hover:bg-brand-hover sm:h-8 sm:w-8"
              @click="fileInput?.click()"
            >
              <Camera class="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            </button>
            <input
              ref="fileInput"
              type="file"
              accept="image/*"
              class="hidden"
              @change="handleFileUpload"
            />
          </div>
          <div>
            <p class="text-sm font-semibold text-text-1">{{ auth.user?.username }}</p>
            <p :class="helperTextClass">
              <button
                type="button"
                class="font-medium text-brand transition-standard hover:text-brand-hover"
                @click="fileInput?.click()"
              >
                Upload a new photo
              </button>
            </p>
          </div>
        </div>

        <!-- Form Fields -->
        <div class="grid grid-cols-1 gap-4">
          <BaseInput
            v-model="username"
            label="Username"
            placeholder="your_username"
            :disabled="loading"
          />
          <BaseInput
            v-model="displayName"
            label="Display Name"
            placeholder="Your Name"
            :disabled="loading"
          />
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <BaseInput
              v-model="firstName"
              label="First Name"
              placeholder="John"
              :disabled="loading"
            />
            <BaseInput v-model="lastName" label="Last Name" placeholder="Doe" :disabled="loading" />
          </div>
          <BaseInput v-model="nickname" label="Nickname" placeholder="Johnny" :disabled="loading" />
          <BaseInput
            v-model="position"
            label="Position"
            placeholder="Software Engineer"
            :disabled="loading"
          />
          <BaseInput
            v-model="avatarUrl"
            label="Avatar URL"
            placeholder="https://example.com/avatar.jpg"
            :disabled="loading"
          />
          <div class="space-y-1">
            <label class="block text-sm font-medium text-text-2">Email</label>
            <div :class="readOnlyCardClass">
              {{ auth.user?.email }}
            </div>
          </div>
        </div>

        <div class="flex justify-end">
          <BaseButton :loading="loading" @click="handleSaveProfile">Save Profile</BaseButton>
        </div>
      </div>
    </div>

    <!-- Status Section -->
    <div :class="sectionClass">
      <div :class="sectionHeaderClass">
        <h4 :class="sectionTitleClass">Custom Status</h4>
        <p class="mt-1 text-xs text-text-3">
          Share quick context with teammates when you are heads-down, away, or on call.
        </p>
      </div>

      <div :class="sectionBodyClass">
        <div class="space-y-4">
          <div class="flex space-x-2">
            <div class="w-12">
              <BaseInput
                v-model="statusEmoji"
                placeholder="😀"
                class="text-center"
                :disabled="loading"
              />
            </div>
            <div class="flex-1">
              <BaseInput
                v-model="statusText"
                placeholder="What's your status?"
                :disabled="loading"
              />
            </div>
          </div>
          <p :class="helperTextClass">
            Enter an emoji and a short message to describe your status.
          </p>
        </div>

        <div class="flex justify-end">
          <BaseButton :loading="loading" @click="handleSaveStatus">Update Status</BaseButton>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/svelte/components/settings/tabs/ProfileTab.svelte
<script lang="ts">
  import { tick } from 'svelte'
  import { authStore } from '../../../stores/auth'
  import { svelteApi } from '../../../stores/http'

  let firstName = $state('')
  let lastName = $state('')
  let nickname = $state('')
  let position = $state('')
  let displayName = $state('')
  let syncedUserId = $state<string | null>(null)
  let saving = $state(false)
  let error = $state<string | null>(null)
  let success = $state<string | null>(null)

  function syncFromUser() {
    const user = $authStore.user
    if (!user || syncedUserId === user.id) return

    syncedUserId = user.id
    firstName = user.first_name || user.firstName || ''
    lastName = user.last_name || user.lastName || ''
    nickname = user.nickname || ''
    position = user.position || ''
    displayName = user.display_name || user.displayName || ''
  }

  $effect(() => {
    syncFromUser()
  })

  async function handleSave() {
    const user = $authStore.user
    if (!user || saving) {
      return
    }

    saving = true
    error = null
    success = null

    try {
      await svelteApi.put('/users/me/patch', {
        first_name: firstName.trim(),
        last_name: lastName.trim(),
        nickname: nickname.trim(),
        position: position.trim(),
      }, { baseURL: '/api/v4' })

      await svelteApi.put(`/users/${user.id}`, {
        display_name: displayName.trim(),
        username: user.username,
      })

      syncedUserId = null
      await authStore.fetchMe()
      await tick()
      success = 'Profile saved.'
    } catch (saveError) {
      error = saveError instanceof Error ? saveError.message : 'Failed to save profile.'
    } finally {
      saving = false
    }
  }
</script>

<div class="space-y-6">
  <div class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
    <div class="border-b border-border-1 pb-3">
      <h4 class="text-sm font-semibold tracking-[0.01em] text-text-1">Profile Information</h4>
      <p class="mt-1 text-xs text-text-3">Keep your identity details current so teammates can recognize and trust who is speaking.</p>
    </div>

    <div class="mt-4 space-y-4">
      <!-- Display Name -->
      <div>
        <label class="mb-1 block text-sm font-medium text-text-1">Display Name</label>
        <input
          type="text"
          bind:value={displayName}
          placeholder="Your Name"
          class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 outline-none transition-standard placeholder:text-text-3 focus:border-brand focus:ring-2 focus:ring-brand/15"
        />
      </div>

      <!-- First & Last Name -->
      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <label class="mb-1 block text-sm font-medium text-text-1">First Name</label>
          <input
            type="text"
            bind:value={firstName}
            placeholder="John"
            class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 outline-none transition-standard placeholder:text-text-3 focus:border-brand focus:ring-2 focus:ring-brand/15"
          />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-text-1">Last Name</label>
          <input
            type="text"
            bind:value={lastName}
            placeholder="Doe"
            class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 outline-none transition-standard placeholder:text-text-3 focus:border-brand focus:ring-2 focus:ring-brand/15"
          />
        </div>
      </div>

      <!-- Nickname -->
      <div>
        <label class="mb-1 block text-sm font-medium text-text-1">Nickname</label>
        <input
          type="text"
          bind:value={nickname}
          placeholder="Johnny"
          class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 outline-none transition-standard placeholder:text-text-3 focus:border-brand focus:ring-2 focus:ring-brand/15"
        />
      </div>

      <!-- Position -->
      <div>
        <label class="mb-1 block text-sm font-medium text-text-1">Position</label>
        <input
          type="text"
          bind:value={position}
          placeholder="Software Engineer"
          class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 outline-none transition-standard placeholder:text-text-3 focus:border-brand focus:ring-2 focus:ring-brand/15"
        />
      </div>

      <!-- Email (read-only) -->
      <div>
        <label class="mb-1 block text-sm font-medium text-text-2">Email</label>
        <div class="rounded-r-2 border border-border-1 bg-bg-surface-2 px-3 py-2 text-sm text-text-3 break-all">
          {$authStore.user?.email || '—'}
        </div>
      </div>

      <!-- Username (read-only) -->
      <div>
        <label class="mb-1 block text-sm font-medium text-text-2">Username</label>
        <div class="rounded-r-2 border border-border-1 bg-bg-surface-2 px-3 py-2 text-sm text-text-3 break-all">
          {$authStore.user?.username || '—'}
        </div>
      </div>

      <!-- Save Button -->
      {#if error}
        <div class="rounded-r-2 border border-danger/30 bg-danger/10 px-3 py-2 text-sm text-danger" role="alert">
          {error}
        </div>
      {/if}

      {#if success}
        <div class="rounded-r-2 border border-success/30 bg-success/10 px-3 py-2 text-sm text-success" role="status">
          {success}
        </div>
      {/if}

      <div class="flex justify-end">
        <button
          type="button"
          on:click={handleSave}
          disabled={saving || !$authStore.user}
          class="rounded-r-2 bg-brand px-4 py-2.5 text-sm font-medium text-brand-foreground transition-standard hover:bg-brand-hover disabled:cursor-not-allowed disabled:opacity-60"
        >
          {saving ? 'Saving...' : 'Save Profile'}
        </button>
      </div>
    </div>
  </div>
</div>
