// frontend/src/svelte/components/modals/CreateTeamModal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { X } from 'lucide-svelte'
  import { svelteApi, SvelteHttpError } from '../../stores/http'
  import { authStore } from '../../stores/auth'
  import { canCreateTeam } from '@/features/permissions/capabilities'

  interface Props {
    open?: boolean
  }

  let { open = false }: Props = $props()

  const dispatch = createEventDispatcher<{ close: void }>()

  let name = $state('')
  let displayName = $state('')
  let description = $state('')
  let loading = $state(false)
  let error = $state('')

  const canCreate = $derived(canCreateTeam($authStore.user?.role))

  function resetForm() {
    name = ''
    displayName = ''
    description = ''
    error = ''
  }

  function handleClose() {
    resetForm()
    dispatch('close')
  }

  $effect(() => {
    if (!open) {
      resetForm()
    }
  })

  async function handleSubmit(event: Event) {
    event.preventDefault()

    if (!canCreate) {
      error = 'You do not have permission to create teams'
      return
    }

    if (!name.trim()) {
      error = 'Team name is required'
      return
    }

    loading = true
    error = ''

    try {
      await svelteApi.post('/teams', {
        name: name.trim().toLowerCase().replace(/\s+/g, '-'),
        display_name: displayName.trim() || name.trim(),
        description: description.trim() || undefined,
      })

      resetForm()
      dispatch('close')
    } catch (e: unknown) {
      if (e instanceof SvelteHttpError && e.data && typeof e.data === 'object' && 'message' in e.data) {
        error = String(e.data.message)
      } else if (e instanceof Error) {
        error = e.message
      } else {
        error = 'Failed to create team'
      }
    } finally {
      loading = false
    }
  }
</script>

<svelte:window on:keydown={(e) => open && e.key === 'Escape' && handleClose()} />

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4"
    data-testid="create-team-modal"
    role="dialog"
    aria-modal="true"
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/60 backdrop-blur-sm"
      on:click={handleClose}
      role="button"
      tabindex="-1"
      aria-label="Close create team modal"
    ></div>

    <!-- Modal -->
    <div
      class="relative bg-bg-surface-1 rounded-r-3 shadow-2xl ring-1 ring-border-1 w-full max-w-md overflow-hidden"
    >
      <!-- Header -->
      <div class="flex items-center justify-between px-6 py-4 border-b border-border-1">
        <h2 class="text-lg font-semibold text-text-1">Create Team</h2>
        <button
          type="button"
          on:click={handleClose}
          class="flex h-10 w-10 items-center justify-center rounded-r-2 text-text-3 hover:text-text-1 hover:bg-bg-surface-2 transition-standard focus-ring"
          aria-label="Close"
        >
          <X class="h-5 w-5" />
        </button>
      </div>

      {#if !canCreate}
        <div class="p-6 space-y-4">
          <div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
            You do not have permission to create teams.
          </div>
          <div class="flex justify-end pt-2">
            <button
              type="button"
              on:click={handleClose}
              class="px-4 py-2 text-sm font-medium text-text-2 bg-bg-surface-2 rounded-lg hover:bg-bg-surface-1 border border-border-2 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      {:else}
        <form on:submit={handleSubmit} class="p-6 space-y-4">
          <!-- Error -->
          {#if error}
            <div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
              {error}
            </div>
          {/if}

          <!-- Name -->
          <div>
            <label class="block text-sm font-medium text-text-2 mb-1">
              Team Name
            </label>
            <input
              type="text"
              bind:value={name}
              placeholder="e.g., engineering"
              required
              disabled={loading}
              class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
            />
          </div>

          <!-- Display Name -->
          <div>
            <label class="block text-sm font-medium text-text-2 mb-1">
              Display Name
            </label>
            <input
              type="text"
              bind:value={displayName}
              placeholder="e.g., Engineering Team"
              disabled={loading}
              class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
            />
          </div>

          <!-- Description -->
          <div>
            <label class="block text-sm font-medium text-text-2 mb-1">
              Description
            </label>
            <textarea
              bind:value={description}
              rows="3"
              class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent resize-none text-sm disabled:opacity-50"
              placeholder="What's this team about?"
              disabled={loading}
            ></textarea>
          </div>

          <!-- Actions -->
          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              on:click={handleClose}
              disabled={loading}
              class="px-4 py-2 text-sm font-medium text-text-2 bg-bg-surface-2 rounded-lg hover:bg-bg-surface-1 border border-border-2 transition-colors disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              class="px-4 py-2 text-sm font-medium text-brand-foreground bg-brand rounded-lg hover:bg-brand-hover transition-colors disabled:opacity-50"
            >
              {loading ? 'Creating...' : 'Create Team'}
            </button>
          </div>
        </form>
      {/if}
    </div>
  </div>
{/if}

// frontend/src/components/modals/CreateTeamModal.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { X } from 'lucide-vue-next';
import { useTeamStore } from '../../features/teams/stores/teamStore';
import { useAuthStore } from '../../features/auth/stores/authStore';
import { canCreateTeam as canCreateTeamForRole } from '../../features/permissions/capabilities';
import BaseButton from '../atomic/BaseButton.vue';
import BaseInput from '../atomic/BaseInput.vue';
import { getApiErrorMessage } from '@/core/errors/errorUtils';

const props = defineProps<{
    show: boolean
}>();

const emit = defineEmits<{
    (e: 'close'): void
}>();

const teamStore = useTeamStore();
const authStore = useAuthStore();

const name = ref('');
const displayName = ref('');
const description = ref('');
const loading = ref(false);
const error = ref('');
const canCreateTeam = computed(() => canCreateTeamForRole(authStore.user?.role));

async function handleSubmit() {
    if (!canCreateTeam.value) {
        error.value = 'You do not have permission to create teams';
        return;
    }

    if (!name.value.trim()) {
        error.value = 'Team name is required';
        return;
    }

    loading.value = true;
    error.value = '';

    try {
        await teamStore.createTeam({
            name: name.value.trim().toLowerCase().replace(/\s+/g, '-'),
            display_name: displayName.value.trim() || name.value.trim(),
            description: description.value.trim() || undefined,
        });
        
        // Reset and close
        name.value = '';
        displayName.value = '';
        description.value = '';
        emit('close');
    } catch (e: unknown) {
        error.value = getApiErrorMessage(e) || 'Failed to create team';
    } finally {
        loading.value = false;
    }
}

function handleClose() {
    name.value = '';
    displayName.value = '';
    description.value = '';
    error.value = '';
    emit('close');
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center">
      <!-- Backdrop -->
      <div class="absolute inset-0 bg-black/50" @click="handleClose"></div>
      
      <!-- Modal -->
      <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 overflow-hidden">
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 class="text-xl font-bold text-gray-900">Create Team</h2>
          <button @click="handleClose" class="p-1 hover:bg-gray-100 rounded-lg transition-colors">
            <X class="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <div v-if="!canCreateTeam" class="p-6 space-y-4">
          <div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
            You do not have permission to create teams.
          </div>

          <div class="flex justify-end pt-2">
            <BaseButton variant="secondary" @click="handleClose">
              Close
            </BaseButton>
          </div>
        </div>

        <!-- Form -->
        <form v-else @submit.prevent="handleSubmit" class="p-6 space-y-4">
          <!-- Error -->
          <div v-if="error" class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
            {{ error }}
          </div>

          <BaseInput
            v-model="name"
            label="Team Name"
            placeholder="e.g., engineering"
            :disabled="loading"
            required
          />

          <BaseInput
            v-model="displayName"
            label="Display Name"
            placeholder="e.g., Engineering Team"
            :disabled="loading"
          />

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">
              Description
            </label>
            <textarea
              v-model="description"
              rows="3"
              class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-white text-gray-900 focus:ring-2 focus:ring-primary focus:border-transparent resize-none"
              placeholder="What's this team about?"
              :disabled="loading"
            ></textarea>
          </div>

          <!-- Actions -->
          <div class="flex justify-end space-x-3 pt-4">
            <BaseButton variant="secondary" @click="handleClose" :disabled="loading">
              Cancel
            </BaseButton>
            <BaseButton type="submit" :loading="loading">
              Create Team
            </BaseButton>
          </div>
        </form>
      </div>
    </div>
  </Teleport>
</template>
