// frontend/src/svelte/components/modals/EditProfileModal.svelte
<script lang="ts">
  import { createEventDispatcher, untrack } from 'svelte'
  import { X, Camera } from 'lucide-svelte'
  import { svelteApi, SvelteHttpError } from '../../stores/http'
  import { authStore } from '../../stores/auth'
  import type { AuthUser } from '../../../core/entities/Auth'

  interface Props {
    open?: boolean
  }

  let { open = false }: Props = $props()

  const dispatch = createEventDispatcher<{ close: void }>()

  let username = $state('')
  let firstName = $state('')
  let lastName = $state('')
  let displayName = $state('')
  let nickname = $state('')
  let position = $state('')
  let avatarUrl = $state('')
  let loading = $state(false)
  let error = $state('')
  let success = $state('')

  const currentUser = $derived($authStore.user)

  // Full name preview
  const fullNamePreview = $derived((() => {
    const first = firstName.trim()
    const last = lastName.trim()
    if (first || last) return `${first} ${last}`.trim()
    return displayName.trim() || nickname.trim() || username
  })())

  // Populate form when modal opens
  $effect(() => {
    if (open) {
      const user = untrack(() => $authStore.user)
      if (user) {
        username = user.username || ''
        firstName = user.firstName || user.first_name || ''
        lastName = user.lastName || user.last_name || ''
        displayName = user.displayName || user.display_name || ''
        nickname = user.nickname || ''
        position = user.position || ''
        avatarUrl = user.avatarUrl || user.avatar_url || ''
        error = ''
        success = ''
      }
    }
  })

  function getInitials(name: string) {
    return name
      .split(' ')
      .map((n) => n[0])
      .filter(Boolean)
      .join('')
      .toUpperCase()
      .slice(0, 2)
  }

  async function handleSubmit(event: Event) {
    event.preventDefault()

    if (!currentUser) return

    loading = true
    error = ''
    success = ''

    try {
      await svelteApi.put<AuthUser>('/users/me', {
        username: username.trim() || undefined,
        first_name: firstName.trim() || undefined,
        last_name: lastName.trim() || undefined,
        display_name: displayName.trim() || undefined,
        nickname: nickname.trim() || undefined,
        position: position.trim() || undefined,
        avatar_url: avatarUrl.trim() || undefined,
      })

      // Update local user state
      await authStore.fetchMe()
      success = 'Profile updated successfully!'

      setTimeout(() => {
        dispatch('close')
      }, 1000)
    } catch (e: unknown) {
      if (e instanceof SvelteHttpError && e.data && typeof e.data === 'object' && 'message' in e.data) {
        error = String(e.data.message)
      } else if (e instanceof Error) {
        error = e.message
      } else {
        error = 'Failed to update profile'
      }
    } finally {
      loading = false
    }
  }

  function handleClose() {
    error = ''
    success = ''
    dispatch('close')
  }
</script>

<svelte:window on:keydown={(e) => open && e.key === 'Escape' && handleClose()} />

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4"
    data-testid="edit-profile-modal"
    role="dialog"
    aria-modal="true"
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/60 backdrop-blur-sm"
      on:click={handleClose}
      role="button"
      tabindex="-1"
      aria-label="Close edit profile modal"
    ></div>

    <!-- Modal -->
    <div
      class="relative bg-bg-surface-1 rounded-r-3 shadow-2xl ring-1 ring-border-1 w-full max-w-md overflow-hidden max-h-[90vh] overflow-y-auto"
    >
      <!-- Header -->
      <div class="flex items-center justify-between px-6 py-4 border-b border-border-1">
        <h2 class="text-lg font-semibold text-text-1">Edit Profile</h2>
        <button
          type="button"
          on:click={handleClose}
          class="flex h-10 w-10 items-center justify-center rounded-r-2 text-text-3 hover:text-text-1 hover:bg-bg-surface-2 transition-standard focus-ring"
          aria-label="Close"
        >
          <X class="h-5 w-5" />
        </button>
      </div>

      <!-- Form -->
      <form on:submit={handleSubmit} class="p-6 space-y-5">
        <!-- Avatar Preview -->
        <div class="flex justify-center">
          <div class="relative">
            <div class="flex h-24 w-24 items-center justify-center overflow-hidden rounded-full bg-brand text-3xl font-bold text-brand-foreground">
              {#if avatarUrl}
                <img src={avatarUrl} alt="Avatar" class="w-full h-full object-cover" />
              {:else}
                {getInitials(fullNamePreview || username || 'U')}
              {/if}
            </div>
            <button
              type="button"
              class="absolute bottom-0 right-0 w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center border-2 border-white"
            >
              <Camera class="w-4 h-4 text-white" />
            </button>
          </div>
        </div>

        <!-- Full Name Preview -->
        <div class="text-center">
          <p class="text-lg font-semibold text-text-1">{fullNamePreview}</p>
          <p class="text-sm text-text-3">@{username}</p>
        </div>

        <!-- Error/Success Messages -->
        {#if error}
          <div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
            {error}
          </div>
        {/if}
        {#if success}
          <div class="p-3 bg-green-50 border border-green-200 rounded-lg text-green-600 text-sm">
            {success}
          </div>
        {/if}

        <!-- Name Fields -->
        <div class="space-y-1">
          <label class="block text-xs font-semibold text-text-3 uppercase tracking-wider">Full Name</label>
          <div class="grid grid-cols-2 gap-3">
            <div>
              <label class="block text-sm font-medium text-text-2 mb-1">First Name</label>
              <input
                type="text"
                bind:value={firstName}
                placeholder="John"
                disabled={loading}
                class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-text-2 mb-1">Last Name</label>
              <input
                type="text"
                bind:value={lastName}
                placeholder="Doe"
                disabled={loading}
                class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
              />
            </div>
          </div>
        </div>

        <!-- Display Name -->
        <div>
          <label class="block text-sm font-medium text-text-2 mb-1">Display Name</label>
          <input
            type="text"
            bind:value={displayName}
            placeholder="How you want to be called"
            disabled={loading}
            class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
          />
        </div>

        <!-- Nickname -->
        <div>
          <label class="block text-sm font-medium text-text-2 mb-1">Nickname</label>
          <input
            type="text"
            bind:value={nickname}
            placeholder="Your preferred name"
            disabled={loading}
            class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
          />
        </div>

        <!-- Position -->
        <div>
          <label class="block text-sm font-medium text-text-2 mb-1">Position / Job Title</label>
          <input
            type="text"
            bind:value={position}
            placeholder="e.g. Software Engineer"
            disabled={loading}
            class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
          />
        </div>

        <!-- Username -->
        <div>
          <label class="block text-sm font-medium text-text-2 mb-1">Username</label>
          <input
            type="text"
            bind:value={username}
            placeholder="your_username"
            disabled={loading}
            class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
          />
        </div>

        <!-- Avatar URL -->
        <div>
          <label class="block text-sm font-medium text-text-2 mb-1">Avatar URL</label>
          <input
            type="text"
            bind:value={avatarUrl}
            placeholder="https://example.com/avatar.jpg"
            disabled={loading}
            class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1 focus:ring-2 focus:ring-brand focus:border-transparent text-sm disabled:opacity-50"
          />
        </div>

        <!-- Email (read-only) -->
        <div class="space-y-1">
          <label class="block text-sm font-medium text-text-2">Email</label>
          <div class="px-3 py-2 bg-bg-surface-2 rounded-lg text-text-3 text-sm">
            {currentUser?.email ?? ''}
          </div>
        </div>

        <!-- Actions -->
        <div class="flex justify-end space-x-3 pt-4">
          <button
            type="button"
            on:click={handleClose}
            disabled={loading}
            class="px-4 py-2 text-sm font-medium text-text-2 bg-bg-surface-2 rounded-lg hover:bg-bg-surface-1 border border-border-2 transition-colors disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={loading}
            class="px-4 py-2 text-sm font-medium text-brand-foreground bg-brand rounded-lg hover:bg-brand-hover transition-colors disabled:opacity-50"
          >
            {loading ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

// frontend/src/components/modals/EditProfileModal.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { X, User, Camera } from 'lucide-vue-next'
import { useAuthStore } from '../../features/auth/stores/authStore'
import type { AuthUser } from '../../core/entities/Auth'
import { usersApi } from '../../api/users'
import BaseButton from '../atomic/BaseButton.vue'
import BaseInput from '../atomic/BaseInput.vue'
import { getApiErrorMessage } from '@/core/errors/errorUtils'

const props = defineProps<{
  show: boolean
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

const authStore = useAuthStore()

const username = ref('')
const firstName = ref('')
const lastName = ref('')
const displayName = ref('')
const nickname = ref('')
const position = ref('')
const avatarUrl = ref('')
const loading = ref(false)
const error = ref('')
const success = ref('')

const currentUser = computed(() => authStore.user)

// Full name preview
const fullNamePreview = computed(() => {
  const first = firstName.value.trim()
  const last = lastName.value.trim()
  if (first || last) return `${first} ${last}`.trim()
  return displayName.value.trim() || nickname.value.trim() || username.value
})

// Populate form when modal opens
watch(
  () => props.show,
  isOpen => {
    if (isOpen && currentUser.value) {
      username.value = currentUser.value.username || ''
      firstName.value = currentUser.value.firstName || ''
      lastName.value = currentUser.value.lastName || ''
      displayName.value = currentUser.value.displayName || ''
      nickname.value = currentUser.value.nickname || ''
      position.value = currentUser.value.position || ''
      avatarUrl.value = currentUser.value.avatarUrl || ''
      error.value = ''
      success.value = ''
    }
  }
)

async function handleSubmit() {
  if (!currentUser.value) return

  loading.value = true
  error.value = ''
  success.value = ''

  try {
    const response = await usersApi.update(currentUser.value.id, {
      username: username.value.trim() || undefined,
      first_name: firstName.value.trim() || undefined,
      last_name: lastName.value.trim() || undefined,
      display_name: displayName.value.trim() || undefined,
      nickname: nickname.value.trim() || undefined,
      position: position.value.trim() || undefined,
      avatar_url: avatarUrl.value.trim() || undefined,
    })

    // Update local user state
    authStore.user = response.data as unknown as AuthUser
    success.value = 'Profile updated successfully!'

    setTimeout(() => {
      emit('close')
    }, 1000)
  } catch (e: unknown) {
    error.value = getApiErrorMessage(e) || 'Failed to update profile'
  } finally {
    loading.value = false
  }
}

function handleClose() {
  error.value = ''
  success.value = ''
  emit('close')
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center">
      <!-- Backdrop -->
      <div class="absolute inset-0 bg-black/50" @click="handleClose"></div>

      <!-- Modal -->
      <div
        class="relative bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 overflow-hidden max-h-[90vh] overflow-y-auto"
      >
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 class="text-xl font-bold text-gray-900">Edit Profile</h2>
          <button class="p-1 hover:bg-gray-100 rounded-lg transition-colors" @click="handleClose">
            <X class="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <!-- Form -->
        <form class="p-6 space-y-5" @submit.prevent="handleSubmit">
          <!-- Avatar Preview -->
          <div class="flex justify-center">
            <div class="relative">
              <div
                class="flex h-24 w-24 items-center justify-center overflow-hidden rounded-full bg-primary text-3xl font-bold text-brand-foreground"
              >
                <img
                  v-if="avatarUrl"
                  :src="avatarUrl"
                  alt="Avatar"
                  class="w-full h-full object-cover"
                />
                <User v-else class="w-12 h-12" />
              </div>
              <button
                type="button"
                class="absolute bottom-0 right-0 w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center border-2 border-white"
              >
                <Camera class="w-4 h-4 text-white" />
              </button>
            </div>
          </div>

          <!-- Full Name Preview -->
          <div class="text-center">
            <p class="text-lg font-semibold text-gray-900">{{ fullNamePreview }}</p>
            <p class="text-sm text-gray-500">@{{ username }}</p>
          </div>

          <!-- Error/Success Messages -->
          <div
            v-if="error"
            class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm"
          >
            {{ error }}
          </div>
          <div
            v-if="success"
            class="p-3 bg-green-50 border border-green-200 rounded-lg text-green-600 text-sm"
          >
            {{ success }}
          </div>

          <!-- Name Fields -->
          <div class="space-y-1">
            <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wider"
              >Full Name</label
            >
            <div class="grid grid-cols-2 gap-3">
              <BaseInput
                v-model="firstName"
                label="First Name"
                placeholder="John"
                :disabled="loading"
              />
              <BaseInput
                v-model="lastName"
                label="Last Name"
                placeholder="Doe"
                :disabled="loading"
              />
            </div>
          </div>

          <BaseInput
            v-model="displayName"
            label="Display Name"
            placeholder="How you want to be called"
            :disabled="loading"
          />

          <BaseInput
            v-model="nickname"
            label="Nickname"
            placeholder="Your preferred name"
            :disabled="loading"
          />

          <BaseInput
            v-model="position"
            label="Position / Job Title"
            placeholder="e.g. Software Engineer"
            :disabled="loading"
          />

          <BaseInput
            v-model="username"
            label="Username"
            placeholder="your_username"
            :disabled="loading"
          />

          <BaseInput
            v-model="avatarUrl"
            label="Avatar URL"
            placeholder="https://example.com/avatar.jpg"
            :disabled="loading"
          />

          <!-- Email (read-only) -->
          <div class="space-y-1">
            <label class="block text-sm font-medium text-gray-700"> Email </label>
            <div class="px-3 py-2 bg-gray-100 rounded-lg text-gray-600 text-sm">
              {{ currentUser?.email }}
            </div>
          </div>

          <!-- Actions -->
          <div class="flex justify-end space-x-3 pt-4">
            <BaseButton variant="secondary" :disabled="loading" @click="handleClose">
              Cancel
            </BaseButton>
            <BaseButton type="submit" :loading="loading"> Save Changes </BaseButton>
          </div>
        </form>
      </div>
    </div>
  </Teleport>
</template>
