// frontend/src/svelte/components/search/SearchModal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { Search, X, Hash, Clock, MessageSquare } from 'lucide-svelte'
  import { format } from 'date-fns'
  import { searchStore, type SearchFilter } from '../../stores/search'
  import { chatStore } from '../../stores/chat'

  export let open = false

  const dispatch = createEventDispatcher<{ close: void }>()

  const filters: SearchFilter[] = ['messages', 'files', 'channels', 'users']
  const filterLabels: Record<SearchFilter, string> = {
    messages: 'Messages',
    files: 'Files',
    channels: 'Channels',
    users: 'Users',
  }

  let query = ''

  $: if (!open) {
    query = ''
    searchStore.clearSearch()
  }

  function handleClose() {
    query = ''
    searchStore.clearSearch()
    dispatch('close')
  }

  function handleFilterClick(filter: SearchFilter) {
    searchStore.performSearch(query, filter)
  }

  function getChannelName(channelId: string): string {
    const channel = $chatStore.channels.find((c) => c.id === channelId)
    return channel?.display_name || channel?.name || 'Unknown'
  }

  function handleResultClick() {
    dispatch('close')
  }

  function handleRecentClick(search: string) {
    query = search
    searchStore.performSearch(search, $searchStore.filter)
  }

  function onInput() {
    searchStore.performSearch(query, $searchStore.filter)
  }
</script>

<svelte:window
  on:keydown={(e) => {
    if (open && e.key === 'Escape') {
      e.preventDefault()
      handleClose()
    }
  }}
/>

{#if open}
  <div class="fixed inset-0 z-50 flex items-start justify-center pt-[10vh]" data-testid="search-modal">
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/50"
      on:click={handleClose}
      on:keydown={(e) => e.key === 'Escape' && handleClose()}
      role="button"
      tabindex="-1"
      aria-label="Close search"
    ></div>

    <!-- Modal -->
    <div class="relative mx-4 w-full max-w-2xl overflow-hidden rounded-xl bg-white shadow-2xl">
      <!-- Search Input -->
      <div class="flex items-center border-b border-gray-200 px-4 py-3">
        <Search class="mr-3 h-5 w-5 text-gray-400" />
        <input
          bind:value={query}
          on:input={onInput}
          type="text"
          placeholder="Search messages, files, and more..."
          class="flex-1 bg-transparent text-lg text-gray-900 placeholder-gray-400 outline-none"
          data-testid="search-input"
          autofocus
        />
        <div class="flex items-center space-x-2">
          <kbd class="hidden rounded bg-gray-100 px-2 py-1 text-xs text-gray-500 sm:block">ESC</kbd>
          <button on:click={handleClose} class="rounded p-1 hover:bg-gray-100">
            <X class="h-5 w-5 text-gray-400" />
          </button>
        </div>
      </div>

      <!-- Filter Tabs -->
      <div class="flex border-b border-gray-200 px-4">
        {#each filters as filter}
          <button
            class="px-3 py-2 text-sm font-medium capitalize transition-colors"
            class:text-brand={$searchStore.filter === filter}
            class:border-b-2={$searchStore.filter === filter}
            class:border-brand={$searchStore.filter === filter}
            class:text-gray-500={$searchStore.filter !== filter}
            class:hover:text-gray-700={$searchStore.filter !== filter}
            on:click={() => handleFilterClick(filter)}
          >
            {filterLabels[filter]}
          </button>
        {/each}
      </div>

      <!-- Results Area -->
      <div class="max-h-[60vh] overflow-y-auto">
        {#if $searchStore.loading}
          <div class="p-8 text-center text-gray-500">
            <div class="mx-auto h-8 w-8 animate-spin rounded-full border-2 border-brand border-t-transparent"></div>
            <p class="mt-2">Searching...</p>
          </div>
        {:else if $searchStore.error}
          <div class="p-8 text-center text-red-500">
            {$searchStore.error}
          </div>
        {:else if $searchStore.results.length > 0}
          <div class="py-2">
            <div class="px-4 py-2 text-xs font-semibold uppercase text-gray-500">
              {$searchStore.results.length} Results
            </div>
            {#each $searchStore.results as result (result.id)}
              <div
                on:click={handleResultClick}
                on:keydown={(e) => e.key === 'Enter' && handleResultClick()}
                class="cursor-pointer border-b border-gray-100 px-4 py-3 last:border-0 hover:bg-gray-50"
                role="button"
                tabindex="0"
              >
                <div class="mb-1 flex items-center space-x-2 text-xs text-gray-500">
                  <Hash class="h-3 w-3" />
                  <span>{getChannelName(result.channel_id)}</span>
                  <span>•</span>
                  <Clock class="h-3 w-3" />
                  <span>{format(new Date(result.created_at), 'MMM d, yyyy')}</span>
                </div>
                <div class="line-clamp-2 text-sm text-gray-900">
                  {result.message}
                </div>
                {#if result.username}
                  <div class="mt-1 text-xs text-gray-400">
                    @{result.username}
                  </div>
                {/if}
              </div>
            {/each}
          </div>
        {:else if query.trim().length >= 2 && !$searchStore.loading}
          <div class="p-8 text-center text-gray-500">
            <MessageSquare class="mx-auto mb-3 h-12 w-12 opacity-50" />
            <p>No results found for "{query}"</p>
          </div>
        {:else}
          <div class="p-4">
            {#if $searchStore.recentSearches.length > 0}
              <div class="mb-2 text-xs font-semibold uppercase text-gray-500">Recent Searches</div>
              <div class="space-y-1">
                {#each $searchStore.recentSearches as search}
                  <button
                    on:click={() => handleRecentClick(search)}
                    class="flex w-full items-center rounded-lg px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"
                  >
                    <Clock class="mr-2 h-4 w-4 text-gray-400" />
                    {search}
                  </button>
                {/each}
              </div>
            {:else}
              <div class="py-6 text-center text-gray-500">
                <Search class="mx-auto mb-3 h-12 w-12 opacity-50" />
                <p>Start typing to search messages</p>
              </div>
            {/if}
          </div>
        {/if}
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-between border-t border-gray-200 bg-gray-50 px-4 py-2 text-xs text-gray-500">
        <span>Search powered by PostgreSQL full-text search</span>
        <span>↵ to select</span>
      </div>
    </div>
  </div>
{/if}

<style>
  .line-clamp-2 {
    display: -webkit-box;
    line-clamp: 2;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
</style>

// frontend/src/components/modals/SearchModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { X, Search, Hash, Clock, MessageSquare } from 'lucide-vue-next'
import { format } from 'date-fns'
import { searchApi, type SearchResult } from '../../api/search'
import { useChannelStore } from '../../features/channels/stores/channelStore'
import { getApiErrorMessage } from '@/core/errors/errorUtils'

const props = defineProps<{
    show: boolean
}>()

const emit = defineEmits<{
    (e: 'close'): void
    (e: 'navigate', channelId: string, postId: string): void
}>()

const channelStore = useChannelStore()

const query = ref('')
const results = ref<SearchResult | null>(null)
const loading = ref(false)
const error = ref('')
const recentSearches = ref<string[]>([])

// Debounced search
let searchTimeout: ReturnType<typeof setTimeout> | null = null

watch(query, (newQuery) => {
    if (searchTimeout) {
        clearTimeout(searchTimeout)
    }
    
    if (newQuery.trim().length < 2) {
        results.value = null
        return
    }
    
    searchTimeout = setTimeout(() => {
        performSearch()
    }, 300)
})

async function performSearch() {
    if (query.value.trim().length < 2) return
    
    loading.value = true
    error.value = ''
    
    try {
        const response = await searchApi.search({
            q: query.value.trim(),
            per_page: 20,
        })
        results.value = response.data
        
        // Save to recent searches
        const search = query.value.trim()
        if (!recentSearches.value.includes(search)) {
            recentSearches.value = [search, ...recentSearches.value.slice(0, 4)]
        }
    } catch (e: unknown) {
        error.value = getApiErrorMessage(e) || 'Search failed'
    } finally {
        loading.value = false
    }
}

function handleResultClick(channelId: string, postId: string) {
    emit('navigate', channelId, postId)
    emit('close')
}

function handleRecentClick(search: string) {
    query.value = search
    performSearch()
}

function handleClose() {
    query.value = ''
    results.value = null
    error.value = ''
    emit('close')
}

function getChannelName(channelId: string): string {
    const channel = channelStore.channels.find(c => c.id === channelId)
    return channel?.display_name || channel?.name || 'Unknown'
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="fixed inset-0 z-50 flex items-start justify-center pt-[10vh]">
      <!-- Backdrop -->
      <div class="absolute inset-0 bg-black/50" @click="handleClose"></div>
      
      <!-- Search Modal -->
      <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-2xl mx-4 overflow-hidden">
        <!-- Search Input -->
        <div class="flex items-center px-4 py-3 border-b border-gray-200">
          <Search class="w-5 h-5 text-gray-400 mr-3" />
          <input
            v-model="query"
            type="text"
            placeholder="Search messages, files, and more..."
            class="flex-1 bg-transparent text-lg text-gray-900 placeholder-gray-400 focus:outline-none"
            autofocus
          />
          <div class="flex items-center space-x-2">
            <kbd class="hidden sm:block px-2 py-1 text-xs bg-gray-100 text-gray-500 rounded">ESC</kbd>
            <button @click="handleClose" class="p-1 hover:bg-gray-100 rounded">
              <X class="w-5 h-5 text-gray-400" />
            </button>
          </div>
        </div>

        <!-- Results Area -->
        <div class="max-h-[60vh] overflow-y-auto">
          <!-- Loading -->
          <div v-if="loading" class="p-8 text-center text-gray-500">
            <div class="animate-spin w-8 h-8 border-2 border-primary border-t-transparent rounded-full mx-auto"></div>
            <p class="mt-2">Searching...</p>
          </div>

          <!-- Error -->
          <div v-else-if="error" class="p-8 text-center text-red-500">
            {{ error }}
          </div>

          <!-- Results -->
          <div v-else-if="results && results.posts.length > 0" class="py-2">
            <div class="px-4 py-2 text-xs font-semibold text-gray-500 uppercase">
              {{ results.total }} Results
            </div>
            <div 
              v-for="post in results.posts"
              :key="post.id"
              @click="handleResultClick(post.channel_id, post.id)"
              class="px-4 py-3 hover:bg-gray-50 cursor-pointer border-b border-gray-100 last:border-0"
            >
              <div class="flex items-center space-x-2 text-xs text-gray-500 mb-1">
                <Hash class="w-3 h-3" />
                <span>{{ getChannelName(post.channel_id) }}</span>
                <span>•</span>
                <Clock class="w-3 h-3" />
                <span>{{ format(new Date(post.created_at), 'MMM d, yyyy') }}</span>
              </div>
              <div class="text-sm text-gray-900 line-clamp-2">
                {{ post.message }}
              </div>
            </div>
          </div>

          <!-- No Results -->
          <div v-else-if="results && results.posts.length === 0" class="p-8 text-center text-gray-500">
            <MessageSquare class="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p>No results found for "{{ query }}"</p>
          </div>

          <!-- Empty State / Recent Searches -->
          <div v-else class="p-4">
            <div v-if="recentSearches.length > 0">
              <div class="text-xs font-semibold text-gray-500 uppercase mb-2">Recent Searches</div>
              <div class="space-y-1">
                <button
                  v-for="search in recentSearches"
                  :key="search"
                  @click="handleRecentClick(search)"
                  class="flex items-center w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-lg"
                >
                  <Clock class="w-4 h-4 mr-2 text-gray-400" />
                  {{ search }}
                </button>
              </div>
            </div>
            <div v-else class="text-center text-gray-500 py-6">
              <Search class="w-12 h-12 mx-auto mb-3 opacity-50" />
              <p>Start typing to search messages</p>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="px-4 py-2 border-t border-gray-200 bg-gray-50 text-xs text-gray-500 flex items-center justify-between">
          <span>Search powered by PostgreSQL full-text search</span>
          <span>↵ to select</span>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
