// frontend/src/components/ui/CommandPalette.vue
<script setup lang="ts">
import { log } from '@/utils/log'
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Search, Hash, User } from 'lucide-vue-next'

const isOpen = ref(false)
const searchQuery = ref('')
const selectedIndex = ref(0)
const inputRef = ref<HTMLInputElement | null>(null)
const router = useRouter()

// Placeholder data - replace with store/API later
const items = [
  { id: '1', type: 'channel', name: 'general', group: 'Channels' },
  { id: '2', type: 'channel', name: 'random', group: 'Channels' },
  { id: '3', type: 'channel', name: 'devops', group: 'Channels' },
  { id: '4', type: 'user', name: 'Alice', group: 'Direct Messages' },
  { id: '5', type: 'user', name: 'Bob', group: 'Direct Messages' },
]

const filteredItems = computed(() => {
  if (!searchQuery.value) return items.slice(0, 5) // Recent
  return items.filter(item => item.name.toLowerCase().includes(searchQuery.value.toLowerCase()))
})

function open() {
  isOpen.value = true
  searchQuery.value = ''
  selectedIndex.value = 0
  setTimeout(() => inputRef.value?.focus(), 50)
}

function close() {
  isOpen.value = false
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'k' && (e.metaKey || e.ctrlKey)) {
    e.preventDefault()
    if (isOpen.value) close()
    else open()
  } else if (e.key === 'Escape' && isOpen.value) {
    close()
  } else if (isOpen.value) {
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      selectedIndex.value = (selectedIndex.value + 1) % filteredItems.value.length
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      selectedIndex.value =
        (selectedIndex.value - 1 + filteredItems.value.length) % filteredItems.value.length
    } else if (e.key === 'Enter') {
      e.preventDefault()
      selectItem(filteredItems.value[selectedIndex.value])
    }
  }
}

function selectItem(item: any) {
  log.debug('Selected:', item)
  if (item.type === 'channel') {
    router.push(`/channels/${item.id}`)
  }
  // Navigate
  close()
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onUnmounted(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 z-50 overflow-y-auto p-4 sm:p-6 md:p-20"
    role="dialog"
    @click="close"
  >
    <!-- Backdrop -->
    <div class="fixed inset-0 bg-black/25 transition-opacity backdrop-blur-sm"></div>

    <!-- Modal -->
    <div
      class="mx-auto max-w-xl transform divide-y divide-border-1 overflow-hidden rounded-xl bg-bg-surface-1 shadow-2xl ring-1 ring-text-1/5 transition-all"
      @click.stop
    >
      <div class="relative">
        <Search class="pointer-events-none absolute top-3.5 left-4 h-5 w-5 text-text-4" />
        <input
          ref="inputRef"
          v-model="searchQuery"
          type="text"
          class="h-12 w-full border-0 bg-transparent pl-11 pr-4 text-text-1 placeholder-text-4 focus:ring-0 sm:text-sm"
          placeholder="Search items..."
        />
      </div>

      <div v-if="filteredItems.length > 0" class="max-h-96 scroll-py-3 overflow-y-auto p-3">
        <div v-for="(item, index) in filteredItems" :key="item.id">
          <!-- Group Header (Optional logic needed) -->

          <div
            class="group flex cursor-default select-none rounded-xl p-3"
            :class="selectedIndex === index ? 'bg-bg-surface-2' : ''"
            @click="selectItem(item)"
            @mouseenter="selectedIndex = index"
          >
            <div
              class="flex h-10 w-10 flex-none items-center justify-center rounded-lg"
              :class="selectedIndex === index ? 'bg-bg-surface-1' : 'bg-bg-surface-2'"
            >
              <Hash v-if="item.type === 'channel'" class="h-6 w-6 text-text-3" />
              <User v-else class="h-6 w-6 text-text-3" />
            </div>
            <div class="ml-4 flex-auto">
              <p
                class="text-sm font-medium text-text-2"
                :class="selectedIndex === index ? 'text-text-1' : ''"
              >
                {{ item.name }}
              </p>
              <p class="text-sm text-text-3">
                {{ item.group }}
              </p>
            </div>
          </div>
        </div>
      </div>

      <div v-else class="py-14 px-6 text-center text-sm sm:px-14">
        <p class="mt-4 font-semibold text-text-1">No results found</p>
        <p class="mt-2 text-text-3">No components found for this search term. Please try again.</p>
      </div>
    </div>
  </div>
</template>

// frontend/src/svelte/components/ui/CommandPalette.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import {
    Search,
    Hash,
    User,
    Settings,
    LogOut,
    HelpCircle,
    Bell,
    FileText,
  } from 'lucide-svelte'

  type CommandIconType =
    | 'channel'
    | 'user'
    | 'settings'
    | 'logout'
    | 'search'
    | 'help'
    | 'notifications'
    | 'file'

  interface Command {
    id: string
    name: string
    group: string
    iconType?: CommandIconType
    keywords?: string[]
  }

  interface Props {
    open?: boolean
    commands?: Command[]
    previewLimit?: number
  }

  const fallbackCommands: Command[] = [
    { id: 'settings', name: 'Settings', group: 'Actions', iconType: 'settings' },
    { id: 'search', name: 'Search', group: 'Actions', iconType: 'search' },
    { id: 'notifications', name: 'Notifications', group: 'Actions', iconType: 'notifications' },
    { id: 'help', name: 'Help & Support', group: 'Actions', iconType: 'help' },
  ]

  let { open = false, commands = fallbackCommands, previewLimit = 6 }: Props = $props()

  const dispatch = createEventDispatcher<{
    close: void
    select: string
  }>()

  let searchQuery = $state('')
  let selectedIndex = $state(0)
  let inputRef = $state<HTMLInputElement | null>(null)

  const filteredCommands = $derived(
    searchQuery.trim()
      ? commands.filter((c) =>
          [c.name, c.group, ...(c.keywords ?? [])].some((value) =>
            value.toLowerCase().includes(searchQuery.toLowerCase())
          )
        )
      : commands.slice(0, previewLimit)
  )

  $effect(() => {
    if (open) {
      searchQuery = ''
      selectedIndex = 0
      requestAnimationFrame(() => inputRef?.focus())
    }
  })

  $effect(() => {
    if (selectedIndex >= filteredCommands.length) {
      selectedIndex = Math.max(0, filteredCommands.length - 1)
    }
  })

  function handleClose() {
    dispatch('close')
  }

  function handleSelect(commandId: string) {
    dispatch('select', commandId)
    dispatch('close')
  }

  function handleKeydown(e: KeyboardEvent) {
    const items = filteredCommands
    if (!items.length) {
      if (e.key === 'Escape') {
        e.preventDefault()
        handleClose()
      }
      return
    }

    switch (e.key) {
      case 'Escape':
        e.preventDefault()
        handleClose()
        break
      case 'ArrowDown':
        e.preventDefault()
        selectedIndex = (selectedIndex + 1) % items.length
        break
      case 'ArrowUp':
        e.preventDefault()
        selectedIndex = (selectedIndex - 1 + items.length) % items.length
        break
      case 'Enter':
        e.preventDefault()
        if (items[selectedIndex]) {
          handleSelect(items[selectedIndex].id)
        }
        break
    }
  }

  const iconMap: Record<CommandIconType, typeof Hash> = {
    channel: Hash,
    user: User,
    settings: Settings,
    logout: LogOut,
    search: Search,
    help: HelpCircle,
    notifications: Bell,
    file: FileText,
  }

  function getIconComponent(iconType: Command['iconType'] = 'search'): typeof Hash {
    return iconMap[iconType] ?? Search
  }
</script>

<svelte:window onkeydown={(e) => open && e.key === 'Escape' && handleClose()} />

{#if open}
  <div
    class="fixed inset-0 z-50 overflow-y-auto p-4 sm:p-6 md:p-20"
    role="dialog"
    aria-modal="true"
    data-testid="command-palette"
    tabindex="-1"
    onclick={handleClose}
    onkeydown={(e) => e.key === 'Escape' && handleClose()}
  >
    <!-- Backdrop -->
    <div class="fixed inset-0 bg-black/25 backdrop-blur-sm transition-opacity"></div>

    <!-- Modal -->
    <div
      class="relative mx-auto max-w-xl transform divide-y divide-border-1 overflow-hidden rounded-xl bg-bg-surface-1 shadow-2xl ring-1 ring-text-1/5 transition-all"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.key === 'Escape' && handleClose()}
      role="document"
      tabindex="-1"
    >
      <div class="relative">
        <Search class="pointer-events-none absolute top-3.5 left-4 h-5 w-5 text-text-4" />
        <input
          bind:this={inputRef}
          type="text"
          class="h-12 w-full border-0 bg-transparent pl-11 pr-4 text-text-1 placeholder-text-4 focus:ring-0 sm:text-sm"
          placeholder="Search commands..."
          bind:value={searchQuery}
          onkeydown={handleKeydown}
        />
      </div>

      {#if filteredCommands.length > 0}
        <div class="max-h-96 scroll-py-3 overflow-y-auto p-3">
          {#each filteredCommands as item, index (item.id)}
            <button
              type="button"
              onclick={() => handleSelect(item.id)}
              onmouseenter={() => (selectedIndex = index)}
              class="group flex w-full cursor-default select-none rounded-xl p-3 text-left"
              class:bg-bg-surface-2={selectedIndex === index}
              aria-label={`Select ${item.name}`}
            >
              <div
                class="flex h-10 w-10 flex-none items-center justify-center rounded-lg"
                class:bg-bg-surface-1={selectedIndex === index}
                class:bg-bg-surface-2={selectedIndex !== index}
              >
                <svelte:component this={getIconComponent(item.iconType)} class="h-6 w-6 text-text-3" />
              </div>
              <div class="ml-4 flex-auto">
                <p
                  class="text-sm font-medium"
                  class:text-text-1={selectedIndex === index}
                  class:text-text-2={selectedIndex !== index}
                >
                  {item.name}
                </p>
                <p class="text-sm text-text-3">{item.group}</p>
              </div>
            </button>
          {/each}
        </div>
      {:else}
        <div class="py-14 px-6 text-center text-sm sm:px-14">
          <p class="mt-4 font-semibold text-text-1">No results found</p>
          <p class="mt-2 text-text-3">
            No commands found for this search term. Please try again.
          </p>
        </div>
      {/if}
    </div>
  </div>
{/if}
