// frontend/src/views/main/PlaybooksView.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Plus, Book, Play, ArrowRight } from 'lucide-vue-next'
import { usePlaybookStore } from '../../features/playbooks/stores/playbookStore'
import ChannelSidebar from '../../components/layout/ChannelSidebar.vue'
import PlaybookList from '../../components/playbooks/PlaybookList.vue'
import BaseButton from '../../components/atomic/BaseButton.vue'

const router = useRouter()
const playbookStore = usePlaybookStore()
const activeTab = ref<'playbooks' | 'runs'>('playbooks')

onMounted(() => {
  playbookStore.fetchPlaybooks()
  playbookStore.fetchRuns()
})
</script>

<template>
  <div class="flex h-screen bg-white">
    <!-- Sidebar (Reusing ChannelSidebar for navigation consistency) -->
    <ChannelSidebar />

    <!-- Main Content -->
    <div class="flex-1 flex flex-col min-w-0 bg-gray-50">
      <!-- Header -->
      <header class="bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center">
        <div class="flex items-center space-x-4">
          <div class="p-2 bg-indigo-100 rounded-lg">
            <Book class="w-6 h-6 text-indigo-600" />
          </div>
          <div>
            <h1 class="text-xl font-bold text-gray-900">Playbooks</h1>
            <p class="text-sm text-gray-500">Automate your team's workflows</p>
          </div>
        </div>

        <BaseButton @click="router.push('/playbooks/new')">
          <Plus class="w-4 h-4 mr-2" />
          Create Playbook
        </BaseButton>
      </header>

      <!-- Tabs -->
      <div class="px-6 mt-4 border-b border-gray-200">
        <nav class="flex space-x-8">
          <button
            @click="activeTab = 'playbooks'"
            class="pb-4 border-b-2 font-medium text-sm transition-colors flex items-center"
            :class="
              activeTab === 'playbooks'
                ? 'border-indigo-500 text-indigo-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            "
          >
            <Book class="w-4 h-4 mr-2" />
            Library
          </button>
          <button
            @click="activeTab = 'runs'"
            class="pb-4 border-b-2 font-medium text-sm transition-colors flex items-center"
            :class="
              activeTab === 'runs'
                ? 'border-indigo-500 text-indigo-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            "
          >
            <Play class="w-4 h-4 mr-2" />
            Runs
          </button>
        </nav>
      </div>

      <!-- Content Area -->
      <div class="flex-1 overflow-y-auto p-6">
        <Transition
          enter-active-class="transition ease-out duration-100"
          enter-from-class="opacity-0 translate-y-1"
          enter-to-class="opacity-100 translate-y-0"
          leave-active-class="transition ease-in duration-75"
          leave-from-class="opacity-100 translate-y-0"
          leave-to-class="opacity-0 translate-y-1"
          mode="out-in"
        >
          <div v-if="activeTab === 'playbooks'" key="playbooks">
            <PlaybookList />
          </div>
          <div v-else key="runs">
            <div
              v-if="playbookStore.runs.length === 0"
              class="text-center py-20 bg-white rounded-lg border border-gray-200 border-dashed"
            >
              <Play class="w-12 h-12 text-gray-300 mx-auto mb-3" />
              <h3 class="text-lg font-medium text-gray-900">No active runs</h3>
              <p class="text-gray-500">Start a playbook run to track progress</p>
            </div>
            <div v-else class="grid grid-cols-1 gap-4">
              <div
                v-for="run in playbookStore.runs"
                :key="run.id"
                @click="router.push(`/runs/${run.id}`)"
                class="bg-white p-4 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-all cursor-pointer flex items-center justify-between group"
              >
                <div class="flex items-center space-x-4">
                  <div class="p-2 bg-blue-50 rounded-lg text-blue-600">
                    <Play class="w-5 h-5" />
                  </div>
                  <div>
                    <h3
                      class="font-medium text-gray-900 group-hover:text-primary transition-colors"
                    >
                      {{ run.name }}
                    </h3>
                    <div class="flex items-center space-x-2 mt-1 text-xs text-gray-500">
                      <span class="capitalize px-1.5 py-0.5 rounded bg-gray-100">{{
                        run.status.replace('_', ' ')
                      }}</span>
                      <span>• Started {{ new Date(run.started_at).toLocaleDateString() }}</span>
                    </div>
                  </div>
                </div>
                <div class="text-gray-400">
                  <ArrowRight class="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>
    </div>
  </div>
</template>

// frontend/src/svelte/views/playbooks/PlaybooksView.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { get } from 'svelte/store'
  import { ArrowRight, BookOpen, CheckCircle2, Loader2, Play, Plus } from 'lucide-svelte'
  import { authStore } from '../../stores/auth'
  import { chatStore } from '../../stores/chat'
  import { playbooksStore } from '../../stores/playbooks'
  import type { Playbook } from '../../stores/playbooks'

  let activeTab = $state<'library' | 'runs'>('library')
  let teamId = $state<string | null>(null)

  function navigate(path: string) {
    window.history.pushState({}, '', path)
    window.dispatchEvent(new PopStateEvent('popstate'))
  }

  async function loadPlaybooks() {
    if (get(chatStore).teams.length === 0) {
      await chatStore.fetchTeams()
    }

    teamId = get(chatStore).teams[0]?.id ?? null
    if (!teamId) return

    await Promise.all([
      playbooksStore.fetchPlaybooks(teamId),
      playbooksStore.fetchRuns(teamId),
    ])
  }

  async function startRun(playbook: Playbook) {
    if (!teamId || $playbooksStore.saving) return

    const run = await playbooksStore.startRun(teamId, {
      playbook_id: playbook.id,
      name: playbook.name,
      owner_id: $authStore.user?.id,
    })
    navigate(`/runs/${run.run.id}`)
  }

  function formatDate(value: string) {
    return new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
  }

  onMount(() => {
    void loadPlaybooks()
  })
</script>

<main class="min-h-screen bg-bg-app text-text-1">
  <header class="border-b border-border-1 bg-bg-surface-1 px-6 py-5">
    <div class="mx-auto flex max-w-6xl items-center justify-between gap-4">
      <div class="flex items-center gap-3">
        <div class="flex h-11 w-11 items-center justify-center rounded-r-3 bg-brand/10 text-brand">
          <BookOpen class="h-5 w-5" />
        </div>
        <div>
          <h1 class="text-xl font-bold">Playbooks</h1>
          <p class="text-sm text-text-3">Create repeatable workflows and track active runs.</p>
        </div>
      </div>

      <button
        type="button"
        class="inline-flex items-center gap-2 rounded-r-2 bg-brand px-4 py-2.5 text-sm font-semibold text-brand-foreground transition-standard hover:bg-brand-hover"
        on:click={() => navigate('/playbooks/new')}
      >
        <Plus class="h-4 w-4" />
        Create Playbook
      </button>
    </div>
  </header>

  <section class="mx-auto max-w-6xl px-6 py-6">
    <div class="mb-5 flex gap-2 border-b border-border-1">
      <button
        type="button"
        class="border-b-2 px-1 pb-3 text-sm font-semibold transition-standard {activeTab === 'library' ? 'border-brand text-brand' : 'border-transparent text-text-3 hover:text-text-1'}"
        on:click={() => (activeTab = 'library')}
      >
        Library
      </button>
      <button
        type="button"
        class="border-b-2 px-1 pb-3 text-sm font-semibold transition-standard {activeTab === 'runs' ? 'border-brand text-brand' : 'border-transparent text-text-3 hover:text-text-1'}"
        on:click={() => (activeTab = 'runs')}
      >
        Runs
      </button>
    </div>

    {#if $playbooksStore.error}
      <div class="mb-4 rounded-r-2 border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger" role="alert">
        {$playbooksStore.error}
      </div>
    {/if}

    {#if $playbooksStore.loading}
      <div class="flex items-center justify-center rounded-r-3 border border-border-1 bg-bg-surface-1 py-16 text-text-3">
        <Loader2 class="mr-2 h-5 w-5 animate-spin" />
        Loading playbooks...
      </div>
    {:else if activeTab === 'library'}
      <div class="grid gap-4 md:grid-cols-2">
        {#each $playbooksStore.playbooks as playbook (playbook.id)}
          <article class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1 transition-standard hover:-translate-y-0.5 hover:shadow-2">
            <div class="flex items-start justify-between gap-4">
              <div class="min-w-0">
                <h2 class="truncate text-lg font-bold">{playbook.name}</h2>
                <p class="mt-1 line-clamp-2 text-sm text-text-3">{playbook.description || 'No description yet.'}</p>
              </div>
              <span class="rounded-full bg-bg-surface-2 px-2.5 py-1 text-xs font-semibold text-text-3">
                {playbook.is_public ? 'Public' : 'Private'}
              </span>
            </div>

            <div class="mt-5 flex flex-wrap items-center justify-between gap-3">
              <p class="text-xs text-text-3">Updated {formatDate(playbook.updated_at)}</p>
              <div class="flex gap-2">
                <button
                  type="button"
                  class="rounded-r-2 border border-border-1 px-3 py-2 text-sm font-medium text-text-2 transition-standard hover:bg-bg-surface-2"
                  on:click={() => navigate(`/playbooks/${playbook.id}/edit`)}
                >
                  Edit
                </button>
                <button
                  type="button"
                  class="inline-flex items-center gap-2 rounded-r-2 bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground transition-standard hover:bg-brand-hover disabled:opacity-60"
                  disabled={$playbooksStore.saving}
                  on:click={() => startRun(playbook)}
                >
                  <Play class="h-4 w-4" />
                  Run
                </button>
              </div>
            </div>
          </article>
        {:else}
          <div class="rounded-r-3 border border-dashed border-border-1 bg-bg-surface-1 py-16 text-center md:col-span-2">
            <BookOpen class="mx-auto mb-3 h-10 w-10 text-text-4" />
            <h2 class="text-lg font-semibold">No playbooks yet</h2>
            <p class="mt-1 text-sm text-text-3">Create your first workflow to make repeatable work easier.</p>
          </div>
        {/each}
      </div>
    {:else}
      <div class="space-y-3">
        {#each $playbooksStore.runs as run (run.id)}
          <button
            type="button"
            class="flex w-full items-center justify-between gap-4 rounded-r-3 border border-border-1 bg-bg-surface-1 p-4 text-left shadow-1 transition-standard hover:bg-bg-surface-2"
            on:click={() => navigate(`/runs/${run.id}`)}
          >
            <div class="flex items-center gap-3">
              <div class="flex h-10 w-10 items-center justify-center rounded-r-2 bg-success/10 text-success">
                <CheckCircle2 class="h-5 w-5" />
              </div>
              <div>
                <h2 class="font-semibold">{run.name}</h2>
                <p class="text-xs text-text-3">{run.status.replace('_', ' ')} since {formatDate(run.started_at)}</p>
              </div>
            </div>
            <ArrowRight class="h-5 w-5 text-text-3" />
          </button>
        {:else}
          <div class="rounded-r-3 border border-dashed border-border-1 bg-bg-surface-1 py-16 text-center">
            <Play class="mx-auto mb-3 h-10 w-10 text-text-4" />
            <h2 class="text-lg font-semibold">No active runs</h2>
            <p class="mt-1 text-sm text-text-3">Start a playbook run to track progress here.</p>
          </div>
        {/each}
      </div>
    {/if}
  </section>
</main>
