// frontend/src/components/playbooks/PlaybookEditor.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Plus, Trash2, GripVertical, CheckSquare, Save, ArrowLeft, X } from 'lucide-vue-next'
import { usePlaybookStore } from '../../features/playbooks/stores/playbookStore'
import BaseButton from '../atomic/BaseButton.vue'
import { useToast } from '../../composables/useToast'
import { type ChecklistWithTasks, playbooksApi } from '../../api/playbooks'
import { getErrorMessage } from '@/core/errors/errorUtils'

const router = useRouter()
const route = useRoute()
const playbookStore = usePlaybookStore()
const toast = useToast()

const props = defineProps<{
  id?: string // If present, editing existing playbook
}>()

const loading = ref(false)
const saving = ref(false)

const form = ref({
  name: '',
  description: '',
  icon: '📘',
  is_public: false,
  create_channel_on_run: true,
  channel_name_template: 'incident-{{date}}',
  keyword_triggers: '',
})

const checklists = ref<ChecklistWithTasks[]>([])

const isEditing = computed(() => !!props.id || !!route.params.id)

onMounted(async () => {
  const playbookId = (props.id || route.params.id) as string
  if (playbookId) {
    loading.value = true
    try {
      await playbookStore.fetchPlaybook(playbookId)
      const playbook = playbookStore.currentPlaybook
      if (playbook) {
        form.value = {
          name: playbook.name,
          description: playbook.description || '',
          icon: playbook.icon || '📘',
          is_public: playbook.is_public,
          create_channel_on_run: playbook.create_channel_on_run,
          channel_name_template: playbook.channel_name_template || '',
          keyword_triggers: playbook.keyword_triggers?.join(', ') || '',
        }
        checklists.value = JSON.parse(JSON.stringify(playbook.checklists))
      }
    } catch (e) {
      toast.error('Error', 'Failed to load playbook')
    } finally {
      loading.value = false
    }
  } else {
    // Add default checklist for new playbook
    checklists.value = [
      {
        id: 'temp-1',
        playbook_id: '',
        name: 'Default Checklist',
        sort_order: 1,
        created_at: new Date().toISOString(),
        tasks: [],
      },
    ]
  }
})

function addChecklist() {
  checklists.value.push({
    id: `temp-${Date.now()}`,
    playbook_id: '',
    name: 'New Checklist',
    sort_order: checklists.value.length + 1,
    created_at: new Date().toISOString(),
    tasks: [],
  })
}

function removeChecklist(index: number) {
  if (checklists.value[index]) {
    checklists.value.splice(index, 1)
  }
}

function addTask(checklistIndex: number) {
  const checklist = checklists.value[checklistIndex]
  if (checklist) {
    checklist.tasks.push({
      id: `temp-task-${Date.now()}`,
      checklist_id: checklist.id,
      title: '',
      description: '',
      default_assignee_id: null,
      assignee_role: null,
      due_after_minutes: null,
      slash_command: null,
      webhook_url: null,
      sort_order: checklist.tasks.length + 1,
      created_at: new Date().toISOString(),
    })
  }
}

function removeTask(checklistIndex: number, taskIndex: number) {
  const checklist = checklists.value[checklistIndex]
  if (checklist && checklist.tasks[taskIndex]) {
    checklist.tasks.splice(taskIndex, 1)
  }
}

async function save() {
  if (!form.value.name) {
    toast.error('Validation error', 'Playbook name is required')
    return
  }

  saving.value = true
  try {
    let playbookId = props.id || (route.params.id as string)

    const payload = {
      ...form.value,
      keyword_triggers: form.value.keyword_triggers
        .split(',')
        .map(s => s.trim())
        .filter(s => s.length > 0),
    }

    // 1. Create or Update Playbook
    if (isEditing.value) {
      await playbookStore.updatePlaybook(playbookId, payload)
    } else {
      const newPlaybook = await playbookStore.createPlaybook(payload)
      if (newPlaybook) {
        playbookId = newPlaybook.id
      }
    }

    // 2. Sync Checklists and Tasks
    // We iterate through checklists and create them if they have temp IDs
    // For tasks, we do the same
    if (playbookId) {
      // Simplified sync logic for MVP - just create new checklists/tasks that are temp
      // Real implementation would need proper diffing/updating
      for (const checklist of checklists.value) {
        if (checklist.id.startsWith('temp-')) {
          const newChecklist = await playbooksApi.createChecklist(playbookId, {
            name: checklist.name,
            sort_order: checklist.sort_order,
          })
          // Create tasks for this new checklist
          for (const task of checklist.tasks) {
            await playbooksApi.createTask(newChecklist.data.id, {
              title: task.title,
              description: task.description,
              sort_order: task.sort_order,
            })
          }
        } else {
          // Existing checklist, check for new tasks
          for (const task of checklist.tasks) {
            if (task.id.startsWith('temp-')) {
              await playbooksApi.createTask(checklist.id, {
                title: task.title,
                description: task.description,
                sort_order: task.sort_order,
              })
            }
          }
        }
      }
    }

    toast.success('Saved', 'Playbook saved successfully')
    router.push('/playbooks')
  } catch (e: unknown) {
    toast.error('Error', getErrorMessage(e, 'Failed to save playbook'))
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div class="h-full flex flex-col bg-bg-surface-2">
    <!-- Header -->
    <header
      class="bg-bg-surface-1 border-b border-border-1 px-6 py-4 flex justify-between items-center"
    >
      <div class="flex items-center space-x-4">
        <button class="p-2 hover:bg-bg-surface-2 rounded-lg" @click="router.back()">
          <ArrowLeft class="w-5 h-5 text-text-3" />
        </button>
        <div>
          <h1 class="text-xl font-bold text-text-1">
            {{ isEditing ? 'Edit Playbook' : 'Create Playbook' }}
          </h1>
        </div>
      </div>
      <BaseButton :loading="saving" @click="save">
        <Save class="w-4 h-4 mr-2" />
        Save Playbook
      </BaseButton>
    </header>

    <!-- Content -->
    <div class="flex-1 overflow-y-auto p-6 max-w-4xl mx-auto w-full">
      <div class="space-y-8">
        <!-- General Settings -->
        <section class="bg-bg-surface-1 rounded-xl border border-border-1 p-6 shadow-sm">
          <h2 class="text-lg font-semibold mb-4 text-text-1">General Information</h2>
          <div class="space-y-4">
            <div class="flex space-x-4">
              <div class="w-20">
                <label class="block text-sm font-medium text-text-2 mb-1">Icon</label>
                <input
                  v-model="form.icon"
                  class="w-full text-center text-2xl px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1"
                />
              </div>
              <div class="flex-1">
                <label class="block text-sm font-medium text-text-2 mb-1">Name</label>
                <input
                  v-model="form.name"
                  type="text"
                  placeholder="e.g. Incident Response"
                  class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1"
                />
              </div>
            </div>
            <div>
              <label class="block text-sm font-medium text-text-2 mb-1">Description</label>
              <textarea
                v-model="form.description"
                rows="2"
                class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1"
              ></textarea>
            </div>
          </div>
        </section>

        <!-- Automation Settings -->
        <section class="bg-bg-surface-1 rounded-xl border border-border-1 p-6 shadow-sm">
          <h2 class="text-lg font-semibold mb-4 text-text-1">Automation & Settings</h2>
          <div class="space-y-4">
            <div class="flex items-center space-x-2">
              <input
                id="is_public"
                v-model="form.is_public"
                type="checkbox"
                class="rounded border-border-2 text-primary focus:ring-brand"
              />
              <label for="is_public" class="text-sm font-medium text-text-2"
                >Public (visible to everyone in team)</label
              >
            </div>

            <div class="border-t border-border-1 pt-4">
              <div class="flex items-center space-x-2 mb-2">
                <input
                  id="create_channel"
                  v-model="form.create_channel_on_run"
                  type="checkbox"
                  class="rounded border-border-2 text-primary focus:ring-brand"
                />
                <label for="create_channel" class="text-sm font-medium text-text-2"
                  >Create new channel on run</label
                >
              </div>

              <div v-if="form.create_channel_on_run" class="ml-6">
                <label class="block text-sm font-medium text-text-2 mb-1"
                  >Channel Name Template</label
                >
                <input
                  v-model="form.channel_name_template"
                  type="text"
                  placeholder="incident-{{date}}"
                  class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1"
                />
                <p v-pre class="text-xs text-text-3 mt-1">
                  Available variables: {{ date }}, {{ playbook_name }}
                </p>
              </div>
            </div>

            <div class="border-t border-border-1 pt-4">
              <label class="block text-sm font-medium text-text-2 mb-1">Keyword Triggers</label>
              <input
                v-model="form.keyword_triggers"
                type="text"
                placeholder="e.g. incident, outage, server down"
                class="w-full px-3 py-2 border border-border-2 rounded-lg bg-bg-surface-1 text-text-1"
              />
              <p class="text-xs text-text-3 mt-1">
                Comma separated keywords that will trigger a prompt to start this playbook.
              </p>
            </div>
          </div>
        </section>

        <!-- Checklists & Tasks -->
        <section class="space-y-6">
          <div class="flex items-center justify-between">
            <h2 class="text-lg font-semibold text-text-1">Checklists & Tasks</h2>
            <BaseButton variant="secondary" size="sm" @click="addChecklist">
              <Plus class="w-4 h-4 mr-2" />
              Add Checklist
            </BaseButton>
          </div>

          <div
            v-for="(checklist, cIndex) in checklists"
            :key="checklist.id"
            class="bg-bg-surface-1 rounded-xl border border-border-1 overflow-hidden shadow-sm"
          >
            <!-- Checklist Header -->
            <div class="bg-bg-surface-2 p-4 flex items-center space-x-3 border-b border-border-1">
              <GripVertical class="w-5 h-5 text-text-3 cursor-move" />
              <input
                v-model="checklist.name"
                class="flex-1 bg-transparent font-medium text-text-1 focus:outline-none focus:ring-2 focus:ring-primary rounded px-2"
                placeholder="Checklist Name"
              />
              <button class="text-text-3 hover:text-danger" @click="removeChecklist(cIndex)">
                <Trash2 class="w-4 h-4" />
              </button>
            </div>

            <!-- Tasks -->
            <div class="p-4 space-y-2">
              <div
                v-for="(task, tIndex) in checklist.tasks"
                :key="task.id"
                class="flex items-start space-x-3 group"
              >
                <CheckSquare class="w-5 h-5 text-text-3 mt-2" />
                <div class="flex-1 space-y-1">
                  <input
                    v-model="task.title"
                    class="w-full bg-transparent border-b border-transparent hover:border-border-1 focus:border-primary focus:outline-none py-1 text-text-1"
                    placeholder="Task title..."
                  />
                  <input
                    v-model="task.description"
                    class="w-full text-sm bg-transparent border-none focus:ring-0 p-0 text-text-3"
                    placeholder="Description (optional)"
                  />
                </div>
                <button
                  class="opacity-0 group-hover:opacity-100 text-text-3 hover:text-danger p-1"
                  @click="removeTask(cIndex, tIndex)"
                >
                  <X class="w-4 h-4" />
                </button>
              </div>

              <button
                class="flex items-center text-sm text-text-3 hover:text-primary mt-2 px-1"
                @click="addTask(cIndex)"
              >
                <Plus class="w-4 h-4 mr-1" />
                Add Task
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

// frontend/src/svelte/views/playbooks/PlaybookEditor.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { get } from 'svelte/store'
  import { ArrowLeft, Loader2, Plus, Save, Trash2 } from 'lucide-svelte'
  import { chatStore } from '../../stores/chat'
  import { playbooksStore } from '../../stores/playbooks'
  import type { ChecklistWithTasks } from '../../stores/playbooks'

  type EditableChecklist = ChecklistWithTasks

  let playbookId = $state<string | null>(null)
  let teamId = $state<string | null>(null)
  let loading = $state(false)
  let saving = $state(false)
  let error = $state<string | null>(null)
  let form = $state({
    name: '',
    description: '',
    icon: 'book',
    is_public: false,
    create_channel_on_run: true,
    channel_name_template: 'incident-{{date}}',
    keyword_triggers: '',
  })
  let checklists = $state<EditableChecklist[]>([])

  const isEditing = $derived(Boolean(playbookId))

  function navigate(path: string) {
    window.history.pushState({}, '', path)
    window.dispatchEvent(new PopStateEvent('popstate'))
  }

  function back() {
    navigate('/playbooks')
  }

  function makeChecklist(name = 'Default checklist'): EditableChecklist {
    return {
      id: `temp-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      playbook_id: playbookId ?? '',
      name,
      sort_order: checklists.length + 1,
      created_at: new Date().toISOString(),
      tasks: [],
    }
  }

  function addChecklist() {
    checklists = [...checklists, makeChecklist('New checklist')]
  }

  function removeChecklist(index: number) {
    checklists = checklists.filter((_, currentIndex) => currentIndex !== index)
  }

  function addTask(checklistIndex: number) {
    checklists = checklists.map((checklist, currentIndex) => {
      if (currentIndex !== checklistIndex) return checklist

      return {
        ...checklist,
        tasks: [
          ...checklist.tasks,
          {
            id: `temp-task-${Date.now()}-${Math.random().toString(36).slice(2)}`,
            checklist_id: checklist.id,
            title: '',
            description: '',
            default_assignee_id: null,
            assignee_role: null,
            due_after_minutes: null,
            slash_command: null,
            webhook_url: null,
            sort_order: checklist.tasks.length + 1,
            created_at: new Date().toISOString(),
          },
        ],
      }
    })
  }

  function removeTask(checklistIndex: number, taskIndex: number) {
    checklists = checklists.map((checklist, currentIndex) => {
      if (currentIndex !== checklistIndex) return checklist

      return {
        ...checklist,
        tasks: checklist.tasks.filter((_, currentTaskIndex) => currentTaskIndex !== taskIndex),
      }
    })
  }

  async function load() {
    const match = window.location.pathname.match(/^\/playbooks\/([^/]+)\/edit$/)
    playbookId = match?.[1] ?? null

    if (get(chatStore).teams.length === 0) {
      await chatStore.fetchTeams()
    }
    teamId = get(chatStore).teams[0]?.id ?? null

    if (!playbookId) {
      checklists = [makeChecklist()]
      return
    }

    loading = true
    error = null
    try {
      const playbook = await playbooksStore.fetchPlaybook(playbookId)
      form = {
        name: playbook.name,
        description: playbook.description ?? '',
        icon: playbook.icon ?? 'book',
        is_public: playbook.is_public,
        create_channel_on_run: playbook.create_channel_on_run,
        channel_name_template: playbook.channel_name_template ?? '',
        keyword_triggers: playbook.keyword_triggers?.join(', ') ?? '',
      }
      checklists = structuredClone(playbook.checklists ?? [])
      if (checklists.length === 0) {
        checklists = [makeChecklist()]
      }
    } catch (loadError) {
      error = loadError instanceof Error ? loadError.message : 'Failed to load playbook.'
    } finally {
      loading = false
    }
  }

  async function save() {
    if (!teamId || saving) return
    if (!form.name.trim()) {
      error = 'Playbook name is required.'
      return
    }

    saving = true
    error = null
    try {
      const payload = {
        name: form.name.trim(),
        description: form.description.trim(),
        icon: form.icon.trim(),
        is_public: form.is_public,
        create_channel_on_run: form.create_channel_on_run,
        channel_name_template: form.channel_name_template.trim(),
        keyword_triggers: form.keyword_triggers
          .split(',')
          .map((keyword) => keyword.trim())
          .filter(Boolean),
      }

      let savedPlaybookId = playbookId
      if (savedPlaybookId) {
        await playbooksStore.updatePlaybook(savedPlaybookId, payload)
      } else {
        const created = await playbooksStore.createPlaybook(teamId, payload)
        savedPlaybookId = created.id
      }

      for (const checklist of checklists) {
        let checklistId = checklist.id
        if (checklist.id.startsWith('temp-')) {
          const createdChecklist = await playbooksStore.createChecklist(savedPlaybookId, {
            name: checklist.name,
            sort_order: checklist.sort_order,
          })
          checklistId = (createdChecklist.data as { id: string }).id
        }

        for (const task of checklist.tasks) {
          if (task.id.startsWith('temp-task-') && task.title.trim()) {
            await playbooksStore.createTask(checklistId, {
              title: task.title.trim(),
              description: task.description?.trim() || null,
              sort_order: task.sort_order,
            })
          }
        }
      }

      navigate('/playbooks')
    } catch (saveError) {
      error = saveError instanceof Error ? saveError.message : 'Failed to save playbook.'
    } finally {
      saving = false
    }
  }

  onMount(() => {
    void load()
  })
</script>

<main class="min-h-screen bg-bg-app text-text-1">
  <header class="border-b border-border-1 bg-bg-surface-1 px-6 py-4">
    <div class="mx-auto flex max-w-5xl items-center justify-between gap-4">
      <div class="flex items-center gap-3">
        <button
          type="button"
          class="flex h-9 w-9 items-center justify-center rounded-r-2 text-text-3 transition-standard hover:bg-bg-surface-2 hover:text-text-1"
          aria-label="Back to playbooks"
          on:click={back}
        >
          <ArrowLeft class="h-5 w-5" />
        </button>
        <div>
          <h1 class="text-xl font-bold">{isEditing ? 'Edit Playbook' : 'Create Playbook'}</h1>
          <p class="text-sm text-text-3">Define the reusable checklist your team will run.</p>
        </div>
      </div>
      <button
        type="button"
        class="inline-flex items-center gap-2 rounded-r-2 bg-brand px-4 py-2.5 text-sm font-semibold text-brand-foreground transition-standard hover:bg-brand-hover disabled:opacity-60"
        disabled={saving || loading}
        on:click={save}
      >
        {#if saving}
          <Loader2 class="h-4 w-4 animate-spin" />
          Saving...
        {:else}
          <Save class="h-4 w-4" />
          Save Playbook
        {/if}
      </button>
    </div>
  </header>

  <section class="mx-auto max-w-5xl space-y-6 px-6 py-6">
    {#if error}
      <div class="rounded-r-2 border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger" role="alert">
        {error}
      </div>
    {/if}

    {#if loading}
      <div class="flex items-center justify-center rounded-r-3 border border-border-1 bg-bg-surface-1 py-16 text-text-3">
        <Loader2 class="mr-2 h-5 w-5 animate-spin" />
        Loading playbook...
      </div>
    {:else}
      <section class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
        <h2 class="mb-4 text-lg font-bold">General</h2>
        <div class="grid gap-4 sm:grid-cols-[8rem_1fr]">
          <label class="block">
            <span class="mb-1 block text-sm font-medium text-text-2">Icon</span>
            <input class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={form.icon} />
          </label>
          <label class="block">
            <span class="mb-1 block text-sm font-medium text-text-2">Name</span>
            <input class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={form.name} placeholder="Incident response" />
          </label>
        </div>
        <label class="mt-4 block">
          <span class="mb-1 block text-sm font-medium text-text-2">Description</span>
          <textarea class="min-h-24 w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={form.description}></textarea>
        </label>
        <div class="mt-4 grid gap-4 sm:grid-cols-2">
          <label class="flex items-center gap-2 text-sm text-text-2">
            <input type="checkbox" bind:checked={form.is_public} />
            Public to the team
          </label>
          <label class="flex items-center gap-2 text-sm text-text-2">
            <input type="checkbox" bind:checked={form.create_channel_on_run} />
            Create channel on run
          </label>
        </div>
        <label class="mt-4 block">
          <span class="mb-1 block text-sm font-medium text-text-2">Channel name template</span>
          <input class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={form.channel_name_template} />
        </label>
        <label class="mt-4 block">
          <span class="mb-1 block text-sm font-medium text-text-2">Keyword triggers</span>
          <input class="w-full rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={form.keyword_triggers} placeholder="incident, outage" />
        </label>
      </section>

      <section class="space-y-4">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-bold">Checklists</h2>
          <button type="button" class="inline-flex items-center gap-2 rounded-r-2 border border-border-1 px-3 py-2 text-sm font-semibold" on:click={addChecklist}>
            <Plus class="h-4 w-4" />
            Add Checklist
          </button>
        </div>

        {#each checklists as checklist, checklistIndex (checklist.id)}
          <article class="rounded-r-3 border border-border-1 bg-bg-surface-1 p-5 shadow-1">
            <div class="flex gap-3">
              <input class="min-w-0 flex-1 rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm font-semibold" bind:value={checklist.name} />
              <button type="button" class="rounded-r-2 p-2 text-text-3 transition-standard hover:bg-danger/10 hover:text-danger" aria-label="Remove checklist" on:click={() => removeChecklist(checklistIndex)}>
                <Trash2 class="h-4 w-4" />
              </button>
            </div>

            <div class="mt-4 space-y-3">
              {#each checklist.tasks as task, taskIndex (task.id)}
                <div class="grid gap-2 rounded-r-2 bg-bg-surface-2 p-3 sm:grid-cols-[1fr_1fr_auto]">
                  <input class="rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={task.title} placeholder="Task title" />
                  <input class="rounded-r-2 border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm" bind:value={task.description} placeholder="Optional description" />
                  <button type="button" class="rounded-r-2 p-2 text-text-3 transition-standard hover:bg-danger/10 hover:text-danger" aria-label="Remove task" on:click={() => removeTask(checklistIndex, taskIndex)}>
                    <Trash2 class="h-4 w-4" />
                  </button>
                </div>
              {/each}
              <button type="button" class="inline-flex items-center gap-2 rounded-r-2 border border-dashed border-border-1 px-3 py-2 text-sm text-text-2" on:click={() => addTask(checklistIndex)}>
                <Plus class="h-4 w-4" />
                Add Task
              </button>
            </div>
          </article>
        {/each}
      </section>
    {/if}
  </section>
</main>
