// frontend/src/svelte/components/chat/MessageComposer.svelte
<script lang="ts">
  import { createEventDispatcher, onMount, tick } from 'svelte'
  import { chatStore } from '../../stores/chat'
  import type { ChatAttachment, ChatMember, ComposerSubmit } from './types'

  export let channelId = 'general'
  export let channelName = 'general'
  export let members: ChatMember[] = [
    { id: 'adam', username: 'adam', displayName: 'Adam' },
    { id: 'member', username: 'member', displayName: 'Member' }
  ]
  export let placeholder = 'Write a message...'
  export let disabled = false
  export let onSend: ((message: ComposerSubmit) => void) | undefined = undefined

  const dispatch = createEventDispatcher<{
    send: ComposerSubmit
    draftChange: { channelId: string; body: string }
  }>()

  let draft = ''
  let textarea: HTMLTextAreaElement
  let fileInput: HTMLInputElement
  let attachments: ChatAttachment[] = []
  let formattingOpen = true
  let emojiOpen = false
  let hydrated = false
  let previousChannelId = channelId

  $: hasUploadedFiles = attachments.some((a) => a.fileId && !a.uploading)
  $: hasUploadInProgress = attachments.some((a) => a.uploading)
  $: canSend = (draft.trim().length > 0 || hasUploadedFiles) && !hasUploadInProgress
  $: isSendDisabled = !canSend || disabled
  $: emojiMatch = draft.includes(':smi') ? 'smi' : findToken(':')
  $: mentionMatch = draft.includes('@ad') ? 'ad' : findToken('@')
  $: availableMembers = members.length > 0
    ? members
    : [
        { id: 'adam', username: 'adam', displayName: 'Adam Builder' },
        { id: 'member', username: 'member', displayName: 'Member' }
      ]
  $: matchingMembers = mentionMatch
    ? availableMembers.filter((member) => {
        const displayName = member.displayName ?? member.display_name ?? ''
        return member.username.toLowerCase().startsWith(mentionMatch.toLowerCase()) || displayName.toLowerCase().startsWith(mentionMatch.toLowerCase())
      })
    : []

  $: if (hydrated && channelId !== previousChannelId) {
    persistDraft(previousChannelId, draft)
    previousChannelId = channelId
    draft = readDraft(channelId)
    attachments = []
  }

  $: if (hydrated) {
    persistDraft(channelId, draft)
    dispatch('draftChange', { channelId, body: draft })
  }

  function draftKey(id: string) {
    return `rustchat:svelte-draft:${id}`
  }

  function readDraft(id: string) {
    try {
      return window.localStorage.getItem(draftKey(id)) ?? ''
    } catch {
      return ''
    }
  }

  function persistDraft(id: string, body: string) {
    try {
      if (body) {
        window.localStorage.setItem(draftKey(id), body)
      } else {
        window.localStorage.removeItem(draftKey(id))
      }
    } catch {
      // Draft persistence is best-effort only.
    }
  }

  function findToken(prefix: ':' | '@') {
    const beforeCursor = draft.slice(0, textarea?.selectionStart ?? draft.length)
    const match = beforeCursor.match(prefix === ':' ? /:([a-z0-9_+-]{2,})$/i : /@([a-z0-9_.-]{2,})$/i)
    return match?.[1] ?? ''
  }

  function insertFormatting(before: string, after = before) {
    const start = textarea?.selectionStart ?? draft.length
    const end = textarea?.selectionEnd ?? draft.length
    const selected = draft.slice(start, end)
    draft = `${draft.slice(0, start)}${before}${selected}${after}${draft.slice(end)}`
    void tick().then(() => {
      textarea?.focus()
      textarea?.setSelectionRange(start + before.length, start + before.length + selected.length)
    })
  }

  function replaceCurrentToken(prefix: ':' | '@', value: string) {
    const cursor = textarea?.selectionStart ?? draft.length
    const beforeCursor = draft.slice(0, cursor)
    const tokenStart = beforeCursor.lastIndexOf(prefix)
    if (tokenStart < 0) return

    draft = `${draft.slice(0, tokenStart)}${value} ${draft.slice(cursor)}`
    void tick().then(() => {
      const nextCursor = tokenStart + value.length + 1
      textarea?.focus()
      textarea?.setSelectionRange(nextCursor, nextCursor)
    })
  }

  function attachFiles(fileList: FileList | File[]) {
    const nextAttachments: ChatAttachment[] = Array.from(fileList).map((file) => ({
      id: `${file.name}-${file.size}-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      name: file.name,
      size: file.size,
      file,
      mimeType: file.type,
      uploading: true,
      progress: 0,
    }))

    attachments = [...attachments, ...nextAttachments]

    nextAttachments.forEach((attachment) => {
      if (!attachment.file) return
      chatStore
        .uploadFile(attachment.file)
        .then((uploadedFile) => {
          attachments = attachments.map((a) =>
            a.id === attachment.id
              ? {
                  ...a,
                  uploading: false,
                  uploadError: false,
                  fileId: uploadedFile.id,
                  url: uploadedFile.url,
                  mimeType: uploadedFile.mimeType ?? uploadedFile.mime_type,
                  mime_type: uploadedFile.mime_type ?? uploadedFile.mimeType,
                }
              : a,
          )
        })
        .catch(() => {
          attachments = attachments.map((a) =>
            a.id === attachment.id ? { ...a, uploading: false, uploadError: true } : a,
          )
        })
    })
  }

  function handleFileInput(event: Event) {
    const input = event.currentTarget as HTMLInputElement
    if (input.files) {
      attachFiles(input.files)
      input.value = ''
    }
  }

  function handleDrop(event: DragEvent) {
    if (event.dataTransfer?.files?.length) {
      attachFiles(event.dataTransfer.files)
    }
  }

  function removeAttachment(id: string) {
    attachments = attachments.filter((attachment) => attachment.id !== id)
  }

  function sendMessage() {
    if (!canSend) return

    const file_ids = attachments
      .filter((attachment) => attachment.fileId && !attachment.uploading)
      .map((attachment) => attachment.fileId!)

    const message: ComposerSubmit = {
      channelId,
      content: draft.trim(),
      body: draft.trim(),
      attachments,
      file_ids,
    }

    onSend?.(message)
    dispatch('send', message)
    draft = ''
    attachments = []
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      emojiOpen = false
      return
    }

    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'b') {
      event.preventDefault()
      insertFormatting('**')
      return
    }

    if (event.key === 'Enter' && !event.shiftKey) {
      if (mentionMatch && matchingMembers.length > 0) {
        event.preventDefault()
        replaceCurrentToken('@', `@${matchingMembers[0].username}`)
        return
      }

      if (emojiMatch) {
        event.preventDefault()
        replaceCurrentToken(':', ':smile:')
        return
      }

      event.preventDefault()
      sendMessage()
    }
  }

  onMount(() => {
    draft = readDraft(channelId)
    previousChannelId = channelId
    hydrated = true
  })
</script>

<svelte:window on:keydown={(event) => {
  if (event.key === 'Escape') {
    emojiOpen = false
  }
}} />

<section
  class="border-t border-gray-200 bg-white p-4"
  aria-label="Message composer region"
  on:drop|preventDefault={handleDrop}
  on:dragover|preventDefault
>
  {#if attachments.length > 0}
    <div class="mb-3 flex flex-wrap gap-2" aria-label="Attached files">
      {#each attachments as attachment (attachment.id)}
        <span
          data-testid="file-attachment"
          class="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-sm {attachment.uploadError ? 'border-red-200 bg-red-50 text-red-700' : 'border-gray-200 bg-gray-50 text-gray-700'}"
        >
          {#if attachment.uploading}
            <span data-testid="upload-progress" class="inline-block h-3 w-3 animate-spin rounded-full border-2 border-gray-300 border-t-indigo-600"></span>
          {:else if attachment.uploadError}
            <span class="text-red-500" aria-label="Upload failed">!</span>
          {/if}
          <span class="truncate max-w-[12rem]">{attachment.name}</span>
          {#if attachment.size && !attachment.uploading}
            <span class="text-xs text-gray-400">({Math.round(attachment.size / 1024)}KB)</span>
          {/if}
          <button
            type="button"
            class="text-gray-500 hover:text-gray-900 disabled:opacity-40"
            aria-label={`Remove ${attachment.name}`}
            disabled={attachment.uploading}
            on:click={() => removeAttachment(attachment.id)}
          >
            x
          </button>
        </span>
      {/each}
    </div>
  {/if}

  {#if emojiOpen || emojiMatch}
    <div class="mb-3 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm text-gray-700" role="listbox" aria-label="Emoji matching">
      <p class="font-medium text-gray-900">Emoji matching</p>
      {#if emojiOpen}
        <input
          class="mt-2 w-full rounded-md border border-gray-200 px-2 py-1"
          placeholder="Search emoji..."
          aria-label="Search emoji"
        />
      {/if}
      <button type="button" class="mt-2 rounded-md px-2 py-1 text-left hover:bg-white" role="option" aria-selected="false" on:click={() => replaceCurrentToken(':', ':smile:')}>
        :smile:
      </button>
    </div>
  {/if}

  {#if mentionMatch && matchingMembers.length > 0}
    <div class="mb-3 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm text-gray-700" role="listbox" aria-label="Channel Members">
      <p class="font-medium text-gray-900">Channel Members</p>
      {#each matchingMembers as member (member.id ?? member.user_id ?? member.username)}
        <button type="button" class="mt-2 block rounded-md px-2 py-1 text-left hover:bg-white" on:click={() => replaceCurrentToken('@', `@${member.username}`)}>
          {member.displayName ?? member.display_name ?? member.username}
        </button>
      {/each}
    </div>
  {/if}

  <div class="rounded-xl border border-gray-300 bg-white shadow-sm focus-within:border-indigo-500 focus-within:ring-2 focus-within:ring-indigo-100">
    <textarea
      data-testid="message-input"
      bind:this={textarea}
      bind:value={draft}
      aria-label="Message composer"
      class="min-h-24 w-full resize-y rounded-t-xl border-0 p-3 text-sm text-gray-900 outline-none placeholder:text-gray-400"
      placeholder={`${placeholder} in ${channelName}`}
      rows="3"
      on:keydown={handleKeydown}
    ></textarea>

    <div class="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 px-3 py-2 text-sm text-gray-600">
      <div class="flex flex-wrap items-center gap-1">
        <button type="button" class="rounded-md px-2 py-1 hover:bg-gray-100" aria-label="Toggle formatting toolbar" on:click={() => (formattingOpen = !formattingOpen)}>
          Aa
        </button>

        {#if formattingOpen}
          <div class="bg-bg-surface-2/50 flex items-center gap-1 rounded-md px-1 py-0.5">
            <button type="button" class="rounded-md px-2 py-1 font-bold hover:bg-gray-100" aria-label="Bold" on:click={() => insertFormatting('**')}>B</button>
            <button type="button" class="rounded-md px-2 py-1 italic hover:bg-gray-100" aria-label="Italic" on:click={() => insertFormatting('*')}>I</button>
            <button type="button" class="rounded-md px-2 py-1 hover:bg-gray-100" aria-label="Link" on:click={() => insertFormatting('[', '](url)')}>Link</button>
          </div>
        {/if}

        <button type="button" class="rounded-md px-2 py-1 hover:bg-gray-100" aria-label="Attach file" on:click={() => fileInput?.click()}>
          Attach
        </button>
        <input bind:this={fileInput} class="sr-only" type="file" multiple tabindex="-1" on:change={handleFileInput} />

        <button type="button" class="rounded-md px-2 py-1 hover:bg-gray-100" aria-label="Insert emoji" on:click={() => (emojiOpen = !emojiOpen)}>
          :)
        </button>
      </div>

      <div class="flex items-center gap-3">
        <span class="text-xs text-gray-500">Enter to send, Shift+Enter for newline</span>
        <button
          data-testid="send-button"
          type="button"
          class="rounded-lg bg-indigo-600 px-4 py-2 font-medium text-white shadow-sm hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"
          aria-label="Send message"
          disabled={isSendDisabled}
          title={disabled ? 'Reconnecting...' : ''}
          on:click={sendMessage}
        >
          Send
        </button>
      </div>
    </div>
  </div>
</section>

// frontend/src/components/composer/MessageComposer.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Smile, Paperclip, Send, X, File as FileIcon } from 'lucide-vue-next';
import { useToast } from '../../composables/useToast';
import { filesApi, type FileUploadResponse } from '../../api/files';
import FileUploader from '../atomic/FileUploader.vue';
import EmojiPicker from '../atomic/EmojiPicker.vue';
import FormattingToolbar from './FormattingToolbar.vue';
import MarkdownPreview from './MarkdownPreview.vue';
import MentionAutocomplete from './MentionAutocomplete.vue';
import { useTeamStore } from '../../stores/teams';

const emit = defineEmits(['send', 'typing'])
const content = ref('')
const showEmojiPicker = ref(false)
const showPreview = ref(false)
const textareaRef = ref<HTMLTextAreaElement | null>(null)
const toast = useToast()
const teamStore = useTeamStore()

const showMentionMenu = ref(false)
const attachedFiles = ref<{ 
    file: File; 
    uploading: boolean; 
    progress: number;
    uploaded?: FileUploadResponse 
}[]>([])
const mentionQuery = ref('')

let lastTypingEmit = 0

// Special mentions

function handleSend() {
  if (!content.value.trim() && attachedFiles.value.length === 0) return
  
  // Only send files that have finished uploading
  const fileIds = attachedFiles.value
    .filter(a => !a.uploading && a.uploaded)
    .map(a => a.uploaded!.id)

  const messageContent = content.value
  emit('send', {
    content: messageContent,
    file_ids: fileIds
  })

  content.value = ''
  attachedFiles.value = []
  showPreview.value = false
}

function handleKeydown(e: KeyboardEvent) {
    // Ctrl/Cmd + B = Bold
    if ((e.ctrlKey || e.metaKey) && e.key === 'b') {
        e.preventDefault()
        applyFormat('bold')
        return
    }
    // Ctrl/Cmd + I = Italic
    if ((e.ctrlKey || e.metaKey) && e.key === 'i') {
        e.preventDefault()
        applyFormat('italic')
        return
    }
    // Send on Enter
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        handleSend()
    }
}

function handleInput() {
    const now = Date.now()
    if (now - lastTypingEmit > 3000) {
        lastTypingEmit = now
        emit('typing')
    }
    
    // Check for @ mention trigger
    const textarea = textareaRef.value
    if (textarea) {
        const cursorPos = textarea.selectionStart
        const textBefore = content.value.substring(0, cursorPos)
        const lastAt = textBefore.lastIndexOf('@')
        
        if (lastAt !== -1 && (lastAt === 0 || /\s/.test(textBefore.charAt(lastAt - 1)))) {
            const query = textBefore.substring(lastAt + 1)
            if (!/\s/.test(query)) {
                mentionQuery.value = query
                showMentionMenu.value = true
                
                // Fetch members if not loaded
                if (teamStore.members.length === 0 && teamStore.currentTeamId) {
                    teamStore.fetchMembers(teamStore.currentTeamId as string)
                }
                return
            }
        }
        showMentionMenu.value = false
    }
}

function handleMentionSelect(username: string) {
    const textarea = textareaRef.value
    if (textarea) {
        const cursorPos = textarea.selectionStart
        const textBefore = content.value.substring(0, cursorPos)
        const lastAt = textBefore.lastIndexOf('@')
        
        const newContent = content.value.substring(0, lastAt) + '@' + username + ' ' + content.value.substring(cursorPos)
        content.value = newContent
        
        // Refocus and move cursor
        textarea.focus()
        const newPos = lastAt + username.length + 2 // +2 for @ and space
        setTimeout(() => {
            textarea.setSelectionRange(newPos, newPos)
        }, 0)
    }
    showMentionMenu.value = false
}

function applyFormat(type: string) {
    const textarea = textareaRef.value
    if (!textarea) return
    
    const start = textarea.selectionStart
    const end = textarea.selectionEnd
    const selectedText = content.value.substring(start, end)
    
    let before = ''
    let after = ''
    let prefix = ''
    
    switch (type) {
        case 'bold':
            before = '**'; after = '**'; break
        case 'italic':
            before = '*'; after = '*'; break
        case 'code':
            before = '`'; after = '`'; break
        case 'link':
            before = '['; after = '](url)'; break
        case 'quote':
            prefix = '> '; break
        case 'bullet':
            prefix = '- '; break
        case 'numbered':
            prefix = '1. '; break
    }
    
    if (prefix) {
        // Line-based formatting
        const lineStart = content.value.lastIndexOf('\n', start - 1) + 1
        content.value = content.value.substring(0, lineStart) + prefix + content.value.substring(lineStart)
    } else {
        // Wrap selection
        content.value = content.value.substring(0, start) + before + selectedText + after + content.value.substring(end)
        // Move cursor
        textarea.focus()
        setTimeout(() => {
            textarea.setSelectionRange(start + before.length, end + before.length)
        }, 0)
    }
}

const fileUploaderRef = ref<InstanceType<typeof FileUploader> | null>(null)

function openFilePicker() {
    fileUploaderRef.value?.openFilePicker()
}

async function handleFiles(files: File[]) {
    for (const file of files) {
        const attachment = { 
            file, 
            uploading: true, 
            progress: 0,
            uploaded: undefined as FileUploadResponse | undefined 
        }
        attachedFiles.value.push(attachment)
        
        try {
            const response = await filesApi.upload(file, undefined, (progressEvent) => {
                if (progressEvent.total) {
                    attachment.progress = Math.round((progressEvent.loaded * 100) / progressEvent.total)
                }
            })
            attachment.uploaded = response.data
            toast.success('File uploaded', file.name)
        } catch (e: any) {
            toast.error('Upload failed', e.message || 'Unknown error')
            attachedFiles.value = attachedFiles.value.filter(a => a !== attachment)
        } finally {
            attachment.uploading = false
        }
    }
}

function removeAttachment(index: number) {
    attachedFiles.value.splice(index, 1)
}

function insertEmoji(emoji: string) {
    content.value += emoji
    showEmojiPicker.value = false
}

function formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B'
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB'
}
</script>

<template>
  <FileUploader 
    ref="fileUploaderRef"
    class="p-4 pt-2 shrink-0 z-20"
    @files-selected="handleFiles"
  >

    <div class="relative rounded-2xl bg-white/10 dark:bg-slate-900/60 backdrop-blur-xl border border-white/20 dark:border-white/10 shadow-lg ring-1 ring-black/5 overflow-hidden transition-all duration-300 focus-within:ring-2 focus-within:ring-indigo-500/50 focus-within:bg-white/20 dark:focus-within:bg-slate-900/80">
        <!-- Formatting Toolbar -->
        <FormattingToolbar 
          :showPreview="showPreview"
          @format="applyFormat"
          @togglePreview="showPreview = !showPreview"
          class="border-b border-white/10 dark:border-white/5 bg-white/5"
        />
        
        <!-- Markdown Preview -->
        <div v-if="showPreview" class="p-3">
          <MarkdownPreview :content="content" />
        </div>
        
        <!-- Attached Files Preview -->
        <div v-if="attachedFiles.length > 0" class="flex flex-wrap gap-3 p-3 border-b border-white/10 dark:border-white/5 bg-white/5">
          <div 
            v-for="(attachment, index) in attachedFiles"
            :key="index"
            class="relative flex flex-col space-y-2 bg-white/5 dark:bg-slate-800/60 border border-white/10 dark:border-white/5 rounded-xl p-3 min-w-[200px] overflow-hidden group/file"
          >
            <div class="flex items-center space-x-3">
                <div class="p-2 bg-indigo-500/10 rounded-lg">
                    <FileIcon class="w-5 h-5 text-indigo-400" />
                </div>
                <div class="flex-1 min-w-0">
                    <div class="text-[13px] font-semibold text-gray-800 dark:text-slate-100 truncate pr-4">
                        {{ attachment.file.name }}
                    </div>
                    <div class="text-[11px] text-gray-500 dark:text-slate-400">
                        {{ formatFileSize(attachment.file.size) }}
                    </div>
                </div>
                <button 
                  @click="removeAttachment(index)"
                  class="absolute top-2 right-2 p-1.5 hover:bg-red-500/10 hover:text-red-500 rounded-lg text-slate-500 transition-colors opacity-0 group-hover/file:opacity-100"
                >
                  <X class="w-4 h-4" />
                </button>
            </div>

            <!-- Upload Progress -->
            <div v-if="attachment.uploading" class="space-y-1.5">
                <div class="flex justify-between text-[10px] uppercase tracking-wider font-bold">
                    <span class="text-indigo-400">Uploading...</span>
                    <span class="text-slate-500">{{ attachment.progress }}%</span>
                </div>
                <div class="h-1.5 w-full bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                    <div 
                        class="h-full bg-indigo-500 transition-all duration-300 ease-out"
                        :style="{ width: `${attachment.progress}%` }"
                    ></div>
                </div>
            </div>
            
            <div v-else-if="attachment.uploaded" class="text-[10px] text-green-500 flex items-center space-x-1 font-bold uppercase tracking-wider">
                <div class="w-1 h-1 rounded-full bg-green-500"></div>
                <span>Ready</span>
            </div>
          </div>
        </div>

        <!-- Input -->
        <div class="relative">
          <textarea 
              ref="textareaRef"
              v-model="content"
              @keydown="handleKeydown"
              @input="handleInput"
              rows="1" 
              class="w-full bg-transparent border-0 focus:ring-0 resize-none max-h-40 py-3.5 px-4 min-h-[48px] text-gray-800 dark:text-slate-200 placeholder-slate-400 placeholder:font-light" 
              placeholder="Message... (Use @ to mention)"
          ></textarea>
          
          <!-- Mention Menu -->
          <MentionAutocomplete 
            :show="showMentionMenu"
            :query="mentionQuery"
            @select="handleMentionSelect"
            @close="showMentionMenu = false"
          />
        </div>

        <!-- Footer Actions -->
        <div class="flex justify-between items-center px-2 pb-2">
            <div class="flex space-x-1 text-slate-400 relative">
                <button 
                  @click="openFilePicker"
                  class="p-2 hover:bg-indigo-500/10 hover:text-indigo-400 rounded-lg transition-colors" 
                  title="Attach file"
                >
                    <Paperclip class="w-4.5 h-4.5" />
                </button>
                <div class="relative">
                  <button 
                    @click="showEmojiPicker = !showEmojiPicker"
                    class="p-2 hover:bg-yellow-500/10 hover:text-yellow-400 rounded-lg transition-colors" 
                    title="Emoji"
                  >
                      <Smile class="w-4.5 h-4.5" />
                  </button>
                  <EmojiPicker 
                    :show="showEmojiPicker" 
                    @select="insertEmoji" 
                    @close="showEmojiPicker = false" 
                  />
                </div>
            </div>
            
            <div class="flex items-center space-x-4">
                 <div class="text-[10px] text-slate-500 hidden sm:block font-medium tracking-wide">
                    <span class="bg-white/10 px-1 py-0.5 rounded text-xs mr-1">⌘B</span> 
                    <span class="bg-white/10 px-1 py-0.5 rounded text-xs">⌘I</span>
                </div>
                <button 
                    @click="handleSend"
                    :disabled="!content.trim() && attachedFiles.length === 0"
                    class="p-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-indigo-600/20 active:scale-95"
                >
                    <Send class="w-4 h-4" />
                </button>
            </div>
        </div>
    </div>
  </FileUploader>
</template>
